  /* ============ DOCKER FOR DEVOPS — command simulator ============ */
  const DOCKER_CMDS = {
    pull: { syntax:`docker pull &lt;image&gt;:&lt;tag&gt;`, runs:[
      { cmd:`docker pull nginx:1.25`, output:`1.25: Pulling from library/nginx\na2318d6c47ec: Pull complete\nf8cd51b28d4d: Pull complete\n<span class="ok">Status: Downloaded newer image for nginx:1.25</span>`, reading:`Each layer downloads and prints "Pull complete" separately — Docker images are built from stacked layers, not one single blob.` },
      { cmd:`docker pull nginx:1.25`, output:`1.25: Pulling from library/nginx\n<span class="dim">Digest: sha256:2d194184b067...\nStatus: Image is up to date for nginx:1.25</span>`, reading:`"Image is up to date" instead of downloading again — Docker checks the digest first and skips re-pulling layers it already has locally.` },
      { cmd:`docker pull myrepo/myapp:v2`, output:`<span class="err">Error response from daemon: pull access denied for myrepo/myapp, repository does not exist or may require 'docker login'</span>`, reading:`This exact error means one of two things: the image name/tag is wrong, or it's private and you haven't authenticated — not a network problem.` }
    ], does:`Downloads an image (and its layers) from a registry to your local machine.`, where:`The first step before running any container — or Docker just does this automatically on the first "docker run."` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`pull`, desc:`download an image (and its layers)`},{term:`&lt;image&gt;:&lt;tag&gt;`, desc:`which image, and which version`}], whyUseful:`<div class="found-p">You're about to run a container from an image you haven't used before, and want to see exactly what's downloading before it's live.</div><div class="found-pre">$ docker pull nginx:1.25
Status: Downloaded newer image for nginx:1.25</div><div class="found-p"><span class="found-code">docker run</span> would auto-pull this anyway on first use — pulling ahead of time just makes the download visible and confirms the tag actually exists.</div>` },
    images: { syntax:`docker images`, runs:[
      { cmd:`docker images`, output:`REPOSITORY   TAG       IMAGE ID       CREATED        SIZE\nnginx        1.25      605c77e624dd   2 weeks ago    142MB\n<span class="ok">myapp        v2        a3f9d2c1b8e4   3 hours ago    218MB</span>`, reading:`v2 is already sitting on disk — before pulling or rebuilding anything, this one command confirms exactly what's already available locally.` },
      { cmd:`docker images`, output:`REPOSITORY   TAG       IMAGE ID       CREATED        SIZE\n<span class="dim">(nothing printed — no images at all)</span>`, reading:`A completely empty list means this is a fresh machine (or a freshly pruned one) — the very next command run will need to pull or build from scratch.` },
      { cmd:`docker images myapp`, output:`REPOSITORY   TAG       IMAGE ID       CREATED        SIZE\nmyapp        v1        7c4c4f0e1a2b   2 days ago     215MB\nmyapp        v2        a3f9d2c1b8e4   3 hours ago    218MB`, reading:`Filtering to just one repository name shows every tagged VERSION of it side by side — useful for spotting old versions worth cleaning up.` }
    ], does:`Lists every image currently stored locally, with size and age.`, where:`Checking what's already downloaded before deciding whether to pull or rebuild.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`images`, desc:`list every image stored locally`}], whyUseful:`<div class="found-p">Before deciding whether to pull a fresh copy or rebuild from scratch, check what's already sitting on disk.</div><div class="found-pre">$ docker images
myapp   v2   a3f9d2c1b8e4   3 hours ago   218MB</div><div class="found-p">v2 is already here — no need to pull or rebuild it again.</div>` },
    build: { syntax:`docker build -t &lt;name&gt;:&lt;tag&gt; .`, runs:[
      { cmd:`docker build -t myapp:v2 .`, output:`Step 1/6 : FROM node:20-alpine\n...\nStep 6/6 : CMD ["node", "server.js"]\n<span class="ok">Successfully built a3f9d2c1b8e4</span>\n<span class="ok">Successfully tagged myapp:v2</span>`, reading:`Every Dockerfile instruction runs as its own numbered step — six instructions here means six layers, built and reported one at a time.` },
      { cmd:`docker build -t myapp:v3 .`, output:`Step 4/6 : RUN npm install\n<span class="err">npm ERR! code ENOENT\nnpm ERR! missing: package.json</span>\n<span class="err">The command '/bin/sh -c npm install' returned a non-zero code: 1</span>`, reading:`The build stops at whichever step actually fails — step 4 here, meaning package.json wasn't copied into the image before this RUN instruction executed.` },
      { cmd:`docker build -t myapp:v2 .`, output:`Step 3/6 : COPY package*.json ./\n<span class="ok">---> Using cache</span>\nStep 4/6 : RUN npm install\n<span class="ok">---> Using cache</span>`, reading:`"Using cache" means Docker skipped re-running these steps because nothing changed since the last build — this is exactly why builds get dramatically faster after the first one.` }
    ], does:`Builds a new image from a Dockerfile in the current directory, tagging it with the given name.`, where:`Every CI/CD pipeline's build step is essentially this one command.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`build`, desc:`build a new image from a Dockerfile`},{term:`-t &lt;name&gt;:&lt;tag&gt;`, desc:`tag the resulting image`},{term:`.`, desc:`build context — usually the current directory`}], whyUseful:`<div class="found-p">This is the actual build step of every real CI/CD pipeline — turning source code into a deployable image.</div><div class="found-pre">$ docker build -t myapp:v2 .
Successfully tagged myapp:v2</div><div class="found-p">From here, that image can be run locally, pushed to a registry, or deployed straight to Kubernetes.</div>` },
    tag: { syntax:`docker tag &lt;source&gt; &lt;target&gt;`, runs:[
      { cmd:`docker tag myapp:v2 myrepo/myapp:v2`, output:`<span class="dim">(no output — a new tag now points at the same image)</span>`, reading:`Tagging doesn't copy or duplicate anything — it's a second name pointing at the exact same image ID, which is why the command prints nothing at all on success.` },
      { cmd:`docker tag myapp:v2 myrepo/myapp:latest
docker images | grep myapp`, output:`myrepo/myapp   v2       a3f9d2c1b8e4   3 hours ago   218MB\nmyrepo/myapp   <span class="ok">latest</span>  a3f9d2c1b8e4   3 hours ago   218MB`, reading:`Same IMAGE ID (a3f9d2c1b8e4) under two different tags — "v2" and "latest" aren't two images, just two labels for one.` },
      { cmd:`docker tag doesnotexist:v1 myrepo/app:v1`, output:`<span class="err">Error: No such image: doesnotexist:v1</span>`, reading:`Tagging fails immediately if the source image doesn't exist locally at all — a quick way to confirm a typo in an image name before it causes a confusing push failure later.` }
    ], does:`Creates an additional tag pointing at an existing image, without duplicating it.`, where:`Preparing an image to push — registries require the tag to include the destination repo name.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`tag`, desc:`create an additional tag pointing at an existing image`},{term:`&lt;source&gt;`, desc:`the image that already exists`},{term:`&lt;target&gt;`, desc:`the new tag, pointing at the same image`}], whyUseful:`<div class="found-p">You're about to push an image, but registries require the tag to include the destination repo name.</div><div class="found-pre">$ docker tag myapp:v2 myrepo/myapp:v2
(no output — a new tag now points at the same image)</div><div class="found-p">No rebuild needed — just a second name pointing at data that already exists.</div>` },
    rmi: { syntax:`docker rmi &lt;image&gt;`, runs:[
      { cmd:`docker rmi myapp:v1`, output:`Untagged: myapp:v1\n<span class="ok">Deleted: sha256:7c4c4f0e1a2b...</span>`, reading:`Both lines matter — "Untagged" removes the name, "Deleted" actually frees the disk space, since this was the last tag pointing at that image.` },
      { cmd:`docker rmi myapp:v1`, output:`Untagged: myapp:v1\n<span class="dim">(no "Deleted" line — another tag still points at this same image)</span>`, reading:`Only the tag is gone here, not the actual image data — another name (like myrepo/myapp:v1) still references the same underlying layers, so nothing was actually freed.` },
      { cmd:`docker rmi myapp:v1`, output:`<span class="err">Error response from daemon: conflict: unable to remove repository reference "myapp:v1" (must force) - container abc123 is using its referenced image</span>`, reading:`Docker refuses to delete an image that a container (even a stopped one) still depends on — stop and remove the container first, or use -f to force it.` }
    ], does:`Removes an image from local storage.`, where:`Cleaning up old versions after confirming a new one works in production.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`rmi`, desc:`remove an image from local storage`},{term:`&lt;image&gt;`, desc:`target`}], whyUseful:`<div class="found-p">A new version is confirmed working in production, and the old one is just taking up disk space now.</div><div class="found-pre">$ docker rmi myapp:v1
Deleted: sha256:7c4c4f0e1a2b...</div><div class="found-p">Clean housekeeping — without this, old versions quietly pile up forever.</div>` },
    run: { syntax:`docker run -d --name &lt;name&gt; -p &lt;host&gt;:&lt;container&gt; &lt;image&gt;`, runs:[
      { cmd:`docker run -d --name web -p 8080:80 nginx:1.25`, output:`<span class="ok">a3f9d2c1b8e47f6e2d1c9a0b5e3f7d8c</span>`, reading:`The long hash printed is the new container's ID — -d means it's already running in the background, freeing up this terminal immediately.` },
      { cmd:`docker run -d --name web -p 8080:80 nginx:1.25`, output:`<span class="err">docker: Error response from daemon: Conflict. The container name "/web" is already in use.</span>`, reading:`Container names must be unique — this exact error is why "docker rm" on the old container is a required step before reusing the same --name.` },
      { cmd:`docker run -d --name web -p 8080:80 nginx:1.25`, output:`<span class="err">docker: Error response from daemon: driver failed programming external connectivity: Bind for 0.0.0.0:8080 failed: port is already allocated</span>`, reading:`A different, unrelated failure — this time the HOST port 8080 is already taken by something else, nothing to do with the container's own name.` }
    ], does:`Starts a new container in the background, naming it and mapping host port 8080 to the container's port 80.`, where:`The core command that actually launches an application from an image.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`run`, desc:`create and start a new container`},{term:`-d`, desc:`detached — run in the background`},{term:`--name &lt;name&gt;`, desc:`give the container a name`},{term:`-p &lt;host&gt;:&lt;container&gt;`, desc:`map a host port to the container's port`},{term:`&lt;image&gt;`, desc:`which image to run`}], whyUseful:`<div class="found-p">This is THE command — everything else in this tab exists to support what happens after this one runs.</div><div class="found-pre">$ docker run -d --name web -p 8080:80 nginx:1.25
a3f9d2c1b8e47f6e2d1c9a0b5e3f7d8c</div><div class="found-p">An image just became a real, running, network-reachable application.</div>` },
    ps: { syntax:`docker ps`, runs:[
      { cmd:`docker ps`, output:`CONTAINER ID   IMAGE     STATUS         PORTS                  NAMES\na3f9d2c1b8e4   nginx     <span class="ok">Up 2 minutes</span>   0.0.0.0:8080->80/tcp   web`, reading:`"Up 2 minutes" confirms the container is genuinely running right now, and the PORTS column confirms exactly how to reach it.` },
      { cmd:`docker ps`, output:`CONTAINER ID   IMAGE     STATUS                     PORTS     NAMES\n<span class="dim">(nothing printed — no running containers at all)</span>`, reading:`An empty list from plain "docker ps" is the single fastest way to confirm the app isn't running at all — before debugging anything inside it.` },
      { cmd:`docker ps -a`, output:`CONTAINER ID   IMAGE     STATUS                       NAMES\na3f9d2c1b8e4   nginx     Up 2 minutes                 web\nb821f4a9c3d2   myapp     <span class="err">Exited (1) 5 minutes ago</span>   worker`, reading:`-a shows STOPPED containers too, not just running ones — "Exited (1)" means that container crashed with a non-zero exit code, a real clue worth investigating.` }
    ], does:`Lists all currently running containers.`, where:`The very first check when something "isn't working" — is the container even running?` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`ps`, desc:`list currently running containers`}], whyUseful:`<div class="found-p">Something "isn't working," and the very first question is: is the container even running at all?</div><div class="found-pre">$ docker ps
a3f9d2c1b8e4   nginx   Up 2 minutes   0.0.0.0:8080-&gt;80/tcp   web</div><div class="found-p">Confirmed running — so the bug is somewhere past this point, not in the container starting up.</div>` },
    stop: { syntax:`docker stop &lt;container&gt;`, runs:[
      { cmd:`docker stop web`, output:`<span class="ok">web</span>`, reading:`Sends SIGTERM first and waits (10 seconds by default) for the app to shut down cleanly before force-killing it — a graceful stop, not an instant kill.` },
      { cmd:`docker stop web`, output:`<span class="err">Error response from daemon: No such container: web</span>`, reading:`There's no container named "web" at all right now — check "docker ps -a" for the actual current name before assuming stop itself is broken.` },
      { cmd:`docker stop -t 30 web`, output:`<span class="ok">web</span>`, reading:`-t extends the grace period to 30 seconds instead of the 10-second default — useful for an app that needs longer to finish in-flight requests before shutting down.` }
    ], does:`Sends a graceful shutdown signal (SIGTERM) to a running container, waiting before force-killing it.`, where:`Stopping a container cleanly, giving the app a chance to finish in-flight work.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`stop`, desc:`send a graceful shutdown signal`},{term:`&lt;container&gt;`, desc:`target`}], whyUseful:`<div class="found-p">You're about to make a planned change and want the container to shut down cleanly, not get yanked mid-request.</div><div class="found-pre">$ docker stop web
web</div><div class="found-p">In-flight requests get a chance to finish before the container actually goes down.</div>` },
    rm: { syntax:`docker rm &lt;container&gt;`, runs:[
      { cmd:`docker rm web`, output:`<span class="ok">web</span>`, reading:`The container is fully removed — its filesystem and metadata are gone, though the IMAGE it was created from is untouched.` },
      { cmd:`docker rm web`, output:`<span class="err">Error response from daemon: cannot remove container "web": container is running: stop the container before removing or force remove</span>`, reading:`docker rm refuses to remove a RUNNING container by default — stop it first, or add -f, which is exactly the safeguard that prevents accidentally yanking a live app.` },
      { cmd:`docker stop web
docker rm web`, output:`web\n<span class="ok">web</span>`, reading:`Stop then rm, in that order — this two-step sequence (or docker rm -f as a shortcut) is the standard way to fully clear out a container before starting a fresh one with the same name.` }
    ], does:`Removes a stopped container entirely.`, where:`Cleaning up stopped containers before running a fresh one with the same name.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`rm`, desc:`remove a stopped container`},{term:`&lt;container&gt;`, desc:`target`}], whyUseful:`<div class="found-p">You want to run a fresh container with the same name, but Docker won't let a name be reused while the old stopped container still exists.</div><div class="found-pre">$ docker rm web
web</div><div class="found-p">Now "web" is free again for a new container to claim.</div>` },
    exec: { syntax:`docker exec -it &lt;container&gt; &lt;shell&gt;`, runs:[
      { cmd:`docker exec -it web bash`, output:`<span class="ok">root@a3f9d2c1b8e4:/#</span>`, reading:`The prompt changes to show you're now INSIDE the container's filesystem — same idea as SSH, but one layer down, into a container instead of a whole server.` },
      { cmd:`docker exec -it web bash`, output:`<span class="err">OCI runtime exec failed: exec failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown</span>`, reading:`Not every image includes bash — many minimal images (like alpine-based ones) only have "sh". This exact error means try "docker exec -it web sh" instead.` },
      { cmd:`docker exec web cat /etc/os-release`, output:`PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"`, reading:`Without -it, exec runs ONE command and prints its output, no interactive shell needed — useful for scripting a quick check instead of opening a full session.` }
    ], does:`Opens an interactive shell inside an already-running container.`, where:`Debugging a live container from the inside — checking files, env vars, or running one-off commands.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`exec`, desc:`run a command inside an already-running container`},{term:`-it`, desc:`interactive terminal session`},{term:`&lt;container&gt;`, desc:`target`},{term:`&lt;shell&gt;`, desc:`which shell to open, e.g. bash`}], whyUseful:`<div class="found-p">Debugging a live container from the inside — same idea as SSH, but one layer down, for a container instead of a whole server.</div><div class="found-pre">$ docker exec -it web bash
root@a3f9d2c1b8e4:/#</div><div class="found-p">Now you can poke around its filesystem, check env vars, or run one-off commands directly.</div>` },
    logs: { syntax:`docker logs &lt;container&gt;`, runs:[
      { cmd:`docker logs web`, output:`2026/08/10 10:02:11 [notice] nginx started\n<span class="ok">2026/08/10 10:02:14 GET / 200</span>`, reading:`Everything a container ever printed to stdout/stderr since it started — the first place a real crash error shows up.` },
      { cmd:`docker logs web`, output:`2026/08/10 10:02:11 [notice] nginx started\n<span class="err">2026/08/10 10:04:22 [error] connect() failed (111: Connection refused) while connecting to upstream</span>`, reading:`This is exactly the kind of error only visible in logs — the container itself is running fine, but it can't reach something IT depends on.` },
      { cmd:`docker logs --tail 20 web`, output:`<span class="dim">(only the LAST 20 lines printed, not the entire history)</span>`, reading:`--tail limits output to the most recent lines — essential on a container that's been running for days and has thousands of log lines already.` }
    ], does:`Shows a container's stdout/stderr output since it started.`, where:`The first place to look when a container is crashing or behaving unexpectedly.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`logs`, desc:`show a container's captured stdout/stderr`},{term:`&lt;container&gt;`, desc:`target`}], whyUseful:`<div class="found-p">A container is crash-looping, and its own output is the first place the real error will show up.</div><div class="found-pre">$ docker logs web
2026/08/10 10:02:11 [notice] nginx started</div><div class="found-p">The container's own explanation of what happened, straight from the source.</div>` },
    logsF: { syntax:`docker logs -f &lt;container&gt;`, runs:[
      { cmd:`docker logs -f web`, output:`2026/08/10 10:03:01 GET /health 200\n<span class="dim">(streaming live — Ctrl+C to stop)</span>`, reading:`-f keeps the terminal open and prints new lines as they happen — watching requests arrive in real time instead of a one-time dump.` },
      { cmd:`docker logs -f web`, output:`2026/08/10 10:05:12 GET /checkout 200\n<span class="err">2026/08/10 10:05:14 Uncaught TypeError: cannot read property 'id' of undefined</span>`, reading:`Reproducing a bug WHILE following logs live is how you catch the exact error line the instant it happens, tied to the exact request that triggered it.` },
      { cmd:`docker logs -f --since 5m web`, output:`<span class="dim">(only shows lines from the last 5 minutes onward, then keeps streaming new ones)</span>`, reading:`--since skips straight past hours of old history — useful when you only care about what's happening right now, not a full replay from container start.` }
    ], does:`Streams a container's logs live instead of just showing what's already happened.`, where:`Watching requests come in in real time while reproducing an issue.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`logs -f`, desc:`follow logs live instead of a one-time dump`},{term:`&lt;container&gt;`, desc:`target`}], whyUseful:`<div class="found-p">A bug only shows up under live traffic — you want to watch requests arrive in real time while reproducing it.</div><div class="found-pre">$ docker logs -f web
(streaming live — Ctrl+C to stop)</div><div class="found-p">Same idea as <span class="found-code">tail -f</span>, just scoped to one container's output.</div>` },
    inspectContainer: { syntax:`docker inspect &lt;container&gt;`, runs:[
      { cmd:`docker inspect web`, output:`[\n  {\n    "Id": "a3f9d2c1b8e4...",\n    <span class="ok">"State": { "Status": "running", "Health": { "Status": "healthy" } }</span>,\n    "NetworkSettings": { "IPAddress": "172.17.0.2" }\n  }\n]`, reading:`The full low-level JSON — this is where the exact internal IP, mount points, and health status actually live, none of which "docker ps" shows.` },
      { cmd:`docker inspect web --format '{{.State.Health.Status}}'`, output:`<span class="err">unhealthy</span>`, reading:`--format pulls out just ONE field using Go template syntax — no need to eyeball the whole JSON dump when a script only needs one value.` },
      { cmd:`docker inspect deleted-container`, output:`<span class="err">Error: No such object: deleted-container</span>`, reading:`inspect works on stopped AND running containers, but not ones that have actually been removed with "docker rm" — this confirms it's genuinely gone.` }
    ], does:`Dumps the full low-level JSON configuration and current state of a container.`, where:`Digging for exact details a normal command doesn't show — IP address, mounted volumes, exact env vars.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`inspect`, desc:`dump the full low-level JSON config and state`},{term:`&lt;container&gt;`, desc:`target`}], whyUseful:`<div class="found-p">None of the normal commands show a container's exact internal IP or mounted volumes — this is where that detail actually lives.</div><div class="found-pre">$ docker inspect web
"NetworkSettings": { "IPAddress": "172.17.0.2" }</div><div class="found-p">Digging for the one specific fact a summary view just doesn't show.</div>` },
    stats: { syntax:`docker stats`, runs:[
      { cmd:`docker stats --no-stream`, output:`CONTAINER   CPU %   MEM USAGE / LIMIT     MEM %\nweb         <span class="ok">2.14%</span>   84.2MiB / 512MiB      16.4%`, reading:`Low CPU and memory, well under the 512MiB limit — a healthy, comfortable container with plenty of headroom.` },
      { cmd:`docker stats --no-stream`, output:`CONTAINER   CPU %    MEM USAGE / LIMIT      MEM %\nweb         <span class="err">98.7%</span>    <span class="err">498MiB / 512MiB</span>       97.3%`, reading:`Both CPU and memory pegged near their limits — this container is one small spike away from being OOM-killed or throttled entirely.` },
      { cmd:`docker stats --no-stream --format "table {{.Name}}\t{{.CPUPerc}}"`, output:`NAME   CPU %\nweb    2.14%\nworker 45.2%\ndb     8.9%`, reading:`--format with a table template shows just the columns you actually want, across every running container at once, instead of scrolling a wide default table.` }
    ], does:`Shows live (or one-shot with --no-stream) CPU and memory usage per container.`, where:`Confirming a container isn't quietly eating all the host's resources.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`stats`, desc:`live CPU/memory usage per container`},{term:`--no-stream`, desc:`(optional) one snapshot instead of continuous updates`}], whyUseful:`<div class="found-p">Confirming one container isn't quietly starving every other container on the same host of resources.</div><div class="found-pre">$ docker stats --no-stream
web   2.14%   84.2MiB / 512MiB   16.4%</div><div class="found-p">Well within its limit — this container isn't the problem, if something else on the host is slow.</div>` },
    top: { syntax:`docker top &lt;container&gt;`, runs:[
      { cmd:`docker top web`, output:`UID    PID    PPID   CMD\nroot   4821   4801   <span class="ok">nginx: master process</span>`, reading:`This is the container's process, but seen from the HOST's own process table — confirms it's genuinely running, not stuck or zombied.` },
      { cmd:`docker top web`, output:`UID    PID    PPID   CMD\n<span class="err">(nothing printed — container is not running)</span>`, reading:`No processes listed at all because the container itself has stopped — docker top only works on currently RUNNING containers.` },
      { cmd:`docker top web`, output:`UID    PID    PPID   CMD\nroot   4821   4801   nginx: master process\n<span class="warn">root   9932   4821   [nginx] &lt;defunct&gt;</span>`, reading:`A defunct (zombie) child process inside the container — same concept as on a normal Linux host, just visible here through Docker's own process view.` }
    ], does:`Lists the actual OS processes running inside a container, from the host's perspective.`, where:`Checking whether a container's process is stuck, zombied, or running as the wrong user.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`top`, desc:`show the actual OS processes running inside a container`},{term:`&lt;container&gt;`, desc:`target`}], whyUseful:`<div class="found-p">A container's health check keeps failing, and you need to see from the host's view whether its process is actually stuck.</div><div class="found-pre">$ docker top web
root   4821   4801   nginx: master process</div><div class="found-p">The process is alive and looks normal — the health check failure is likely elsewhere, like the app's own logic.</div>` },
    networkLs: { syntax:`docker network ls`, runs:[
      { cmd:`docker network ls`, output:`NETWORK ID     NAME      DRIVER    SCOPE\nc1a2b3d4e5f6   bridge    bridge    local\n<span class="ok">f7e8d9c0b1a2   app-net   bridge    local</span>`, reading:`"app-net" exists and uses the bridge driver — confirming the right network is actually there before trying to attach a container to it.` },
      { cmd:`docker network ls`, output:`NETWORK ID     NAME      DRIVER    SCOPE\nc1a2b3d4e5f6   bridge    bridge    local\nd2e3f4a5b6c7   host      host      local\ne3f4a5b6c7d8   none      null      local`, reading:`Only the three default networks Docker creates automatically — no custom network like "app-net" has been created on this host yet.` },
      { cmd:`docker network ls --filter driver=bridge`, output:`NETWORK ID     NAME      DRIVER    SCOPE\nc1a2b3d4e5f6   bridge    bridge    local\nf7e8d9c0b1a2   app-net   bridge    local`, reading:`--filter narrows the list to just one driver type — useful on a host with many networks when you only care about the bridge-type ones.` }
    ], does:`Lists every Docker network currently defined on this host.`, where:`Confirming which network a container should join before connecting it to others.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`network ls`, desc:`list every Docker network on this host`}], whyUseful:`<div class="found-p">Before connecting a new container to a network, confirm the right one actually exists first.</div><div class="found-pre">$ docker network ls
f7e8d9c0b1a2   app-net   bridge   local</div><div class="found-p">"app-net" is real and ready to attach containers to.</div>` },
    networkCreate: { syntax:`docker network create &lt;name&gt;`, runs:[
      { cmd:`docker network create app-net`, output:`<span class="ok">f7e8d9c0b1a2c3d4e5f6a7b8c9d0e1f2</span>`, reading:`The long ID printed confirms a brand-new isolated network was created — containers attached to it can now resolve each other by name.` },
      { cmd:`docker network create app-net`, output:`<span class="err">Error response from daemon: network with name app-net already exists</span>`, reading:`Network names must be unique on a host — this exact error is why a setup script should check "docker network ls" first, or just ignore this specific error.` },
      { cmd:`docker network create --subnet 172.20.0.0/16 app-net`, output:`<span class="ok">a1b2c3d4e5f6...</span>`, reading:`--subnet lets you control exactly which IP range the network hands out, instead of accepting whatever Docker picks automatically — useful to avoid overlapping with another network.` }
    ], does:`Creates a new isolated network that containers can be attached to.`, where:`Letting related containers (app + database) talk to each other by name, isolated from everything else.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`network create`, desc:`make a new isolated network`},{term:`&lt;name&gt;`, desc:`its name`}], whyUseful:`<div class="found-p">An app container and a database container need to resolve each other by name, isolated from everything else on the host.</div><div class="found-pre">$ docker network create app-net
f7e8d9c0b1a2c3d4e5f6a7b8c9d0e1f2</div><div class="found-p">Any container joining this network can now reach the others on it, by container name.</div>` },
    networkInspect: { syntax:`docker network inspect &lt;name&gt;`, runs:[
      { cmd:`docker network inspect app-net`, output:`"Containers": {\n  <span class="ok">"a3f9d2c1b8e4": { "Name": "web", "IPv4Address": "172.18.0.2/16" }</span>\n}`, reading:`"web" is attached with its own IP on this network — proof it's actually joined, not just started separately.` },
      { cmd:`docker network inspect app-net`, output:`"Containers": {}`, reading:`An empty Containers object means the network exists, but literally nothing is attached to it yet — a real, if easy-to-miss, cause of "container A can't reach container B."` },
      { cmd:`docker network inspect app-net --format '{{range .Containers}}{{.Name}} {{end}}'`, output:`<span class="ok">web db worker</span>`, reading:`--format with a range template prints just the container NAMES on this network, one line, instead of parsing the full nested JSON by hand.` }
    ], does:`Shows exactly which containers are attached to a network and their IPs on it.`, where:`Debugging "why can't container A reach container B" — confirming they're actually on the same network.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`network inspect`, desc:`show full detail of one network`},{term:`&lt;name&gt;`, desc:`target`}], whyUseful:`<div class="found-p">Container A can't reach container B, and you suspect they're not actually on the same network at all.</div><div class="found-pre">$ docker network inspect app-net
"a3f9d2c1b8e4": { "Name": "web", "IPv4Address": "172.18.0.2/16" }</div><div class="found-p">Only "web" shows up here — that confirms the other container was never attached, which is the actual bug.</div>` },
    port: { syntax:`docker port &lt;container&gt;`, runs:[
      { cmd:`docker port web`, output:`<span class="ok">80/tcp -> 0.0.0.0:8080</span>`, reading:`Container port 80 maps to host port 8080, reachable from anywhere (0.0.0.0) — confirms exactly which URL actually reaches this container.` },
      { cmd:`docker port web`, output:`<span class="dim">(nothing printed — no ports are published for this container)</span>`, reading:`Empty output means this container was started with no -p flags at all — it's reachable only from other containers on the same Docker network, never from the host or outside.` },
      { cmd:`docker port web 80`, output:`<span class="ok">0.0.0.0:8080</span>`, reading:`Filtering to one specific container port shows just that one mapping — useful in a script that only needs the host port for a single known service port.` }
    ], does:`Shows the actual host-port mappings for a running container.`, where:`Double-checking which host port actually reaches a container when the run command isn't in front of you.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`port`, desc:`show the active host-port mappings`},{term:`&lt;container&gt;`, desc:`target`}], whyUseful:`<div class="found-p">You forgot exactly which host port a container was started with, and don't want to re-read the whole original run command.</div><div class="found-pre">$ docker port web
80/tcp -&gt; 0.0.0.0:8080</div><div class="found-p">Confirmed — reach this container at host port 8080.</div>` },
    volumeCreate: { syntax:`docker volume create &lt;name&gt;`, runs:[
      { cmd:`docker volume create pgdata`, output:`<span class="ok">pgdata</span>`, reading:`Just the name echoed back on success — this volume now exists independently of any container, ready to be mounted into one.` },
      { cmd:`docker volume create pgdata`, output:`<span class="warn">pgdata</span>\n<span class="dim">(already existed — command succeeds again, nothing is overwritten or reset)</span>`, reading:`Creating a volume that already exists is completely safe — it just confirms the same volume, with all its existing data fully intact.` },
      { cmd:`docker volume create --driver local -o type=nfs pgdata-nfs`, output:`<span class="ok">pgdata-nfs</span>`, reading:`-o passes driver-specific options — here, backing the volume with NFS storage instead of the default local disk, for data shared across multiple hosts.` }
    ], does:`Creates a named, Docker-managed volume for persistent storage.`, where:`Storage that needs to survive a container being removed and recreated — like a database's data directory.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`volume create`, desc:`make a new Docker-managed volume`},{term:`&lt;name&gt;`, desc:`its name`}], whyUseful:`<div class="found-p">A database's data needs to survive the container itself being removed and recreated.</div><div class="found-pre">$ docker volume create pgdata
pgdata</div><div class="found-p">Now that data lives outside the container's own disposable filesystem.</div>` },
    volumeLs: { syntax:`docker volume ls`, runs:[
      { cmd:`docker volume ls`, output:`DRIVER    VOLUME NAME\nlocal     <span class="ok">pgdata</span>\nlocal     redis-data`, reading:`Confirms both volumes genuinely exist before mounting either one into a container — catches a typo'd name before it silently creates a NEW empty volume instead.` },
      { cmd:`docker volume ls`, output:`DRIVER    VOLUME NAME\n<span class="dim">(nothing printed — no volumes exist on this host yet)</span>`, reading:`A completely empty list on a fresh host means any volume referenced in a run command will be auto-created empty — worth knowing before expecting existing data to already be there.` },
      { cmd:`docker volume ls -f dangling=true`, output:`DRIVER    VOLUME NAME\nlocal     <span class="warn">old-cache-vol</span>`, reading:`-f dangling=true filters to only volumes NOT attached to any container right now — exactly the list "docker volume prune" would remove.` }
    ], does:`Lists every volume Docker currently manages on this host.`, where:`Confirming a volume actually exists (and isn't just a typo) before mounting it into a container.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`volume ls`, desc:`list every volume Docker manages`}], whyUseful:`<div class="found-p">Before mounting a volume into a container, confirm it genuinely exists — and the name isn't a typo.</div><div class="found-pre">$ docker volume ls
local   pgdata</div><div class="found-p">"pgdata" is real — safe to mount.</div>` },
    bindMount: { syntax:`docker run -v &lt;host-path&gt;:&lt;container-path&gt; &lt;image&gt;`, runs:[
      { cmd:`docker run -v $(pwd):/app -w /app node:20 npm start`, output:`<span class="dim">(container starts with your local folder mounted live at /app)</span>`, reading:`Any file edit on your host machine appears inside the container instantly — no rebuild, no restart, since it's the exact same files, not a copy.` },
      { cmd:`echo "console.log('hi')" >> server.js
docker exec web cat /app/server.js`, output:`<span class="ok">...\nconsole.log('hi')</span>`, reading:`The edit made on the HOST shows up instantly when read from INSIDE the container — proof the bind mount is a live, shared view, not a one-time copy.` },
      { cmd:`docker run -v $(pwd):/app node:20 npm start`, output:`<span class="err">Error: Cannot find module '/app/server.js'\n(host folder was empty when mounted)</span>`, reading:`A bind mount OVERLAYS whatever was baked into the image at that path — if the host folder is empty, it hides the image's own files there instead of merging with them.` }
    ], does:`Mounts a folder from your host machine directly into the container, live.`, where:`Local development — code changes on your machine show up inside the container instantly, no rebuild needed.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`run -v &lt;host-path&gt;:&lt;container-path&gt;`, desc:`mount a host folder live into the container`},{term:`&lt;image&gt;`, desc:`which image to run`}], whyUseful:`<div class="found-p">Local development — you want code edits on your machine to show up inside the container instantly, no rebuild loop.</div><div class="found-pre">$ docker run -v $(pwd):/app -w /app node:20 npm start
(container starts with your local folder mounted live at /app)</div><div class="found-p">Save a file locally, and the running container sees the change immediately.</div>` },
    cp: { syntax:`docker cp &lt;container&gt;:&lt;path&gt; &lt;local-path&gt;`, runs:[
      { cmd:`docker cp web:/var/log/nginx/error.log ./error.log`, output:`<span class="ok">(file copied to ./error.log)</span>`, reading:`Copies FROM the container TO the host here — the direction is container:path first, then the local destination.` },
      { cmd:`docker cp ./nginx.conf web:/etc/nginx/nginx.conf`, output:`<span class="ok">(file copied into the running container)</span>`, reading:`Reversing the argument order copies the other direction — local file first, then container:path — pushing a config INTO an already-running container.` },
      { cmd:`docker cp web:/var/log/nginx/error.log ./error.log`, output:`<span class="err">Error: No such container:path: web:/var/log/nginx/error.log</span>`, reading:`This means the container exists, but that exact file path doesn't — a typo'd path, or the log genuinely hasn't been created yet inside the container.` }
    ], does:`Copies a file or folder between a container and the host filesystem, in either direction.`, where:`Grabbing a log or config file out of a running container without opening a full shell.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`cp`, desc:`copy a file/folder between container and host`},{term:`&lt;container&gt;:&lt;path&gt;`, desc:`source inside the container`},{term:`&lt;local-path&gt;`, desc:`destination on the host`}], whyUseful:`<div class="found-p">You need one config or log file out of a running container, without opening a full interactive shell.</div><div class="found-pre">$ docker cp web:/var/log/nginx/error.log ./error.log
(file copied to ./error.log)</div><div class="found-p">Faster than exec-ing in and catting the file out manually.</div>` },
    systemPrune: { syntax:`docker system prune -a`, runs:[
      { cmd:`docker system prune -a`, output:`WARNING! This will remove:\n  - all stopped containers\n  - all networks not used by at least one container\n  - all images without at least one container associated to them\nAre you sure you want to continue? [y/N] y\n<span class="ok">Total reclaimed space: 4.2GB</span>`, reading:`One sweep clears stopped containers, unused networks, AND unused images — 4.2GB back, exactly the kind of cleanup a disk-full CI runner needs.` },
      { cmd:`docker system prune -a -f`, output:`<span class="ok">Total reclaimed space: 0B</span>`, reading:`-f skips the confirmation prompt entirely (needed in a non-interactive script) — 0B reclaimed just means this host was already clean, not that the command failed.` },
      { cmd:`docker system prune -a`, output:`WARNING! This will remove:\n  - all stopped containers\n  ...\nAre you sure you want to continue? [y/N] n\n<span class="dim">(aborted — nothing was removed)</span>`, reading:`Answering "n" cancels everything with zero changes made — the warning exists specifically because -a is destructive and irreversible once confirmed.` }
    ], does:`Removes every unused container, network, and image in one sweep to reclaim disk space.`, where:`A dev machine or CI runner that's slowly filling up its disk with old layers and stopped containers.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`system prune`, desc:`remove unused containers, networks, and images in one sweep`},{term:`-a`, desc:`also remove unused images, not just dangling ones`}], whyUseful:`<div class="found-p">A dev machine or CI runner's disk is slowly filling up from months of accumulated old layers.</div><div class="found-pre">$ docker system prune -a
Total reclaimed space: 4.2GB</div><div class="found-p">Everything not currently in use by a running container gets cleared out in one shot.</div>` },
    containerPrune: { syntax:`docker container prune`, runs:[
      { cmd:`docker container prune`, output:`Deleted Containers:\na1b2c3d4e5f6\n\n<span class="ok">Total reclaimed space: 12MB</span>`, reading:`Only STOPPED containers are removed — running ones are never touched, so this is safe to run without checking "docker ps" first.` },
      { cmd:`docker container prune`, output:`<span class="dim">Total reclaimed space: 0B</span>`, reading:`0B reclaimed simply means there were no stopped containers to remove at all — not an error, just nothing to clean up right now.` },
      { cmd:`docker container prune --filter "until=24h"`, output:`Deleted Containers:\nb2c3d4e5f6a7\n\n<span class="ok">Total reclaimed space: 8MB</span>`, reading:`--filter "until=24h" only removes containers stopped more than 24 hours ago — useful to keep a recently-stopped container around briefly for debugging before it's swept up.` }
    ], does:`Removes all stopped containers, specifically, without touching images or networks.`, where:`A lighter cleanup than a full system prune when you just want stopped containers gone.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`container prune`, desc:`remove all stopped containers, specifically`}], whyUseful:`<div class="found-p">You just want stopped containers gone, without touching images or networks at all.</div><div class="found-pre">$ docker container prune
Total reclaimed space: 12MB</div><div class="found-p">A lighter, more scoped cleanup than a full system prune.</div>` },
    imagePrune: { syntax:`docker image prune -a`, runs:[
      { cmd:`docker image prune -a`, output:`Deleted Images:\nuntagged: myapp:v1\ndeleted: sha256:7c4c4f0e1a2b...\n\n<span class="ok">Total reclaimed space: 1.8GB</span>`, reading:`-a removes EVERY image not used by a container, not just "dangling" (untagged) ones — 1.8GB of old build versions freed at once.` },
      { cmd:`docker image prune`, output:`Deleted Images:\ndeleted: sha256:9f8e7d6c5b4a...\n\n<span class="ok">Total reclaimed space: 340MB</span>`, reading:`Without -a, only DANGLING images (layers left over from failed or superseded builds, with no tag at all) are removed — properly tagged old versions like myapp:v1 are left alone.` },
      { cmd:`docker image prune -a --filter "until=48h"`, output:`<span class="ok">Total reclaimed space: 620MB</span>`, reading:`Combining -a with a time filter removes unused images, but only ones older than 48 hours — protects a version you just built minutes ago from being swept up immediately.` }
    ], does:`Removes every image not currently used by any container.`, where:`Clearing out old build versions that have piled up after repeated docker build runs.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`image prune -a`, desc:`remove every image not used by any container`}], whyUseful:`<div class="found-p">Old build versions have piled up after repeated docker build runs, and none of them are actually in use anymore.</div><div class="found-pre">$ docker image prune -a
Total reclaimed space: 1.8GB</div><div class="found-p">Only images with no container attached get removed — anything actually in use is left alone.</div>` },
    volumePrune: { syntax:`docker volume prune`, runs:[
      { cmd:`docker volume prune`, output:`Deleted Volumes:\n<span class="warn">old-cache-vol</span>\n\nTotal reclaimed space: 340MB`, reading:`Only volumes with ZERO containers attached get removed — a volume still mounted anywhere, even by a stopped container, is left alone.` },
      { cmd:`docker volume prune`, output:`<span class="err">Total reclaimed space: 0B</span>\n<span class="dim">(every volume on this host is still attached to something)</span>`, reading:`0B here is a genuinely good sign — it means nothing is truly abandoned; every volume is still doing a job for some container.` },
      { cmd:`docker volume prune -f`, output:`Deleted Volumes:\n<span class="err">pgdata</span>\n\nTotal reclaimed space: 2.1GB`, reading:`-f skips the confirmation and deleted "pgdata" — this is exactly why the tool warns "this deletes data": a volume you thought was still in use, but whose container had already been removed, is now genuinely gone.` }
    ], does:`Removes every volume not currently attached to any container.`, where:`Be careful — this deletes data. Only run it once you're sure nothing still needs those volumes.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`volume prune`, desc:`remove every volume not attached to any container`}], whyUseful:`<div class="found-p">Reclaiming space from genuinely abandoned volumes — but this one deletes real data, so double-check first.</div><div class="found-pre">$ docker volume prune
Total reclaimed space: 340MB</div><div class="found-p">"Unused right now" doesn't always mean "safe to lose" — a stopped-but-still-important container's volume still qualifies for removal.</div>` },
    composeUp: { syntax:`docker compose up -d`, runs:[
      { cmd:`docker compose up -d`, output:`[+] Running 3/3\n <span class="ok">✔ Container myapp-db-1     Started</span>\n <span class="ok">✔ Container myapp-redis-1  Started</span>\n <span class="ok">✔ Container myapp-web-1    Started</span>`, reading:`All three services started together, in the correct dependency order defined by the compose file — one command instead of three separate docker run calls.` },
      { cmd:`docker compose up -d`, output:`[+] Running 3/3\n <span class="dim">✔ Container myapp-db-1     Running</span>\n <span class="dim">✔ Container myapp-redis-1  Running</span>\n <span class="dim">✔ Container myapp-web-1    Running</span>`, reading:`"Running" instead of "Started" means the stack was already up — compose is idempotent, safe to re-run without duplicating anything.` },
      { cmd:`docker compose up -d`, output:`[+] Running 2/3\n ✔ Container myapp-db-1     Started\n <span class="err">✘ Container myapp-web-1    Error</span>\n\ndependency failed to start: container myapp-web-1 is unhealthy`, reading:`One service failed its healthcheck, and compose refuses to bring up anything that depends on it — a real safeguard against starting a broken stack halfway.` }
    ], does:`Starts every service defined in docker-compose.yml, in the background, in the correct dependency order.`, where:`Spinning up a whole local dev stack (app + database + cache) with one command instead of several docker run calls.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`compose up`, desc:`start every service defined in docker-compose.yml`},{term:`-d`, desc:`detached — run in the background`}], whyUseful:`<div class="found-p">Spinning up a whole local dev stack — app, database, cache — with one command instead of three separate docker run calls.</div><div class="found-pre">$ docker compose up -d
✔ Container myapp-web-1    Started</div><div class="found-p">Every service starts together, already able to reach each other by name.</div>` },
    composeDown: { syntax:`docker compose down`, runs:[
      { cmd:`docker compose down`, output:`Container myapp-web-1    Removed\nContainer myapp-db-1     Removed\n<span class="ok">Network myapp_default    Removed</span>`, reading:`Every container AND the network compose created are removed together — a clean teardown instead of stopping and removing each piece by hand.` },
      { cmd:`docker compose down -v`, output:`Container myapp-web-1    Removed\nContainer myapp-db-1     Removed\nNetwork myapp_default    Removed\n<span class="err">Volume myapp_pgdata      Removed</span>`, reading:`-v additionally deletes the VOLUMES — meaning the database's actual data is now gone too. Without -v, volumes survive a down/up cycle; with it, they don't.` },
      { cmd:`docker compose down`, output:`<span class="dim">(nothing printed — no containers were running for this project)</span>`, reading:`Running down on a stack that's already stopped does nothing and errors on nothing — safe to run defensively even if you're not sure it's currently up.` }
    ], does:`Stops and removes every container (and the network) that compose up created.`, where:`Tearing down the whole local stack cleanly when you're done, instead of stopping containers one by one.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`compose down`, desc:`stop and remove everything compose up created`}], whyUseful:`<div class="found-p">Tearing down the whole local stack cleanly when you're done, instead of stopping containers one by one.</div><div class="found-pre">$ docker compose down
Network myapp_default    Removed</div><div class="found-p">One command undoes exactly what "compose up" set up.</div>` },
    composePs: { syntax:`docker compose ps`, runs:[
      { cmd:`docker compose ps`, output:`NAME            IMAGE      STATUS\nmyapp-web-1     myapp      <span class="ok">Up 5 minutes</span>\nmyapp-db-1      postgres   Up 5 minutes (healthy)`, reading:`Scoped to just THIS project's services — unlike plain "docker ps", which would show every container from every project on the host mixed together.` },
      { cmd:`docker compose ps`, output:`NAME            IMAGE      STATUS\nmyapp-web-1     myapp      <span class="err">Restarting (1) 3 seconds ago</span>\nmyapp-db-1      postgres   Up 5 minutes (healthy)`, reading:`"Restarting" repeatedly means this service is crash-looping — it starts, exits with an error, and the restart policy keeps trying again, never actually stabilizing.` },
      { cmd:`docker compose ps -a`, output:`NAME            IMAGE      STATUS\nmyapp-web-1     myapp      Up 5 minutes\nmyapp-worker-1  myapp      <span class="warn">Exited (0) 2 minutes ago</span>`, reading:`-a includes STOPPED services too — this worker exited cleanly (code 0) on purpose, like a one-off migration job, not a crash.` }
    ], does:`Lists the status of every service in the current compose project.`, where:`Quickly checking which services in a multi-container stack are actually up and healthy.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`compose ps`, desc:`status of services in the current compose project only`}], whyUseful:`<div class="found-p">Quickly checking which services in a multi-container stack are actually up and healthy, scoped to just this project.</div><div class="found-pre">$ docker compose ps
myapp-db-1   postgres   Up 5 minutes (healthy)</div><div class="found-p">Narrower and faster to scan than plain "docker ps" across the whole host.</div>` },
    composeLogs: { syntax:`docker compose logs -f &lt;service&gt;`, runs:[
      { cmd:`docker compose logs -f web`, output:`myapp-web-1  | Server listening on port 3000\n<span class="ok">myapp-web-1  | GET /health 200</span>`, reading:`Every printed line is prefixed with the service name (myapp-web-1) — essential once several services are all logging into the same terminal.` },
      { cmd:`docker compose logs -f`, output:`myapp-db-1    | database system is ready to accept connections\nmyapp-web-1   | GET /health 200\n<span class="err">myapp-web-1   | Error: connect ECONNREFUSED 127.0.0.1:6379</span>`, reading:`Without naming a service, ALL services stream together, interleaved — here you can see web failing to reach redis, both services' logs visible side by side.` },
      { cmd:`docker compose logs --tail 50 web`, output:`<span class="dim">(only the last 50 lines from the web service, not a live stream)</span>`, reading:`Without -f, logs prints a fixed snapshot and exits — --tail limits how much history to dump, useful for a one-time check instead of watching it live.` }
    ], does:`Streams logs for one specific service within a compose stack.`, where:`Isolating one service's output when a whole multi-container stack is running and logging at once.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`compose logs -f`, desc:`follow logs live`},{term:`&lt;service&gt;`, desc:`scope to one specific service`}], whyUseful:`<div class="found-p">A whole multi-container stack is running and logging at once — you need to isolate just one service's output.</div><div class="found-pre">$ docker compose logs -f web
myapp-web-1  | GET /health 200</div><div class="found-p">Only "web"'s lines show up, not the database or cache mixed in.</div>` },
    login: { syntax:`docker login &lt;registry&gt;`, runs:[
      { cmd:`docker login`, output:`Username: ibrahiem17\nPassword:\n<span class="ok">Login Succeeded</span>`, reading:`Authenticates the Docker CLI itself against Docker Hub (the default registry) — this is required once before "docker push" will work at all.` },
      { cmd:`docker login`, output:`Username: ibrahiem17\nPassword:\n<span class="err">Error response from daemon: Get "https://registry-1.docker.io/v2/": unauthorized: incorrect username or password</span>`, reading:`A wrong password fails at THIS step, not at push time — worth checking login succeeded before spending time debugging a later push failure.` },
      { cmd:`docker login ghcr.io`, output:`Username: ibrahiem17\nPassword:\n<span class="ok">Login Succeeded</span>`, reading:`Naming a registry explicitly (GitHub Container Registry here) authenticates against THAT one specifically — Docker can be logged into several different registries at once.` }
    ], does:`Authenticates your Docker CLI against a registry (Docker Hub by default) so you can push images.`, where:`Required once before docker push will work against a private (or your own public) repository.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`login`, desc:`authenticate against a registry`},{term:`&lt;registry&gt;`, desc:`(optional) which one — defaults to Docker Hub`}], whyUseful:`<div class="found-p">Required once before "docker push" will work against a private (or even your own public) repository.</div><div class="found-pre">$ docker login
Login Succeeded</div><div class="found-p">Your CLI session is now authenticated for any subsequent push.</div>` },
    push: { syntax:`docker push &lt;repo&gt;/&lt;image&gt;:&lt;tag&gt;`, runs:[
      { cmd:`docker push myrepo/myapp:v2`, output:`The push refers to repository [docker.io/myrepo/myapp]\n<span class="ok">v2: digest: sha256:2d194184b067... size: 1573</span>`, reading:`The digest printed is the image's unique fingerprint on the registry — this exact value is what a deploy pipeline elsewhere would pull by reference.` },
      { cmd:`docker push myrepo/myapp:v2`, output:`<span class="err">denied: requested access to the resource is denied</span>`, reading:`"Denied" here almost always means one of two things: you're not logged in (see docker login above), or you don't have write access to this specific repository.` },
      { cmd:`docker push myrepo/myapp:v2`, output:`The push refers to repository [docker.io/myrepo/myapp]\nLayer already exists\nLayer already exists\n<span class="ok">v2: digest: sha256:2d194184b067... size: 1573</span>`, reading:`"Layer already exists" means most of this image's layers were already on the registry from a previous push — only the new/changed layers actually upload.` }
    ], does:`Uploads a locally built and tagged image to a registry.`, where:`Publishing a newly built image so a CI/CD pipeline or another server can then pull and deploy it.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`push`, desc:`upload a locally built and tagged image`},{term:`&lt;repo&gt;/&lt;image&gt;:&lt;tag&gt;`, desc:`destination`}], whyUseful:`<div class="found-p">Publishing a newly built image so a CI/CD pipeline or another server can pull and deploy it.</div><div class="found-pre">$ docker push myrepo/myapp:v2
v2: digest: sha256:2d194184b067... size: 1573</div><div class="found-p">The image now exists somewhere other than just your own machine.</div>` },
    healthStatus: { syntax:`docker inspect --format='{{.State.Health.Status}}' &lt;container&gt;`, runs:[
      { cmd:`docker inspect --format='{{.State.Health.Status}}' web`, output:`<span class="ok">healthy</span>`, reading:`Reads just the HEALTHCHECK result, straight from inspect's JSON — this is genuinely different information than "is the container running," which docker ps already shows.` },
      { cmd:`docker inspect --format='{{.State.Health.Status}}' web`, output:`<span class="err">unhealthy</span>`, reading:`"Running" and "healthy" are not the same thing — a container can be fully started, yet still fail its own defined HEALTHCHECK (e.g. an endpoint returning errors).` },
      { cmd:`docker inspect --format='{{.State.Health.Status}}' web`, output:`<span class="warn">starting</span>`, reading:`"starting" is a real, temporary third state — the container just launched and hasn't completed enough healthcheck attempts yet to be judged healthy or unhealthy.` }
    ], does:`Reads just the container's current HEALTHCHECK status, straight from its inspect data.`, where:`Scripting a check that waits for a container to actually be healthy, not just "started."` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`inspect --format='{{.State.Health.Status}}'`, desc:`extract just the HEALTHCHECK status field`},{term:`&lt;container&gt;`, desc:`target`}], whyUseful:`<div class="found-p">Scripting a check that waits for a container to actually be healthy, not just "started" — those are very different things.</div><div class="found-pre">$ docker inspect --format='{{.State.Health.Status}}' web
healthy</div><div class="found-p">A deploy script can poll this in a loop before declaring a rollout successful.</div>` },
    restartPolicy: { syntax:`docker run --restart unless-stopped &lt;image&gt;`, runs:[
      { cmd:`docker run -d --restart unless-stopped --name web nginx`, output:`<span class="ok">a3f9d2c1b8e4</span>\n<span class="dim"># container now auto-restarts if it crashes or the host reboots</span>`, reading:`unless-stopped means Docker restarts it after any crash or host reboot — the ONLY way to stop it staying stopped is a manual "docker stop".` },
      { cmd:`docker inspect web --format='{{.HostConfig.RestartPolicy.Name}}'`, output:`<span class="ok">unless-stopped</span>`, reading:`Confirms the policy actually took effect after the container was started — a real way to verify instead of just trusting the run command worked as intended.` },
      { cmd:`docker run -d --restart on-failure:3 --name worker myapp`, output:`<span class="ok">b821f4a9c3d2</span>\n<span class="dim"># restarts up to 3 times only if it exits with an error — a clean exit (0) is never restarted</span>`, reading:`on-failure:3 is more conservative than unless-stopped — it only retries a LIMITED number of times on a genuine crash, and never restarts a container that exited cleanly on purpose.` }
    ], does:`Sets a restart policy so Docker automatically restarts the container if it exits unexpectedly (or the host reboots).`, where:`Production containers should basically always have a restart policy — an unhandled crash shouldn't mean permanent downtime.` , breakdown:[{term:`docker`, desc:`the CLI`},{term:`run --restart unless-stopped`, desc:`auto-restart on crash or host reboot`},{term:`&lt;image&gt;`, desc:`which image to run`}], whyUseful:`<div class="found-p">Production containers should basically always have this — an unhandled crash shouldn't mean permanent downtime until a human notices.</div><div class="found-pre">$ docker run -d --restart unless-stopped --name web nginx
a3f9d2c1b8e4</div><div class="found-p">If this container crashes at 3 AM, it's already back up before anyone's paged.</div>` },

    useraddExpireDocker: { syntax:`useradd -e &lt;YYYY-MM-DD&gt; &lt;username&gt;`, runs:[
      { cmd:`docker exec -it web bash
useradd -e 2026-12-31 auditor_temp
echo $?`, output:`<span class="ok">root@a3f9d2c1b8e4:/#</span>\n<span class="ok">0</span>`, reading:`Silence, then exit code 0 — same success signal as running it on a normal server. This account only exists inside THIS container's own filesystem, not on the host machine at all.` },
      { cmd:`useradd -e 2026-12-31 auditor_temp`, output:`<span class="err">useradd: user 'auditor_temp' already exists</span>`, reading:`Same error you'd get anywhere — this container already has that username. Nothing docker-specific here, this container's /etc/passwd behaves exactly like any Linux machine's.` },
      { cmd:`docker exec -it api bash
useradd -e 2026-12-31 auditor_temp`, output:`<span class="ok">root@f7c2e9a41d33:/#</span>\n<span class="ok">(silence — succeeded, no error)</span>`, reading:`No "already exists" error this time, even with the exact same username — each container has its own completely separate user database. Creating this user in "web" has zero effect on "api."` }
    ], does:`Creates a user account inside whichever container you've exec'd into — isolated to that one container's own filesystem, exactly like it would be on a real separate machine.`, where:`Giving someone a temporary shell account inside a specific container for debugging or an audit, without that access ever existing anywhere else — not the host, not any other container.`, breakdown:[{term:`docker exec -it web bash`, desc:`open an interactive shell INSIDE the "web" container first`},{term:`useradd -e &lt;date&gt;`, desc:`same command as on a real server — but scoped entirely to this one container`}], whyUseful:`<div class="found-p">An auditor needs to poke around inside one specific container to check something, but you don't want to hand out a permanent account, and definitely don't want it to exist on the host or any other container.</div><div class="found-pre">$ docker exec -it web bash
root@web:/# useradd -e 2026-12-31 auditor_temp</div><div class="found-p">The account is scoped to exactly that one container, expires itself, and if that container ever gets removed and recreated, the account is gone with it automatically.</div>` },
    chageListDocker: { syntax:`chage -l &lt;username&gt;`, runs:[
      { cmd:`docker exec web chage -l auditor_temp`, output:`Account expires : <span class="warn">Dec 31, 2026</span>`, reading:`docker exec without -it just runs one command inside the container and prints its output — no need to open a full shell just to check one thing.` },
      { cmd:`docker exec web chage -l www-data`, output:`Account expires : <span class="ok">never</span>`, reading:`The app's own built-in service account has no expiration, as expected — only the account deliberately created with -e has one.` },
      { cmd:`chage -l auditor_temp`, output:`<span class="err">chage: user 'auditor_temp' does not exist in /etc/passwd</span>`, reading:`Run on the HOST instead of inside the container — this proves the isolation directly. The account is completely invisible outside the container it was created in; the host's own /etc/passwd was never touched.` }
    ], does:`Shows an account's expiration settings, scoped to whichever container (or the host) you actually check it against.`, where:`Confirming a temporary container account is actually set to expire — and confirming it hasn't accidentally leaked out to the host or another container.`, breakdown:[{term:`docker exec web`, desc:`run the following command inside the "web" container specifically`},{term:`chage -l &lt;username&gt;`, desc:`same command as on a real server, scoped to that one container`}], whyUseful:`<div class="found-p">After granting temporary container access for an audit, you want quick proof it's genuinely time-boxed and hasn't somehow ended up on the host too.</div><div class="found-pre">$ docker exec web chage -l auditor_temp
Account expires : Dec 31, 2026

$ chage -l auditor_temp   ← run on the host
chage: user 'auditor_temp' does not exist</div><div class="found-p">Two commands prove both things at once: it expires, and it never existed anywhere except that one container.</div>` },
  };
  function runDockerCmd(key, btn) {
    const d = DOCKER_CMDS[key];
    if (!d) return;
    const runsArea = document.getElementById('dockerRunsArea');
    if (d.runs && d.runs.length) {
      renderCmdRuns(d.runs, runsArea);
    } else {
      // legacy shape — single cmd/output pair, not yet migrated to runs:[]
      const lines = d.cmd.split('\n');
      let extra = '';
      if (lines.length > 1) {
        extra = lines.slice(1).map(l => '<span class="ld-prompt">devops@server:~$</span> ' + l).join('\n') + '\n';
      }
      renderCmdRuns([{ cmd: lines[0], output: extra + d.output }], runsArea);
    }
    document.getElementById('dockerSyntax').innerHTML = d.syntax || (d.runs ? d.runs[0].cmd.split('\n')[0] : d.cmd.split('\n')[0]);
    document.getElementById('dockerDoes').innerHTML = d.does;
    document.getElementById('dockerWhere').innerHTML = d.where;
    const dockerBdList = document.getElementById('dockerBreakdownList');
    if (dockerBdList) {
      dockerBdList.innerHTML = (d.breakdown && d.breakdown.length)
        ? d.breakdown.map(b => `<div class="sl-breakdown-item"><span class="sl-breakdown-term">${b.term}</span><span class="sl-breakdown-desc">${b.desc}</span></div>`).join('')
        : '<span class="dim">No further breakdown needed for this one.</span>';
    }
    const dockerWhyEl = document.getElementById('dockerWhyUseful');
    if (dockerWhyEl) dockerWhyEl.innerHTML = d.whyUseful || '<span class="dim">—</span>';
    document.querySelectorAll('#tab-dockerdevops .ld-pill').forEach(p => p.classList.remove('active'));
    if (btn) btn.classList.add('active');
  }

  /* ============ DOCKER FOR DEVOPS QUIZ ============ */
  const DOCKER_QUIZ_JOKES = [
    `"It works on my machine" is what Docker was invented to make illegal.`,
    `A container's favorite exit code is 137 — right after it learns what OOMKilled means.`,
    `docker system prune -a: the closest thing to spring cleaning a DevOps engineer will ever do.`,
    `Two containers walk into a bar. Neither can find it — they're not on the same network.`,
    `There's no cloud, just someone else's containers, restarting unless-stopped.`
  ];

  const DOCKER_QUIZ_QUESTIONS = [
    { q:`What's the difference between a Docker image and a Docker container?`, options:[`An image is a static blueprint; a container is a running instance of that image`,`An image is a running instance; a container is the static blueprint it came from`,`They're just two different names for the exact same underlying concept`,`An image only exists on a registry; a container only exists locally on disk`], correct:0, why:`The image is the read-only template; the container is what you get when Docker actually runs it.` },
    { q:`What does "docker pull nginx:1.25" actually do?`, options:[`Downloads that specific image and its layers from a registry to your machine`,`Starts a new running container from the nginx image immediately`,`Builds a brand-new image tagged nginx:1.25 from a local Dockerfile`,`Uploads your own local nginx image up to a remote registry`], correct:0, why:`pull only fetches the image — it doesn't start anything running on its own.` },
    { q:`What does "docker images" list?`, options:[`Every image currently stored locally, with its size and how old it is`,`Every container currently running on this host machine right now`,`Every image available on Docker Hub across the entire registry`,`Every Dockerfile found anywhere within the current project folder`], correct:0, why:`It's a purely local listing — nothing about what's running, nothing about the remote registry.` },
    { q:`What does "docker build -t myapp:v2 ." do?`, options:[`Builds a new image from the Dockerfile in this folder, tagging it myapp:v2`,`Runs a new container from an image that's already tagged myapp:v2`,`Downloads myapp:v2 from a registry instead of building it locally`,`Pushes an already-built myapp:v2 image up to a remote registry`], correct:0, why:`The trailing "." tells Docker to use the current directory as the build context.` },
    { q:`Why would you run "docker tag myapp:v2 myrepo/myapp:v2"?`, options:[`To point an additional tag at the same image, ready to push to that repo`,`To physically duplicate the image so two separate copies now exist`,`To rename the Dockerfile itself so it matches the new repo name`,`To permanently delete the old myapp:v2 tag before pushing a new one`], correct:0, why:`Tagging just adds a pointer — no new image data is created or copied.` },
    { q:`What does "docker rmi myapp:v1" do?`, options:[`Removes that specific image from local storage`,`Removes every running container that was started from that image`,`Renames the image from myapp:v1 to a different, unspecified tag`,`Removes the image only from the remote registry, not locally`], correct:0, why:`rmi targets an image, not the containers that were started from it.` },
    { q:`What does "docker run -d --name web -p 8080:80 nginx" actually start?`, options:[`A new background container named web, mapping host port 8080 to its port 80`,`A new container that blocks your terminal until you manually stop it`,`A container that's only reachable from other containers, not the host`,`A container that automatically restarts every 8080 milliseconds by default`], correct:0, why:`-d detaches it into the background, and -p publishes the port mapping to the host.` },
    { q:`What does "docker ps" show by default?`, options:[`Only the containers that are currently running`,`Every container that has ever existed on this machine, running or not`,`Every image currently stored locally, not containers at all`,`Only containers that have already stopped or crashed`], correct:0, why:`Plain "docker ps" is running-only — stopped containers need the -a flag.` },
    { q:`What's the difference between "docker ps" and "docker ps -a"?`, options:[`-a additionally includes stopped containers, not just running ones`,`-a shows containers on remote hosts instead of the local machine`,`-a shows only containers, while plain ps also lists images`,`There's no real difference — they behave in an identical way`], correct:0, why:`-a stands for "all" — every container regardless of its current state.` },
    { q:`What does "docker stop web" do, compared to "docker kill web"?`, options:[`stop sends a graceful shutdown signal first; kill force-terminates it immediately`,`They're functionally identical commands with two different names`,`stop removes the container entirely; kill only pauses it temporarily`,`kill is gentler than stop, giving the app more time to shut down`], correct:0, why:`stop gives the app a chance to shut down cleanly before Docker force-kills it if it doesn't.` },
    { q:`What does "docker rm web" require to succeed?`, options:[`The container must already be stopped, unless you also pass -f`,`The container's image must be deleted first, before the container`,`Nothing — it works on running containers exactly the same as stopped ones`,`The container must have a restart policy already configured on it`], correct:0, why:`Docker refuses to remove a running container without an explicit force flag, as a safety net.` },
    { q:`What does "docker exec -it web bash" do?`, options:[`Opens an interactive shell inside the already-running web container`,`Starts a brand-new container from the web image and opens a shell`,`Executes a bash script located on the host machine, not inside the container`,`Permanently changes the container's default startup command to bash`], correct:0, why:`exec runs a new process inside an existing, already-running container.` },
    { q:`What does "docker logs web" show?`, options:[`The container's stdout/stderr output captured since it started`,`A list of every command that was ever run inside the container`,`The container's CPU and memory usage history over time`,`The full contents of every file inside the container's filesystem`], correct:0, why:`Docker captures whatever the container's main process prints and stores it as its logs.` },
    { q:`Why use "docker logs -f" instead of plain "docker logs"?`, options:[`It streams new log lines live instead of just showing what's already happened`,`It shows dramatically more historical log output than the plain version`,`It filters the logs down to errors only, hiding everything else`,`It's required the very first time you ever check a container's logs`], correct:0, why:`-f follows the log output, exactly like tail -f on a regular log file.` },
    { q:`What does "docker inspect web" return?`, options:[`The full low-level JSON configuration and current state of that container`,`A simplified, human-readable summary of the container's health only`,`The container's log output, formatted as JSON instead of plain text`,`A list of every image layer that container's image was built from`], correct:0, why:`inspect dumps everything Docker knows about that container — networking, mounts, state, and more.` },
    { q:`What does "docker stats" show?`, options:[`Live CPU and memory usage per container, updating continuously`,`A one-time historical report of resource usage from when it started`,`The number of requests each container has handled since it started`,`Which host the container is physically running on in a cluster`], correct:0, why:`It's a live-updating dashboard, similar in spirit to "top" but scoped to containers.` },
    { q:`What does "docker top web" show?`, options:[`The actual OS processes running inside that container, from the host's view`,`The single container using the most CPU across the whole host`,`A ranked list of the largest files stored inside that container`,`The container's uptime and nothing else about its current state`], correct:0, why:`It's literally "ps" scoped to just that one container's process namespace.` },
    { q:`Why can't two containers on the default bridge network reach each other by container name?`, options:[`The default bridge network doesn't support automatic name-based DNS resolution`,`Containers can never reach each other under any circumstance at all`,`Docker blocks all container-to-container traffic by default, always`,`Container names are only ever used for display, never for networking`], correct:0, why:`Only user-defined networks get Docker's built-in DNS for resolving containers by name.` },
    { q:`What does creating a custom network with "docker network create app-net" actually enable?`, options:[`Containers attached to it can resolve and reach each other by container name`,`It automatically encrypts all traffic between every container on the host`,`It gives every container on it a public IP reachable from the internet`,`It's required before any container is allowed to make outbound requests`], correct:0, why:`This is exactly what the default bridge network is missing — name-based resolution between containers.` },
    { q:`What does "docker network inspect app-net" let you confirm?`, options:[`Exactly which containers are attached to that network, and their IPs on it`,`The total amount of bandwidth that network has used since creation`,`Which host ports are currently forwarded through that specific network`,`Whether that network is reachable from outside the Docker host`], correct:0, why:`It's the direct way to check whether a container you expect to be attached actually is.` },
    { q:`What does "docker port web" show?`, options:[`The actual host-port mappings currently active for that container`,`Every port that container's application could theoretically listen on`,`Whether the container's exposed port is currently being attacked`,`The container's internal IP address on its default network`], correct:0, why:`It's a quick way to confirm the exact host-to-container port mapping without re-reading the run command.` },
    { q:`What's the difference between a named volume and a bind mount?`, options:[`A named volume is managed by Docker; a bind mount points at a specific host folder`,`They're two different names for exactly the same underlying feature`,`A bind mount is managed by Docker; a named volume points at a host folder`,`Named volumes only work on Linux, while bind mounts work everywhere`], correct:0, why:`Docker owns and manages a named volume's storage location; a bind mount is just a direct host path.` },
    { q:`Why is a bind mount ("-v $(pwd):/app") so common in local development?`, options:[`Code changes on your machine show up inside the container instantly, no rebuild`,`It's required before a container is allowed to expose any ports at all`,`It automatically encrypts the mounted folder's contents for security`,`It permanently copies the folder into the image the first time it runs`], correct:0, why:`The container reads live from your actual filesystem — no rebuild-and-restart loop needed for every edit.` },
    { q:`Why would a database container specifically need a named volume?`, options:[`So its data survives the container being removed and recreated`,`So the database runs measurably faster than it would without one`,`Because databases are technically incapable of running without one`,`So the database's data becomes visible to every other container automatically`], correct:0, why:`Without a volume, a database's data lives only inside the container's writable layer, and disappears with it.` },
    { q:`What does "docker cp web:/etc/nginx/nginx.conf ./nginx.conf" do?`, options:[`Copies that one file out of the running container to your local machine`,`Permanently moves the file, deleting it from inside the container`,`Opens the file for live editing directly inside the container`,`Copies every file in the container's /etc folder, not just that one`], correct:0, why:`cp is a straightforward copy — the original stays exactly where it was inside the container.` },
    { q:`What does "docker system prune -a" remove?`, options:[`All stopped containers, unused networks, and images with no container using them`,`Every image and container on the host, running or not, with no exceptions`,`Only currently-running containers that have been up for over a day`,`Only Docker's own internal cache, leaving every image and container untouched`], correct:0, why:`It's a broad but not total cleanup — anything still actually in use is left alone.` },
    { q:`What's the difference between "docker container prune" and "docker system prune -a"?`, options:[`container prune only removes stopped containers; system prune -a also removes unused images and networks`,`They remove exactly the same things, just with two different command names`,`container prune is more aggressive, removing images that system prune keeps`,`system prune -a only works when no containers exist on the host at all`], correct:0, why:`container prune is scoped narrowly; system prune -a sweeps containers, images, and networks together.` },
    { q:`Why should "docker volume prune" be run carefully?`, options:[`It permanently deletes data in any volume not currently attached to a container`,`It only ever deletes volumes that are already completely empty`,`It's actually a read-only command that never deletes anything`,`It only affects volumes created in the last 24 hours, nothing older`], correct:0, why:`"Unused" doesn't mean "safe to lose" — a stopped-but-important container's volume still qualifies.` },
    { q:`What does "docker compose up -d" do?`, options:[`Starts every service defined in docker-compose.yml, in the background, in order`,`Starts only the single service explicitly named on the command line`,`Builds every service's image but does not actually start any containers`,`Uploads the whole compose project to a remote server automatically`], correct:0, why:`Compose reads the whole file and brings up every service, respecting any "depends_on" ordering.` },
    { q:`What does "docker compose down" do?`, options:[`Stops and removes every container (and network) that compose up created`,`Only pauses every running service without removing anything`,`Permanently deletes the docker-compose.yml file from the project`,`Only stops the database service, leaving the rest of the stack running`], correct:0, why:`down is the clean, complete teardown counterpart to "compose up."` },
    { q:`What does "docker compose ps" show, compared to "docker ps"?`, options:[`The status of just the services belonging to the current compose project`,`Exactly the same output as docker ps, with no meaningful difference`,`Only services that have already failed their health checks`,`The status of every container on the host, across every project`], correct:0, why:`It's scoped to the current compose project's docker-compose.yml, not the whole host.` },
    { q:`What does "docker compose logs -f web" do?`, options:[`Streams live logs for just the web service within the compose stack`,`Streams combined logs for every service in the compose stack at once`,`Shows only errors logged by the web service, filtering out everything else`,`Permanently saves the web service's logs to a file on the host`], correct:0, why:`Naming a service scopes the streamed logs down to just that one container.` },
    { q:`Why does "docker login" need to happen before "docker push"?`, options:[`Push requires an authenticated session against the target registry`,`Login is only required the very first time Docker is ever installed`,`Push works without authentication for any image under 100MB`,`Login is optional and only improves the speed of the push itself`], correct:0, why:`Registries won't accept an upload from an identity they haven't verified first.` },
    { q:`What does "docker push myrepo/myapp:v2" require the image name to include?`, options:[`The destination repository name — plain local tags aren't enough to push`,`The exact IP address of the target registry server`,`A digital signature generated separately before the push can start`,`Nothing extra — any locally built and tagged image can be pushed as-is`], correct:0, why:`Without the repo name baked into the tag, Docker doesn't know where to actually send the image.` },
    { q:`What does "docker inspect --format='{{.State.Health.Status}}' web" return?`, options:[`Just that container's current HEALTHCHECK status, like healthy or unhealthy`,`The container's full JSON configuration, unformatted and unfiltered`,`The container's current CPU and memory usage percentages`,`A history of every healthcheck that container has ever run`], correct:0, why:`The --format flag extracts just that one field instead of dumping the whole inspect output.` },
    { q:`What does adding "--restart unless-stopped" to "docker run" do?`, options:[`Docker automatically restarts the container if it crashes or the host reboots`,`The container becomes completely immune to ever crashing at all`,`Docker checks the container's health every second instead of periodically`,`The container is prevented from ever being manually stopped again`], correct:0, why:`It keeps the container coming back on its own, without needing anyone to notice and intervene.` },
    { q:`In a Dockerfile, why does instruction order (like COPY before RUN npm install) affect build speed?`, options:[`Docker caches each layer, and reuses it on rebuild unless that layer's inputs changed`,`Instruction order has no effect at all on how long a build takes`,`Later instructions in a Dockerfile always run measurably faster than earlier ones`,`Docker always rebuilds every single layer from scratch on every single build`], correct:0, why:`Layer caching is the whole reason careful instruction ordering in a Dockerfile matters.` },
    { q:`Why is it a common mistake to "COPY . ." before "COPY package*.json ./" and "RUN npm install"?`, options:[`Any source file change invalidates the cache, forcing npm install to rerun every time`,`It causes the build to fail immediately with a syntax error every time`,`It makes the resulting image significantly larger than it needs to be`,`It's actually the correct, recommended order and causes no real problem`], correct:0, why:`Copying everything first means even a one-line code change busts the cache for the expensive install step.` },
    { q:`What's the benefit of a multi-stage Dockerfile build?`, options:[`The final image only contains what's needed to run, not the whole build toolchain`,`It builds the image measurably faster than a single-stage build always would`,`It's required before an image can be pushed to any public registry`,`It automatically runs the application's test suite during the build itself`], correct:0, why:`Build tools and intermediate artifacts get left behind in an earlier stage instead of bloating the final image.` },
    { q:`A container exits immediately after "docker run," with nothing obviously wrong printed to your terminal. What's the right next step?`, options:[`Run docker logs on it — stdout/stderr from before it exited is captured there`,`Assume the image itself is corrupted and re-pull it from scratch`,`Immediately rebuild the image with no changes and try running it again`,`Conclude the host machine itself is out of available memory`], correct:0, why:`The container's own output before it died is exactly what logs preserves for you to inspect.` },
    { q:`Scenario: your app container can't reach a database container by hostname, though both show as running. What's the likely cause?`, options:[`They're not attached to the same custom network, so name resolution fails`,`The database container is simply too slow to respond to any request`,`Container names can never be used for networking under any setup`,`One of the two containers is missing a restart policy configuration`], correct:0, why:`Both containers being "up" says nothing about whether they can actually resolve each other by name.` },
    { q:`Scenario: you rebuilt an image after fixing a bug, but "docker ps" shows the running container's image is still the old tag. What's the fix?`, options:[`Stop and remove the old container, then run a new one from the new image tag`,`Nothing is needed — the running container updates itself automatically`,`Rebuild the image a second time, since one rebuild is never enough`,`Restart the Docker daemon itself to force the change through`], correct:0, why:`A running container is frozen at the image it was started from — rebuilding the image doesn't touch it.` },
    { q:`Scenario: a CI runner's disk is nearly full after months of repeated image builds. What's the appropriate cleanup?`, options:[`docker system prune -a, to clear out unused layers, images, and containers`,`Manually deleting random files inside the Docker installation folder`,`Reinstalling Docker completely from scratch on that runner`,`Reducing the number of CPU cores available to the Docker daemon`], correct:0, why:`This is exactly the built-in tool for reclaiming space from accumulated build byproducts.` },
    { q:`Scenario: you need to grab one config file out of a running container without opening a full shell session. What do you run?`, options:[`docker cp <container>:<path> <local-path>`,`docker exec -it <container> bash, then manually retype the whole file`,`docker inspect <container>, since config files appear in that output`,`docker logs <container>, since logs include a copy of every file`], correct:0, why:`cp is built exactly for this — moving one file across the container boundary directly.` },
    { q:`Scenario: "docker ps" shows a container marked unhealthy, and you need to know why. What do you check?`, options:[`docker inspect's Health field — it logs the output of each failed check`,`docker stats, since resource usage always explains a health failure`,`docker port, since a wrong port mapping is the only possible cause`,`There's no way to see why — you can only see that it failed`], correct:0, why:`The Health object records exactly what each healthcheck probe returned, including the failure output.` },
    { q:`Scenario: you're about to deploy a production container and want it to come back up automatically if it crashes. What do you add?`, options:[`--restart unless-stopped (or always) on the docker run command`,`A HEALTHCHECK instruction alone, which restarts containers by itself`,`Nothing — Docker restarts every container automatically by default already`,`A cron job on the host that manually re-runs docker run every minute`], correct:0, why:`A HEALTHCHECK only reports status — it's the restart policy that actually acts on a crash.` },
    { q:`Scenario: you need to spin up an app, a database, and a cache together for local development, without three separate docker run commands. What's the move?`, options:[`Define all three services in docker-compose.yml and run docker compose up -d`,`Combine all three into a single Dockerfile and one docker run command`,`Manually script three separate docker run commands in a shell loop`,`Install the database and cache directly on the host instead of containerizing them`], correct:0, why:`Compose is purpose-built for coordinating exactly this kind of multi-service local stack.` },
    { q:`Scenario: your Dockerfile builds successfully, but the resulting image is unexpectedly huge. What's a likely fix?`, options:[`Use a multi-stage build so build tools don't end up in the final image`,`Nothing can reasonably be done — image size is fixed by the base OS alone`,`Remove the HEALTHCHECK instruction, since that's what inflates image size`,`Switch from docker build to docker pull, which produces smaller images`], correct:0, why:`Build-time dependencies are often the single biggest, easiest thing to trim from a final image.` },
    { q:`Scenario: after "docker volume prune," an app that used to persist data between restarts now starts empty every time. What happened?`, options:[`The volume holding that data was unused at the time and got deleted`,`This is unrelated — volume prune never actually deletes volume data`,`The application's Dockerfile was silently corrupted by the prune command`,`The container itself was deleted, which is why the data disappeared too`], correct:0, why:`If no container was actively using that volume at prune time, it was fair game to be removed.` },
    { q:`Scenario: "docker push" fails with an authentication error even though the image is built and tagged correctly. What's the fix?`, options:[`Run docker login for that registry before attempting the push again`,`Rebuild the image completely, since a bad build causes push auth errors`,`Rename the image tag, since tag names can trigger authentication failures`,`Switch from docker push to docker pull, which doesn't require authentication`], correct:0, why:`A correct build and tag say nothing about whether your CLI session is actually authenticated.` }
  ];
