  /* ============ GITHUB ACTIONS FOR DEVOPS — feature explorer ============ */
  function ghaBlock(yaml, log) {
    return `<div style="white-space:pre;margin-bottom:10px;">${yaml}</div><div style="border-top:1px dashed #263042;padding-top:8px;margin-top:2px;color:#475569;font-size:9.5px;letter-spacing:.04em;">▸ SIMULATED ACTIONS RUN LOG</div>${log}`;
  }
  const GHA_CMDS = {
    onPush: { syntax:`on: push`, cmd:`on: push`, output: ghaBlock(`on: push`, `<span class="ok">✓ Triggered — someone pushed to a branch</span>`), does:`Runs the workflow every time any commit is pushed to any branch.`, where:`The simplest, broadest trigger — good for a first workflow while you're still learning.` },
    onPushBranches: { syntax:`on:\n  push:\n    branches: [main]`, cmd:`on: push (branches: main)`, output: ghaBlock(`on:\n  push:\n    branches: [main]`, `<span class="dim">push to feature-x → ignored</span>\n<span class="ok">push to main → ✓ triggered</span>`), does:`Only triggers for pushes to the branches listed — everything else is ignored.`, where:`Deploy workflows almost always narrow to "main" only, so a random feature branch push can't accidentally trigger a deploy.` },
    onPR: { syntax:`on: pull_request`, cmd:`on: pull_request`, output: ghaBlock(`on: pull_request`, `<span class="ok">✓ Triggered — PR #42 opened against main</span>`), does:`Runs whenever a pull request is opened, or gets a new commit pushed to it.`, where:`Checking a change before it merges — this is what shows the green ✓ or red ✗ right on the PR page.` },
    onManual: { syntax:`on: workflow_dispatch`, cmd:`on: workflow_dispatch`, output: ghaBlock(`on: workflow_dispatch`, `<span class="dim">Adds a "Run workflow" button on the Actions tab</span>\n<span class="ok">✓ Triggered manually by ibrahiem17</span>`), does:`Adds a manual button in the GitHub UI to trigger this workflow on demand.`, where:`One-off tasks that shouldn't run automatically — a manual production deploy, a one-time data migration.` },
    onSchedule: { syntax:`on:\n  schedule:\n    - cron: '0 2 * * *'`, cmd:`on: schedule (cron)`, output: ghaBlock(`on:\n  schedule:\n    - cron: '0 2 * * *'`, `<span class="dim">Waiting for 2:00 AM UTC...</span>\n<span class="ok">✓ Triggered on schedule</span>`), does:`Runs on a timer, using standard cron syntax — no push or PR needed at all.`, where:`Nightly cleanup jobs, scheduled reports, or periodic health checks that don't depend on any code change.` },
    multipleJobs: { syntax:`jobs:\n  lint: {...}\n  test: {...}`, cmd:`two jobs, no needs:`, output: ghaBlock(`jobs:\n  lint:\n    runs-on: ubuntu-latest\n  test:\n    runs-on: ubuntu-latest`, `<span class="ok">✓ lint — started</span>\n<span class="ok">✓ test — started</span>\n<span class="dim">(both running at the same time, on separate runners)</span>`), does:`Every job in a workflow runs in parallel by default, each on its own fresh runner.`, where:`Independent checks (lint, unit tests, type-check) that don't depend on each other finish faster running side by side.` },
    jobNeeds: { syntax:`deploy:\n  needs: test`, cmd:`needs: test`, output: ghaBlock(`jobs:\n  test:\n    runs-on: ubuntu-latest\n  deploy:\n    needs: test\n    runs-on: ubuntu-latest`, `<span class="ok">✓ test — passed</span>\n<span class="ok">✓ deploy — started (waited for test)</span>`), does:`Forces a job to wait until another named job finishes successfully before it starts.`, where:`Making sure deploy never even attempts to run if the test job failed.` },
    ifCondition: { syntax:`if: github.ref == 'refs/heads/main'`, cmd:`if: (conditional step)`, output: ghaBlock(`- name: Deploy\n  if: github.ref == 'refs/heads/main'\n  run: ./deploy.sh`, `<span class="dim">branch = feature-x → step skipped</span>\n<span class="ok">branch = main → ✓ step ran</span>`), does:`Runs a step (or whole job) only if the condition evaluates true — otherwise it's skipped, not failed.`, where:`Only running a deploy step on main, while still running tests on every branch in the same workflow.` },
    continueOnError: { syntax:`continue-on-error: true`, cmd:`continue-on-error: true`, output: ghaBlock(`- name: Optional lint\n  run: npm run lint\n  continue-on-error: true`, `<span class="warn">⚠ Optional lint — failed, but marked continue-on-error</span>\n<span class="ok">✓ Job continues to next step</span>`), does:`Lets a step fail without failing the whole job or blocking later steps.`, where:`A linter or a nice-to-have check you want visibility into, without it blocking a merge or deploy.` },
    checkout: { syntax:`- uses: actions/checkout@v4`, cmd:`actions/checkout@v4`, output: ghaBlock(`steps:\n  - uses: actions/checkout@v4`, `<span class="ok">✓ Checking out repo at a3f9d2c...</span>\n<span class="ok">✓ Code is now available on the runner</span>`), does:`Downloads your repository's code onto the runner — without it, the runner is completely empty.`, where:`Almost every job's very first step — nothing else can reference your files until this runs.` },
    setupNode: { syntax:`- uses: actions/setup-node@v4\n  with:\n    node-version: 20`, cmd:`actions/setup-node@v4`, output: ghaBlock(`- uses: actions/setup-node@v4\n  with:\n    node-version: 20`, `<span class="ok">✓ Node 20.11.0 installed and added to PATH</span>`), does:`Installs a specific version of Node.js on the runner and adds it to PATH.`, where:`Any JavaScript/TypeScript project's build or test step needs a Node version available first.` },
    runCommand: { syntax:`- run: npm run build`, cmd:`run: (shell command)`, output: ghaBlock(`- name: Build\n  run: npm run build`, `> myapp@1.0.0 build\n<span class="ok">✓ Build completed in 12s</span>`), does:`Runs a raw shell command directly on the runner — the most basic step type there is.`, where:`Anything a pre-built action doesn't already cover — install, build, test, or any custom script.` },
    marketplaceAction: { syntax:`- uses: slackapi/slack-github-action@v1`, cmd:`marketplace action`, output: ghaBlock(`- uses: slackapi/slack-github-action@v1\n  with:\n    channel-id: deploys\n    slack-message: "Deploy finished ✅"`, `<span class="ok">✓ Message posted to #deploys</span>`), does:`Drops in a pre-built step someone else already wrote and published, instead of writing it yourself.`, where:`Slack notifications, deploy integrations, security scans — check the Marketplace before writing something from scratch.` },
    secretsUsage: { syntax:`${'$'}{{ secrets.API_KEY }}`, cmd:`secrets.API_KEY`, output: ghaBlock(`- run: curl -H "Authorization: Bearer \${{ secrets.API_KEY }}" https://api.example.com`, `<span class="ok">✓ Authorization: Bearer ***</span> <span class="dim">(masked automatically in the log)</span>`), does:`References an encrypted value stored in Settings → Secrets — the real value never appears in the YAML.`, where:`API keys, database passwords, deploy credentials — anything that must never be visible in the repo.` },
    envVars: { syntax:`env:\n  NODE_ENV: production`, cmd:`env: block`, output: ghaBlock(`- run: npm run build\n  env:\n    NODE_ENV: production`, `<span class="ok">✓ NODE_ENV=production npm run build</span>`), does:`Sets an environment variable available to a step, a whole job, or the entire workflow.`, where:`Passing plain (non-secret) config into a build or test step, like which environment it's building for.` },
    githubToken: { syntax:`${'$'}{{ secrets.GITHUB_TOKEN }}`, cmd:`secrets.GITHUB_TOKEN`, output: ghaBlock(`- run: gh pr comment 42 --body "Build passed"\n  env:\n    GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}`, `<span class="ok">✓ Comment posted to PR #42</span>`), does:`A special secret GitHub creates automatically for every run, scoped to that repo — no setup needed.`, where:`Letting a workflow comment on a PR, create a release, or call the GitHub API on your behalf.` },
    uploadArtifact: { syntax:`- uses: actions/upload-artifact@v4\n  with:\n    path: dist/`, cmd:`upload-artifact`, output: ghaBlock(`- uses: actions/upload-artifact@v4\n  with:\n    name: build-output\n    path: dist/`, `<span class="ok">✓ Uploaded "build-output" (4.2MB)</span>`), does:`Saves files from the runner so they're downloadable from the run page after the job ends.`, where:`Keeping a build's compiled output or a test report, since the runner itself is destroyed the moment the job finishes.` },
    downloadArtifact: { syntax:`- uses: actions/download-artifact@v4\n  with:\n    name: build-output`, cmd:`download-artifact`, output: ghaBlock(`- uses: actions/download-artifact@v4\n  with:\n    name: build-output`, `<span class="ok">✓ Downloaded "build-output" into this job</span>`), does:`Pulls an artifact uploaded earlier in the workflow into a different job's runner.`, where:`A "build" job produces the app, and a separate "deploy" job downloads exactly that output to ship it.` },
    cacheDeps: { syntax:`- uses: actions/cache@v4\n  with:\n    path: ~/.npm\n    key: npm-${'$'}{{ hashFiles('package-lock.json') }}`, cmd:`actions/cache`, output: ghaBlock(`- uses: actions/cache@v4\n  with:\n    path: ~/.npm\n    key: npm-\${{ hashFiles('package-lock.json') }}`, `<span class="ok">Cache hit — restored in 2s</span> <span class="dim">(lockfile unchanged since last run)</span>`), does:`Saves and restores files between runs, keyed off something like a lockfile's hash.`, where:`Skipping a full dependency reinstall on every single run when nothing has actually changed.` },
    matrixBasic: { syntax:`strategy:\n  matrix:\n    node-version: [18, 20]`, cmd:`matrix (versions)`, output: ghaBlock(`strategy:\n  matrix:\n    node-version: [18, 20]\nsteps:\n  - uses: actions/setup-node@v4\n    with:\n      node-version: \${{ matrix.node-version }}`, `<span class="ok">✓ test (18) — passed</span>\n<span class="ok">✓ test (20) — passed</span>`), does:`Runs the same job once per value in the list, automatically, in parallel.`, where:`Confirming your app actually works across every Node/Python/Ruby version you claim to support.` },
    matrixOS: { syntax:`matrix:\n  os: [ubuntu-latest, windows-latest]\n  node: [18, 20]`, cmd:`matrix (OS × version)`, output: ghaBlock(`strategy:\n  matrix:\n    os: [ubuntu-latest, windows-latest]\n    node: [18, 20]`, `<span class="ok">✓ (ubuntu-latest, 18)</span>\n<span class="ok">✓ (ubuntu-latest, 20)</span>\n<span class="ok">✓ (windows-latest, 18)</span>\n<span class="ok">✓ (windows-latest, 20)</span>`), does:`Combines two matrix dimensions — every OS gets tested against every version listed, all combinations.`, where:`Cross-platform libraries that genuinely need to prove they work on more than just Linux.` },
    dockerBuildPush: { syntax:`- uses: docker/build-push-action@v5\n  with:\n    push: true`, cmd:`docker build + push`, output: ghaBlock(`- uses: docker/build-push-action@v5\n  with:\n    push: true\n    tags: myapp:\${{ github.sha }}`, `<span class="ok">✓ Built and pushed myapp:a3f9d2c</span>`), does:`Builds a Docker image from your Dockerfile and pushes it to a registry, in one action.`, where:`The build step of a real CI/CD pipeline — turning your code into a deployable image automatically.` },
    deploySSH: { syntax:`- uses: appleboy/ssh-action@v1\n  with:\n    script: ./deploy.sh`, cmd:`deploy over SSH`, output: ghaBlock(`- uses: appleboy/ssh-action@v1\n  with:\n    host: \${{ secrets.HOST }}\n    script: ./deploy.sh`, `<span class="ok">✓ Connected — deploy.sh executed on remote server</span>`), does:`Connects to a remote server over SSH and runs a deploy script there.`, where:`Deploying to a plain EC2/VM-based server that isn't running Kubernetes or a managed platform.` },
    deployKubernetes: { syntax:`- run: kubectl apply -f deployment.yaml`, cmd:`kubectl apply step`, output: ghaBlock(`- run: kubectl set image deployment/web web=myapp:\${{ github.sha }}`, `<span class="ok">deployment.apps/web image updated</span>`), does:`Runs a normal kubectl command as a workflow step to update a live cluster.`, where:`The actual "deploy" step of a pipeline targeting Kubernetes — see the Kubernetes for DevOps tab for the command itself.` },
    environmentProtection: { syntax:`environment: production`, cmd:`environment: (approval)`, output: ghaBlock(`jobs:\n  deploy:\n    environment: production\n    runs-on: ubuntu-latest`, `<span class="warn">⏸ Waiting for approval on "production"...</span>\n<span class="ok">✓ Approved — deploy proceeding</span>`), does:`Ties a job to a named environment that can require specific reviewers to approve before it runs.`, where:`The safety switch for real production deploys — configured once in Settings → Environments.` },
    concurrencyGroup: { syntax:`concurrency:\n  group: deploy-prod\n  cancel-in-progress: true`, cmd:`concurrency:`, output: ghaBlock(`concurrency:\n  group: deploy-prod\n  cancel-in-progress: true`, `<span class="warn">Canceling older run in group "deploy-prod"</span>\n<span class="ok">✓ Newest run proceeding</span>`), does:`Prevents overlapping runs in the same group — either queues them, or cancels the older one.`, where:`Stopping several rapid pushes from triggering multiple deploys that race each other to production.` },
    permissions: { syntax:`permissions:\n  contents: read`, cmd:`permissions:`, output: ghaBlock(`permissions:\n  contents: read`, `<span class="ok">✓ GITHUB_TOKEN scoped to read-only for this run</span>`), does:`Restricts what the automatic GITHUB_TOKEN is allowed to do for that run — least privilege by default.`, where:`A workflow that only reads code shouldn't also be able to write to the repo — this locks that down explicitly.` },
    reusableWorkflow: { syntax:`jobs:\n  call-shared:\n    uses: ./.github/workflows/shared.yml`, cmd:`reusable workflow`, output: ghaBlock(`jobs:\n  call-shared:\n    uses: ./.github/workflows/shared.yml\n    with:\n      env-name: staging`, `<span class="ok">✓ shared.yml — invoked with env-name=staging</span>`), does:`Lets one workflow file call another, passing inputs — write the logic once, reuse it everywhere.`, where:`A team with 10 repos that all deploy the same way — one shared workflow instead of 10 copy-pasted ones.` }
  };
  function runGhaCmd(key, btn) {
    const d = GHA_CMDS[key];
    if (!d) return;
    document.getElementById('ghaCmd').textContent = d.cmd;
    document.getElementById('ghaOutput').innerHTML = d.output;
    document.getElementById('ghaSyntax').innerHTML = d.syntax;
    document.getElementById('ghaDoes').innerHTML = d.does;
    document.getElementById('ghaWhere').innerHTML = d.where;
    document.querySelectorAll('#tab-ghactionsdevops .ld-pill').forEach(p => p.classList.remove('active'));
    if (btn) btn.classList.add('active');
  }

  /* ============ GITHUB ACTIONS FOR DEVOPS QUIZ ============ */
  const GHADEVOPS_QUIZ_JOKES = [
    `A runner's entire life: born, does one job, dies. No pension, no complaints.`,
    `"It works on my machine" has never once been an acceptable answer to a failed workflow run.`,
    `GITHUB_TOKEN: the only credential that's ever handed to you without a single password prompt.`,
    `Somewhere, a concurrency group just canceled a deploy so a newer, better deploy could win.`,
    `A green checkmark on a PR is worth more serotonin than it has any right to be.`
  ];

  const GHADEVOPS_QUIZ_QUESTIONS = [
    { q:`What is GitHub Actions, in the simplest terms?`, options:[`A robot built into GitHub that automatically runs a checklist you wrote every time code changes`,`A separate paid service you have to install and manage outside of GitHub entirely`,`A chat feature for talking with other developers working on the same repo`,`A tool that only works after your code has already been deployed to production`], correct:0, why:`That's the entire concept — everything else is just details layered on top of "automatic checklist."` },
    { q:`What problem does GitHub Actions actually solve?`, options:[`It removes the need for a human to remember to check code manually before it's trusted`,`It writes application code for you automatically, without a developer involved`,`It replaces the need to use Git for tracking changes to your code`,`It's only useful for fixing bugs that have already reached real users`], correct:0, why:`Human memory is unreliable — the whole point is making the check happen automatically, every time.` },
    { q:`What is a "workflow" in GitHub Actions?`, options:[`A single YAML file describing an automated checklist and when it should run`,`The general term for any code you push to a GitHub repository`,`A paid GitHub feature that must be purchased before it can be used`,`A folder containing your entire project's source code`], correct:0, why:`One file, one workflow — a repo can have several, each independent of the others.` },
    { q:`Where does a workflow file actually live in a repository?`, options:[`Inside the .github/workflows/ folder, as a .yml file`,`Anywhere at all — GitHub Actions searches the whole repo for workflow files`,`Only inside a special private area outside of the Git repository itself`,`It must be uploaded separately through a different website, not the repo`], correct:0, why:`That exact folder is the only place GitHub looks for workflow files.` },
    { q:`What is a "trigger" (the "on:" line)?`, options:[`The specific event that causes a workflow to actually start running`,`The final step that runs at the very end of every workflow`,`A setting that controls how many jobs a workflow is allowed to have`,`The name shown for a workflow in the GitHub Actions tab`], correct:0, why:`No matching event under on:, and the workflow simply never runs at all.` },
    { q:`What is a "job" in a workflow?`, options:[`A group of steps that all run together on one single runner`,`A single individual command, the smallest unit a workflow can have`,`The specific person responsible for maintaining that workflow file`,`A separate GitHub repository dedicated entirely to automation`], correct:0, why:`One job = one machine, with however many steps you give it.` },
    { q:`What is a "step"?`, options:[`One individual task inside a job, run in order along with the others`,`Another word meaning exactly the same thing as a whole workflow`,`A separate virtual machine created just for that one single task`,`The percentage of a job that has completed so far`], correct:0, why:`Steps are the smallest unit — the actual individual lines of the checklist.` },
    { q:`What is a "runner"?`, options:[`A temporary, fresh virtual machine GitHub creates just to run one job`,`Your own personal computer, which GitHub actions runs on directly`,`A person on the team responsible for approving every deployment`,`A permanent server that stays running between every single job`], correct:0, why:`It exists only for the duration of one job — nothing about it is permanent.` },
    { q:`What happens to a runner after a job finishes?`, options:[`It's destroyed — the next run always starts on a completely fresh machine`,`It stays running indefinitely, ready for the very next job to reuse`,`It gets saved as a snapshot for faster startup on the next run`,`It's manually shut down by a developer after checking the results`], correct:0, why:`That destruction is intentional — it guarantees every run starts from an identical, clean state.` },
    { q:`Do steps within one job run in order, or all at once?`, options:[`In order, top to bottom — and if one fails, the rest of that job stops`,`All at the exact same time, regardless of the order they're written in`,`In a random order chosen fresh by GitHub on every single run`,`In order, but a failed step never affects any of the steps after it`], correct:0, why:`Sequential and dependent — a failure genuinely halts everything after it in that job.` },
    { q:`Do multiple jobs in one workflow run in order, or at the same time?`, options:[`At the same time by default, unless one is explicitly told to wait for another`,`Always strictly in the order they're written in the YAML file`,`Only one job is allowed to exist per workflow file at all`,`In alphabetical order based on each job's given name`], correct:0, why:`Parallel by default — needs: is the one thing that changes that.` },
    { q:`What does "on: push" actually trigger the workflow on?`, options:[`Any time a commit is pushed to the repository`,`Only when a pull request is specifically opened, never a plain push`,`Only once per day, regardless of how many commits are pushed`,`Only when a repository is very first created on GitHub`], correct:0, why:`It's the broadest, simplest trigger — any push, any branch, unless narrowed further.` },
    { q:`What does "on: pull_request" trigger on?`, options:[`When a pull request is opened, or gets a new commit pushed to it`,`Only the very first time a repository's default branch is created`,`Every single time any file anywhere on GitHub is modified`,`Only after a pull request has already been fully merged`], correct:0, why:`This is what powers the green ✓ / red ✗ shown right on the PR page itself.` },
    { q:`What does "workflow_dispatch" add?`, options:[`A manual 'Run workflow' button you can click in the GitHub UI`,`A second, entirely separate GitHub Actions tab just for this file`,`An automatic daily run at midnight, with no way to disable it`,`A requirement that every push must be manually approved first`],correct:0, why:`It's specifically an on-demand trigger, not an automatic one.` },
    { q:`What does a "schedule" trigger with a cron expression do?`, options:[`Runs the workflow automatically on a timer, with no code push required`,`Deletes old, unused workflow runs automatically after a set time`,`Schedules a human to manually review the workflow's YAML file`,`Only works if the repository already has at least one scheduled event`], correct:0, why:`Purely time-based — completely independent of any push or PR activity.` },
    { q:`Why is "actions/checkout" usually the very first step in a job?`, options:[`A fresh runner starts completely empty — checkout is what fetches your code onto it`,`It's required before GitHub allows a workflow file to even be saved`,`It permanently installs Git onto every developer's personal machine`,`It automatically writes the rest of the workflow's steps for you`], correct:0, why:`Nothing else in that job has your files to work with until this step runs.` },
    { q:`What is a GitHub Marketplace action?`, options:[`A pre-built, reusable step someone else already wrote and published`,`A paid subscription required before any workflow can be created at all`,`The official name for GitHub's own built-in checkout step only`,`A separate marketplace for buying entirely new GitHub repositories`], correct:0, why:`Marketplace actions save you from writing common integrations from scratch.` },
    { q:`Why should a database password never be written directly into a workflow's YAML?`, options:[`The YAML file is committed to Git history, visible forever to anyone with repo access`,`YAML files are technically incapable of containing any text in quotes`,`GitHub Actions automatically deletes any workflow containing a password`,`It's actually completely fine, as long as the repository itself is private`], correct:0, why:`Even deleting the line in a later commit doesn't remove it from history.` },
    { q:`Where should a database password go instead?`, options:[`Stored in Settings → Secrets and variables → Actions, referenced by name`,`Emailed directly to every teammate before each individual deploy`,`Written as a code comment instead of a real line, so it's 'hidden'`,`Stored in a second, entirely separate GitHub repository just for secrets`], correct:0, why:`Secrets there are encrypted and never appear in the workflow file itself.` },
    { q:`What happens if a workflow step accidentally prints a secret's value to the log?`, options:[`GitHub automatically masks it as *** in the visible log output`,`The entire workflow run is permanently and irreversibly deleted`,`Nothing at all — the real value is shown in plain text to anyone who looks`,`The repository is automatically made private from that point onward`], correct:0, why:`Masking is automatic once a value is registered as a secret — a real safety net.` },
    { q:`What is GITHUB_TOKEN?`, options:[`A special secret GitHub creates automatically for every run, with no setup needed`,`A secret every developer has to manually create before their first workflow`,`A token that must be purchased separately from GitHub before it can be used`,`The personal login password for the GitHub account that owns the repo`], correct:0, why:`It's issued fresh, scoped to that repo, for every single run — zero setup required.` },
    { q:`What does "needs: test" on a deploy job actually do?`, options:[`Makes deploy wait until the test job finishes successfully before starting`,`Deletes the test job entirely once the deploy job has been added`,`Makes the deploy job run before the test job, instead of after it`,`Has no real effect — jobs always run in the order they're written`], correct:0, why:`It's the specific mechanism that turns default-parallel jobs into an ordered dependency.` },
    { q:`What does "if: github.ref == 'refs/heads/main'" do on a step?`, options:[`Only runs that step when the workflow is running on the main branch`,`Permanently deletes any branch that isn't named main`,`Runs that step on every branch except main, specifically excluding it`,`Requires a human to manually type 'main' before the step can run`], correct:0, why:`It's a conditional check evaluated fresh on every single run.` },
    { q:`What does "continue-on-error: true" do to a failing step?`, options:[`Lets the job continue to the next step instead of stopping on that failure`,`Automatically retries that exact step up to three more times`,`Immediately stops the entire workflow the moment that step fails`,`Silently deletes the step from the workflow file going forward`], correct:0, why:`It downgrades that one step's failure from job-ending to merely noted.` },
    { q:`What is a caching step (like actions/cache) actually for?`, options:[`Skipping a full dependency reinstall when nothing relevant has actually changed`,`Permanently storing a copy of your source code as a backup`,`Making the runner itself start up measurably faster in general`,`Required before actions/checkout is allowed to run in a job`], correct:0, why:`It targets one specific slow step — reinstalling unchanged dependencies — not the runner overall.` },
    { q:`How does actions/cache usually decide whether to reuse a cache?`, options:[`A key, often based on a hash of a lockfile — same key means same cache`,`It always reuses whatever cache is the very newest, regardless of contents`,`By checking the current date, refreshing automatically every single day`,`By asking the developer to manually confirm before every single run`], correct:0, why:`Change the lockfile, the hash changes, the key changes, and a fresh cache builds automatically.` },
    { q:`What does a "matrix" build let you do?`, options:[`Run the same job automatically across multiple versions or configurations at once`,`Run completely different, unrelated jobs all inside one single matrix`,`Limit a workflow to running only a fixed number of times per day`,`Require every job in a workflow to use the exact same OS and version`], correct:0, why:`One job definition, many real runs — one per listed combination.` },
    { q:`If a matrix has node-version: [18, 20], how many times does the job actually run?`, options:[`Twice — once for each value, automatically, without duplicating any YAML`,`Once, using only whichever version happens to be listed first`,`Eighteen times, based on misreading 18 as a literal repeat count`,`Zero times, since a matrix requires at least three listed values`], correct:0, why:`Each list entry becomes its own real, independent run of that job.` },
    { q:`What does actions/upload-artifact let you do?`, options:[`Save files from the runner so they're downloadable after the job finishes`,`Permanently deploy a build directly to production, with no other steps`,`Upload a workflow file itself to a separate, different repository`,`Automatically email a build's output to every listed contributor`], correct:0, why:`It's specifically about surviving the runner's destruction, not deployment itself.` },
    { q:`Why is uploading an artifact necessary at all, instead of just leaving files on the runner?`, options:[`The runner itself is destroyed the moment its job ends, taking everything on it`,`Runners technically have zero available disk space for any files`,`Artifacts are required before a workflow file is allowed to be saved`,`Files on a runner are visible to every other repository automatically`], correct:0, why:`Without uploading, anything written to that runner simply vanishes with it.` },
    { q:`What does "environment: production" on a job enable?`, options:[`The job can require specific reviewers to approve it before it's allowed to run`,`It automatically renames the job to 'production' in the run log`,`It doubles the amount of time the runner is allowed to stay alive`,`It's purely cosmetic and has no real effect on how the job runs`], correct:0, why:`Configured in Settings, this is a real gate, not just a label.` },
    { q:`Why would a team specifically want required approval on a production deploy job?`, options:[`It adds a real human checkpoint before code reaches real users, on purpose`,`It's required by GitHub before any job is allowed to use secrets at all`,`It makes the deploy step run measurably faster than it would otherwise`,`It's the only way to give a job access to the main branch's code`], correct:0, why:`A deliberate slowdown, in exchange for a human catching something automation might miss.` },
    { q:`What does a "concurrency" group with cancel-in-progress do?`, options:[`Cancels an older, still-running run in that group in favor of the newest one`,`Runs every push in that group simultaneously, all at the exact same time`,`Prevents that workflow from ever being triggered more than once, ever`,`Requires manual approval before any two runs are allowed to overlap`], correct:0, why:`Only the freshest run in the group is allowed to actually finish.` },
    { q:`Why would rapid, back-to-back pushes without a concurrency group be a problem for a deploy workflow?`, options:[`Multiple deploys could run at once and race each other to production`,`GitHub technically only allows one push to a repository per day`,`Each push would silently overwrite the repository's entire commit history`,`Workflow files themselves would become corrupted by simultaneous triggers`], correct:0, why:`Whichever deploy happens to finish last "wins," unpredictably, without a concurrency group.` },
    { q:`What does the "permissions:" block at the top of a workflow control?`, options:[`What the automatic GITHUB_TOKEN is allowed to do during that run`,`Which specific developers are allowed to view the workflow's results`,`How many jobs total are permitted to exist inside that one workflow`,`Whether the workflow is allowed to use any secrets at all, ever`], correct:0, why:`It's a least-privilege setting scoped specifically to that auto-issued token.` },
    { q:`What's the benefit of a "reusable workflow" (using: ./path/to/shared.yml)?`, options:[`Write the automation logic once and call it from many different workflows`,`It's required before more than one job is allowed in a workflow`,`It automatically duplicates a workflow across every repository you own`,`It merges two completely unrelated workflows into a single YAML file`], correct:0, why:`One source of truth for shared logic, called from wherever it's needed.` },
    { q:`What's the difference between a plain "run:" step and a "uses:" step?`, options:[`run: executes a raw shell command; uses: drops in a pre-built, packaged action`,`They're functionally identical — just two different keywords for the same thing`,`run: can only be used once per job, while uses: can repeat freely`,`uses: only works for Docker-related steps, run: works for everything else`], correct:0, why:`Write it yourself with run:, or reuse someone else's packaged step with uses:.` },
    { q:`What does github.sha refer to inside a workflow?`, options:[`The exact commit hash that triggered this specific run`,`The name of whichever branch triggered the workflow, not a commit`,`A random identifier that changes every time a workflow file is opened`,`The username of whoever most recently edited the workflow's YAML`], correct:0, why:`It's a direct, unambiguous pointer to the exact code that's being built or tested.` },
    { q:`Why tag a Docker image with \${{ github.sha }} instead of just "latest"?`, options:[`Every build becomes uniquely traceable back to the exact code that produced it`,`It's required by Docker itself — "latest" is not a valid tag name`,`It makes the resulting image noticeably smaller in file size`,`It's purely a style preference with no real practical benefit`], correct:0, why:`"latest" is ambiguous over time; a commit SHA never is.` },
    { q:`What is the actual first thing a beginner should automate with GitHub Actions?`, options:[`Running the existing test suite automatically on every push`,`A full, automatic production deploy pipeline, right from day one`,`A workflow that rewrites and reformats all of the project's code`,`Nothing — GitHub Actions should only be added after the project ships`], correct:0, why:`Tests-on-push catches the most bugs for the least setup and risk.` },
    { q:`Scenario: your test suite takes 3 minutes because it reinstalls dependencies from scratch every run. What's the fix?`, options:[`Add actions/cache keyed on the lockfile, so unchanged installs are skipped`,`Switch from actions/checkout to a completely different checkout action`,`Add more jobs to the workflow so the install runs in parallel instead`,`Remove the test step entirely so nothing needs to install at all`], correct:0, why:`This targets the actual slow part directly, without touching anything else.` },
    { q:`Scenario: you need to confirm your app works on both Node 18 and Node 20 without duplicating the job. What's the move?`, options:[`Use a matrix strategy with node-version: [18, 20]`,`Manually create two full, separate copies of the same job in the YAML`,`Use continue-on-error so one version's failure doesn't block the other`,`Add a schedule trigger so each version is tested on a different day`], correct:0, why:`Matrix is the built-in feature for exactly this "same job, multiple configs" need.` },
    { q:`Scenario: a deploy step needs a database password. Where does the real value live?`, options:[`In Settings → Secrets, referenced in the YAML as \${{ secrets.DB_PASSWORD }}`,`Typed directly into the run: command, since it's only visible to the team`,`In a comment above the step, so it's technically not an active line`,`In the workflow's name: field, since that's just a label anyway`], correct:0, why:`The value stays encrypted and out of the file entirely — only the reference lives in YAML.` },
    { q:`Scenario: a deploy job must never run unless the test job passed. What one line enforces this?`, options:[`needs: test, added to the deploy job`,`if: always(), added to the deploy job specifically`,`continue-on-error: false, added to the test job instead`,`Nothing needs to be added — this happens automatically by default`], correct:0, why:`Without needs:, deploy would start in parallel with test, not after it.` },
    { q:`Scenario: you want to build and push a Docker image only when code lands on main, never on other branches. What do you configure?`, options:[`on: push: branches: [main], scoping the trigger to that one branch`,`on: push, with no further configuration needed at all`,`if: docker == true, checked inside every single step`,`environment: main, set on the job instead of the trigger`], correct:0, why:`Scoping the trigger's branches list is exactly what narrows it to main only.` },
    { q:`Scenario: production deploys should require a real person to click approve first. What do you configure?`, options:[`environment: production, with required reviewers set in Settings`,`continue-on-error: true, so a human can intervene if it fails`,`A schedule trigger, so a human is always available when it runs`,`permissions: contents: write, which adds an approval requirement`], correct:0, why:`Required reviewers on an environment is the actual, dedicated approval mechanism.` },
    { q:`Scenario: three rapid pushes trigger three overlapping deploy runs. What stops them from racing?`, options:[`A concurrency group with cancel-in-progress: true`,`Reducing the number of jobs in the workflow down to just one`,`Switching the trigger from push to pull_request instead`,`Adding continue-on-error: true to the deploy job`], correct:0, why:`This is precisely the tool built to prevent overlapping runs of the same workflow.` },
    { q:`Scenario: you want a workflow log entry to prove exactly which commit produced a given Docker image later. What do you use?`, options:[`Tag the image with \${{ github.sha }} at build time`,`Rename the Docker image manually after every single deploy`,`Add a code comment inside the Dockerfile listing the commit by hand`,`Nothing is needed — Docker images already track this by default`], correct:0, why:`Baking the commit SHA into the tag is what makes that traceability automatic and reliable.` },
    { q:`Scenario: you're new to GitHub Actions and unsure where to even start on a real project. What's the right first workflow?`, options:[`Tests running automatically on every push — nothing more, at first`,`A full multi-environment deploy pipeline, to cover everything at once`,`A workflow that automatically merges every pull request instantly`,`Nothing — wait until the project has a dedicated DevOps hire`], correct:0, why:`Start small and genuinely useful — deploy automation comes later, once this is trusted.` },
    { q:`Scenario: a workflow step needs to comment on a pull request using the GitHub API. What credential does it use?`, options:[`The automatic \${{ secrets.GITHUB_TOKEN }} — no manual setup required`,`A developer's personal GitHub password, entered directly into the YAML`,`A brand-new GitHub account created specifically for this one workflow`,`It's not possible — workflows cannot interact with pull requests at all`], correct:0, why:`GITHUB_TOKEN already has exactly the access needed for this kind of repo interaction.` }
  ];
