  /* ============ KUBERNETES FOR DEVOPS — kubectl command simulator ============ */
  const K8S_CMDS = {
    clusterInfo: { syntax:`kubectl cluster-info`, cmd:`kubectl cluster-info`, output:`<span class="ok">Kubernetes control plane is running at https://10.0.0.1:6443</span>\nCoreDNS is running at https://10.0.0.1:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy`, does:`Shows the addresses of the cluster's control plane and core services.`, where:`A quick sanity check that kubectl is actually talking to a live, reachable cluster.` },
    getContexts: { syntax:`kubectl config get-contexts`, cmd:`kubectl config get-contexts`, output:`CURRENT   NAME              CLUSTER           NAMESPACE\n<span class="ok">*         prod-cluster      prod-cluster      default</span>\n          staging-cluster   staging-cluster   default`, does:`Lists every cluster/context kubectl knows about, marking which one is currently active.`, where:`Confirming which cluster you're about to run a command against — critical before anything destructive.` },
    useContext: { syntax:`kubectl config use-context &lt;name&gt;`, cmd:`kubectl config use-context staging-cluster`, output:`<span class="ok">Switched to context "staging-cluster".</span>`, does:`Switches kubectl's active cluster/context.`, where:`Moving between staging and production clusters without re-entering credentials each time.` },
    getNodes: { syntax:`kubectl get nodes`, cmd:`kubectl get nodes`, output:`NAME     STATUS   ROLES           AGE   VERSION\nnode-1   <span class="ok">Ready</span>    control-plane   30d   v1.29.2\nnode-2   <span class="ok">Ready</span>    worker          30d   v1.29.2\nnode-3   <span class="ok">Ready</span>    worker          12d   v1.29.2`, does:`Lists every node in the cluster and whether it's healthy and ready.`, where:`The first check when pods aren't scheduling — is there even a Ready node to put them on?` },
    version: { syntax:`kubectl version`, cmd:`kubectl version --short`, output:`Client Version: v1.29.2\n<span class="ok">Server Version: v1.29.0</span>`, does:`Shows the kubectl client version and the cluster's server version.`, where:`Confirming client/server compatibility before relying on newer API features.` },
    getPods: { syntax:`kubectl get pods`, cmd:`kubectl get pods`, output:`NAME                     READY   STATUS    RESTARTS   AGE\nweb-7d8f9c6b5d-abcde     1/1     <span class="ok">Running</span>   0          2h\nweb-7d8f9c6b5d-fghij     1/1     <span class="ok">Running</span>   0          2h`, does:`Lists pods in the current namespace, with status and restart count.`, where:`The single most-run kubectl command — checking whether your app is actually running.` },
    describePod: { syntax:`kubectl describe pod &lt;name&gt;`, cmd:`kubectl describe pod web-7d8f9c6b5d-abcde`, output:`Name: web-7d8f9c6b5d-abcde\nStatus: <span class="ok">Running</span>\nEvents:\n  Normal   Scheduled   2h   Successfully assigned to node-2\n  Normal   Pulled      2h   Container image pulled\n  Normal   Started     2h   Started container web`, does:`Shows full details and recent events for one specific pod.`, where:`Debugging why a pod won't start — the Events section at the bottom usually has the answer.` },
    runPod: { syntax:`kubectl run &lt;name&gt; --image=&lt;image&gt;`, cmd:`kubectl run debug --image=busybox --rm -it -- sh`, output:`If you don't see a command prompt, try pressing enter.\n<span class="ok">/ #</span>`, does:`Quickly creates and runs a single throwaway pod from an image.`, where:`Spinning up a quick debug pod inside the cluster's network to test connectivity to a service.` },
    deletePod: { syntax:`kubectl delete pod &lt;name&gt;`, cmd:`kubectl delete pod web-7d8f9c6b5d-abcde`, output:`<span class="ok">pod "web-7d8f9c6b5d-abcde" deleted</span>`, does:`Deletes a specific pod — if it's managed by a Deployment, a replacement is created automatically.`, where:`Forcing a stuck or misbehaving pod to restart fresh.` },
    execPod: { syntax:`kubectl exec -it &lt;pod&gt; -- &lt;cmd&gt;`, cmd:`kubectl exec -it web-7d8f9c6b5d-abcde -- bash`, output:`<span class="ok">root@web-7d8f9c6b5d-abcde:/#</span>`, does:`Opens an interactive shell inside a running pod's container.`, where:`Debugging a live pod from the inside — the same idea as docker exec.` },
    createDeployment: { syntax:`kubectl create deployment &lt;name&gt; --image=&lt;image&gt;`, cmd:`kubectl create deployment web --image=myapp:v2 --replicas=3`, output:`<span class="ok">deployment.apps/web created</span>`, does:`Creates a new Deployment, which manages a set of identical replica pods.`, where:`The standard way to actually run an application on Kubernetes — you almost never create raw pods directly.` },
    getDeployments: { syntax:`kubectl get deployments`, cmd:`kubectl get deployments`, output:`NAME   READY   UP-TO-DATE   AVAILABLE   AGE\nweb    <span class="ok">3/3</span>     3            3           2h`, does:`Lists deployments and whether all their desired replicas are ready.`, where:`Confirming a deployment actually reached its target replica count after a change.` },
    scaleDeployment: { syntax:`kubectl scale deployment &lt;name&gt; --replicas=&lt;n&gt;`, cmd:`kubectl scale deployment web --replicas=5`, output:`<span class="ok">deployment.apps/web scaled</span>`, does:`Changes how many replica pods a deployment should be running.`, where:`Manually scaling up for expected traffic, or scaling down to save cost.` },
    rolloutStatus: { syntax:`kubectl rollout status deployment/&lt;name&gt;`, cmd:`kubectl rollout status deployment/web`, output:`Waiting for deployment "web" rollout to finish: 2 out of 3 new replicas have been updated...\n<span class="ok">deployment "web" successfully rolled out</span>`, does:`Watches a rolling update in progress and reports when it's complete.`, where:`Confirming a new image version actually finished rolling out before moving on in a deploy script.` },
    rolloutUndo: { syntax:`kubectl rollout undo deployment/&lt;name&gt;`, cmd:`kubectl rollout undo deployment/web`, output:`<span class="ok">deployment.apps/web rolled back</span>`, does:`Rolls a deployment back to its previous revision.`, where:`The fastest way to recover from a bad deploy — one command, no rebuild needed.` },
    expose: { syntax:`kubectl expose deployment &lt;name&gt; --port=&lt;port&gt;`, cmd:`kubectl expose deployment web --port=80 --target-port=3000 --type=ClusterIP`, output:`<span class="ok">service/web exposed</span>`, does:`Creates a Service that gives a stable network endpoint in front of a deployment's pods.`, where:`Pods get recreated with new IPs constantly — a Service is what makes them reachable reliably.` },
    getSvc: { syntax:`kubectl get svc`, cmd:`kubectl get svc`, output:`NAME   TYPE        CLUSTER-IP     PORT(S)\nweb    ClusterIP   <span class="ok">10.96.0.15</span>     80/TCP`, does:`Lists services and their stable virtual IPs and ports.`, where:`Checking what internal (or external) address other pods/users should actually connect to.` },
    portForward: { syntax:`kubectl port-forward svc/&lt;name&gt; &lt;local&gt;:&lt;remote&gt;`, cmd:`kubectl port-forward svc/web 8080:80`, output:`<span class="ok">Forwarding from 127.0.0.1:8080 -> 80</span>\nForwarding from [::1]:8080 -> 80`, does:`Tunnels a local port straight to a service (or pod) inside the cluster, without needing it exposed publicly.`, where:`Debugging a service directly from your laptop without setting up a full LoadBalancer or Ingress.` },
    getEndpoints: { syntax:`kubectl get endpoints &lt;name&gt;`, cmd:`kubectl get endpoints web`, output:`NAME   ENDPOINTS\nweb    <span class="ok">10.244.1.5:3000,10.244.1.6:3000</span>`, does:`Shows the actual pod IPs a service is currently routing traffic to.`, where:`Confirming a service has real, healthy pods behind it — an empty list means nothing will ever answer.` },
    logs: { syntax:`kubectl logs &lt;pod&gt;`, cmd:`kubectl logs web-7d8f9c6b5d-abcde`, output:`Server listening on port 3000\n<span class="ok">GET /health 200</span>`, does:`Shows a pod's container logs.`, where:`The first thing to check when a pod is crashing or behaving unexpectedly.` },
    logsF: { syntax:`kubectl logs -f &lt;pod&gt;`, cmd:`kubectl logs -f web-7d8f9c6b5d-abcde`, output:`GET /health 200\n<span class="dim">(streaming live — Ctrl+C to stop)</span>`, does:`Streams a pod's logs live instead of a one-time dump.`, where:`Watching requests come in in real time while reproducing an issue.` },
    getEvents: { syntax:`kubectl get events --sort-by=.lastTimestamp`, cmd:`kubectl get events --sort-by=.lastTimestamp`, output:`LAST SEEN   TYPE      REASON        OBJECT          MESSAGE\n2m          <span class="err">Warning   FailedMount</span>   pod/web-abcde   Unable to mount volume\n5m          Normal    Scheduled     pod/web-fghij   Successfully assigned`, does:`Lists recent cluster-wide events in chronological order.`, where:`Spotting the exact moment something started going wrong, across every resource in the namespace.` },
    topPods: { syntax:`kubectl top pods`, cmd:`kubectl top pods`, output:`NAME                   CPU(cores)   MEMORY(bytes)\nweb-7d8f9c6b5d-abcde   <span class="ok">12m</span>          84Mi`, does:`Shows live CPU and memory usage per pod.`, where:`Finding a pod that's quietly eating way more resources than expected.` },
    describeNode: { syntax:`kubectl describe node &lt;name&gt;`, cmd:`kubectl describe node node-2`, output:`Name: node-2\nConditions: Ready=True\nAllocated resources:\n  cpu: <span class="warn">1200m/4000m</span>\n  memory: 2Gi/8Gi`, does:`Shows a node's health, capacity, and how much of it is already allocated to pods.`, where:`Figuring out why a pod won't schedule — the node might simply be out of room.` },
    createConfigmap: { syntax:`kubectl create configmap &lt;name&gt; --from-literal=&lt;k&gt;=&lt;v&gt;`, cmd:`kubectl create configmap app-config --from-literal=LOG_LEVEL=debug`, output:`<span class="ok">configmap/app-config created</span>`, does:`Creates a ConfigMap — a way to store non-sensitive config outside the container image.`, where:`Changing an app's config (like a log level) without rebuilding or redeploying the image itself.` },
    createSecret: { syntax:`kubectl create secret generic &lt;name&gt; --from-literal=&lt;k&gt;=&lt;v&gt;`, cmd:`kubectl create secret generic db-creds --from-literal=password=hunter2`, output:`<span class="ok">secret/db-creds created</span>`, does:`Creates a Secret — like a ConfigMap, but for sensitive values, base64-encoded at rest.`, where:`Storing database passwords and API keys separately from application code and images.` },
    getConfigmaps: { syntax:`kubectl get configmaps`, cmd:`kubectl get configmaps`, output:`NAME         DATA   AGE\napp-config   <span class="ok">1</span>      3h`, does:`Lists ConfigMaps in the current namespace.`, where:`Confirming a ConfigMap actually exists before a pod tries to mount it.` },
    applyF: { syntax:`kubectl apply -f &lt;file&gt;`, cmd:`kubectl apply -f deployment.yaml`, output:`<span class="ok">deployment.apps/web configured</span>`, does:`Creates or updates resources to match exactly what's described in a YAML file.`, where:`The standard, declarative way to manage Kubernetes resources — the backbone of GitOps.` },
    getNamespaces: { syntax:`kubectl get namespaces`, cmd:`kubectl get namespaces`, output:`NAME          STATUS   AGE\ndefault       <span class="ok">Active</span>   90d\nproduction    <span class="ok">Active</span>   60d\nkube-system   <span class="ok">Active</span>   90d`, does:`Lists every namespace — Kubernetes' way of splitting a cluster into isolated virtual sub-clusters.`, where:`Confirming which namespace resources actually live in before trying to reach them.` },
    createNamespace: { syntax:`kubectl create namespace &lt;name&gt;`, cmd:`kubectl create namespace staging`, output:`<span class="ok">namespace/staging created</span>`, does:`Creates a new isolated namespace.`, where:`Separating environments (staging, production) or teams within a single shared cluster.` },
    getRoles: { syntax:`kubectl get roles -n &lt;namespace&gt;`, cmd:`kubectl get roles -n production`, output:`NAME         AGE\n<span class="ok">pod-reader</span>   30d`, does:`Lists the RBAC Roles defined in a namespace — sets of permissions that can be granted.`, where:`Auditing exactly what actions are allowed within a given namespace.` },
    authCanI: { syntax:`kubectl auth can-i &lt;verb&gt; &lt;resource&gt;`, cmd:`kubectl auth can-i delete pods --namespace production`, output:`<span class="warn">no</span>`, does:`Checks whether the current user/service account is allowed to perform a specific action.`, where:`Quickly confirming permissions before assuming an RBAC policy actually grants (or blocks) something.` },
    autoscale: { syntax:`kubectl autoscale deployment &lt;name&gt; --min=&lt;n&gt; --max=&lt;n&gt; --cpu-percent=&lt;n&gt;`, cmd:`kubectl autoscale deployment web --min=2 --max=10 --cpu-percent=70`, output:`<span class="ok">horizontalpodautoscaler.autoscaling/web autoscaled</span>`, does:`Creates a Horizontal Pod Autoscaler that automatically scales replica count based on CPU usage.`, where:`Handling variable traffic automatically instead of manually running kubectl scale.` },
    rolloutHistory: { syntax:`kubectl rollout history deployment/&lt;name&gt;`, cmd:`kubectl rollout history deployment/web`, output:`REVISION  CHANGE-CAUSE\n1         Initial deploy\n2         Update to v2.1\n<span class="ok">3         Update to v2.2</span>`, does:`Lists every past revision of a deployment.`, where:`Deciding exactly which revision to roll back to instead of just "the previous one."` },
    setImage: { syntax:`kubectl set image deployment/&lt;name&gt; &lt;container&gt;=&lt;image&gt;`, cmd:`kubectl set image deployment/web web=myapp:v2.3`, output:`<span class="ok">deployment.apps/web image updated</span>`, does:`Updates a deployment's container image, triggering a rolling update automatically.`, where:`The actual command a CI/CD pipeline runs to deploy a new version — no YAML editing needed.` }
  };
  function runK8sCmd(key, btn) {
    const d = K8S_CMDS[key];
    if (!d) return;
    const lines = d.cmd.split('\n');
    document.getElementById('k8sCmd').textContent = lines[0];
    let extra = '';
    if (lines.length > 1) {
      extra = lines.slice(1).map(l => '<span class="ld-prompt">devops@server:~$</span> ' + l).join('\n') + '\n';
    }
    document.getElementById('k8sOutput').innerHTML = extra + d.output;
    document.getElementById('k8sSyntax').innerHTML = d.syntax || lines[0];
    document.getElementById('k8sDoes').innerHTML = d.does;
    document.getElementById('k8sWhere').innerHTML = d.where;
    document.querySelectorAll('#tab-k8sdevops .ld-pill').forEach(p => p.classList.remove('active'));
    if (btn) btn.classList.add('active');
  }

  /* ============ KUBERNETES FOR DEVOPS QUIZ ============ */
  const K8SDEVOPS_QUIZ_JOKES = [
    `CrashLoopBackOff: Kubernetes' polite way of saying "I've tried restarting this six times and I'm starting to worry about you."`,
    `A pod without a Service is like a phone number that changes every time someone calls it.`,
    `kubectl rollout undo: the closest thing DevOps has to a real Ctrl+Z.`,
    `"0/3 nodes are available" is Kubernetes' version of walking into a full parking lot.`,
    `Somewhere, an HPA is scaling a deployment up right now just so you don't have to wake up for it.`
  ];

  const K8SDEVOPS_QUIZ_QUESTIONS = [
    { q:`What's the fundamental difference between a Pod and a Deployment?`, options:[`A Pod is one or more running containers; a Deployment manages a set of replica Pods`,`A Deployment is a single container; a Pod manages a set of replica Deployments`,`They're two different names for exactly the same underlying Kubernetes object`,`A Pod only exists inside a Deployment and can never exist by itself`], correct:0, why:`The Pod is the actual running unit; the Deployment is what keeps the right number of them alive.` },
    { q:`Why do you almost never create raw Pods directly in production?`, options:[`A Deployment automatically recreates a Pod if it crashes or the node fails`,`Raw Pods are technically not permitted by the Kubernetes API itself`,`Pods created directly cannot be exposed by a Service at all`,`Deployments are required before any container image can be pulled`], correct:0, why:`A bare Pod that dies just stays dead — a Deployment is what gives you real self-healing.` },
    { q:`What does a Kubernetes Service actually provide?`, options:[`A stable network endpoint that stays constant even as the Pods behind it come and go`,`A completely separate virtual machine dedicated to running one application`,`A build pipeline that automatically deploys new code on every commit`,`A fixed IP address assigned permanently to one specific Pod`], correct:0, why:`Pods are disposable and constantly recreated — the Service is the one thing that stays put.` },
    { q:`Why do Pods need a stable Service in front of them at all?`, options:[`Pods get new IPs every time they're recreated, so nothing else could reliably reach them otherwise`,`Pods are technically incapable of having any IP address of their own`,`Services are only needed for Pods running outside of a Deployment`,`Kubernetes requires a Service before any Pod is allowed to start`], correct:0, why:`Without a Service, every Pod restart would mean updating every client that depended on its old IP.` },
    { q:`What's the difference between "kubectl logs <pod>" and "kubectl logs <pod> --previous"?`, options:[`--previous shows the log from a container that already crashed and restarted, not the current attempt`,`--previous shows logs from an entirely different, previously-deployed application`,`There's no real difference — both always show exactly the same output`,`--previous only works for Pods that have never crashed at all`], correct:0, why:`Once a container restarts, the current attempt's logs start empty — --previous is where the crash evidence actually is.` },
    { q:`What does "kubectl describe pod <name>" show that "kubectl get pods" doesn't?`, options:[`Full details and a timeline of recent events for that one specific Pod`,`A live stream of that Pod's container logs, updating continuously`,`The Pod's CPU and memory usage over the last 24 hours`,`A list of every other Pod running in the same namespace`], correct:0, why:`get pods gives you a status line; describe gives you the full story, including why something failed.` },
    { q:`A Pod shows status "Pending" and never starts. What's a likely cause the scheduler would report?`, options:[`No node currently has enough free CPU or memory to fit the Pod`,`The Pod's container image doesn't technically exist anywhere`,`Pending pods always mean the Kubernetes API server itself is down`,`The Pod's YAML file was formatted using tabs instead of spaces`], correct:0, why:`The scheduler can't place a Pod anywhere that doesn't have room for it — that's the single most common Pending cause.` },
    { q:`What does a rolling update actually do?`, options:[`Gradually replaces old Pods with new ones, keeping the app available throughout`,`Immediately deletes every old Pod before starting any new ones`,`Only updates the Pod with the least recent restart count`,`Pauses the entire application until every Pod has been replaced`], correct:0, why:`The whole point is zero-downtime — old and new Pods briefly coexist instead of a hard cutover.` },
    { q:`What does "kubectl rollout status deployment/<name>" let you do?`, options:[`Watch a rolling update in progress and confirm exactly when it finishes`,`Manually pause a rolling update that's currently in progress`,`Permanently delete the deployment's rollout history`,`List every deployment currently rolling out across the whole cluster`], correct:0, why:`It's a live progress check — genuinely useful for a deploy script deciding when it's safe to continue.` },
    { q:`What does "kubectl rollout undo deployment/<name>" do?`, options:[`Rolls the deployment back to its previous revision`,`Permanently deletes the deployment and all of its Pods`,`Pauses the deployment without changing anything about its Pods`,`Scales the deployment's replica count back down to zero`], correct:0, why:`It's a full revert — Kubernetes already remembers the previous revision's configuration.` },
    { q:`Why is "kubectl rollout undo" often faster than a manual fix for a bad deploy?`, options:[`It reverts to a known-good revision instantly, without needing a new image build`,`It automatically finds and fixes the actual bug in the application code`,`It's not actually faster — manual fixes are always quicker to apply`,`It only works if the bad deploy happened within the last five minutes`], correct:0, why:`Recovery and root-causing are two separate problems — undo solves the first one immediately.` },
    { q:`What does "kubectl scale deployment <name> --replicas=5" do?`, options:[`Changes how many replica Pods that deployment should be running`,`Increases the CPU limit assigned to each existing Pod by 5x`,`Creates 5 entirely separate, independently-named deployments`,`Schedules the deployment to automatically restart every 5 minutes`], correct:0, why:`It just changes the target replica count — Kubernetes handles creating or removing Pods to match.` },
    { q:`What's the purpose of a Horizontal Pod Autoscaler (HPA)?`, options:[`Automatically adjusts replica count up or down based on real-time metrics like CPU usage`,`Automatically increases a single Pod's CPU and memory limits over time`,`Manually triggers a human to review and approve scaling decisions`,`Converts a Deployment into a different, more powerful resource type`], correct:0, why:`It's scale-out (more replicas), not scale-up (bigger Pods) — and it reacts to live metrics on its own.` },
    { q:`What does "kubectl autoscale deployment web --min=2 --max=10 --cpu-percent=70" configure?`, options:[`Keep replicas between 2 and 10, scaling up once average CPU passes 70%`,`Immediately scale the deployment to exactly 70 replicas`,`Limit the deployment to a maximum of 70% of the cluster's total CPU`,`Restart any Pod that exceeds 70% memory usage, without scaling`], correct:0, why:`Those three flags define the floor, ceiling, and the trigger threshold for automatic scaling.` },
    { q:`What's the difference between a ConfigMap and a Secret?`, options:[`A ConfigMap holds regular config values; a Secret holds sensitive ones, base64-encoded at rest`,`They're functionally identical — Secret is simply a newer name for ConfigMap`,`A ConfigMap can only be used by Deployments, never by raw Pods`,`A Secret can only ever store a single value, unlike a ConfigMap`], correct:0, why:`Same basic mechanism, different intent — Secrets get treated more carefully by Kubernetes and its tooling.` },
    { q:`Why use a ConfigMap instead of hardcoding config values into a container image?`, options:[`Config can change without rebuilding or redeploying the image itself`,`ConfigMaps make the resulting container image significantly smaller`,`Kubernetes technically refuses to run any image without one attached`,`It's required before a Pod is allowed to expose any network port`], correct:0, why:`Separating config from the image means one image can run identically across every environment.` },
    { q:`What does "kubectl apply -f deployment.yaml" do?`, options:[`Creates or updates resources so the cluster matches exactly what's described in the file`,`Only creates new resources — it errors out if they already exist`,`Deletes whatever resource is currently running before creating a fresh one`,`Validates the YAML file's syntax without actually changing anything`], correct:0, why:`apply is idempotent by design — running it again with no changes just does nothing.` },
    { q:`Why is "kubectl apply -f" considered the standard, declarative way to manage resources?`, options:[`You describe the desired end state, and Kubernetes figures out how to get there`,`It's simply the only command kubectl actually provides for creating resources`,`It requires manually specifying every individual step needed to reach that state`,`It only works for Pods, not for Deployments, Services, or ConfigMaps`], correct:0, why:`Declarative means stating the "what," not scripting the "how" — that's the whole GitOps philosophy.` },
    { q:`What does a Kubernetes namespace actually provide?`, options:[`An isolated virtual sub-cluster for grouping and separating resources`,`A completely separate physical cluster with its own dedicated hardware`,`A backup copy of every resource, kept in case the original is deleted`,`A required wrapper that every single container image must be built inside`], correct:0, why:`It's a logical boundary within one real cluster, not a separate piece of infrastructure.` },
    { q:`Why might a team use separate namespaces for staging and production?`, options:[`Keeps resources, configs, and access isolated within one shared cluster`,`Namespaces are required before Kubernetes allows more than one Deployment`,`It's the only way to give staging and production different IP addresses`,`Separate namespaces automatically run on physically separate hardware`], correct:0, why:`One cluster, cleanly separated environments — without needing to run and maintain two clusters.` },
    { q:`What does "kubectl auth can-i delete pods --namespace production" check?`, options:[`Whether the current user/service account is actually allowed to perform that action`,`Whether any pods currently exist in the production namespace at all`,`Whether the production namespace itself has been properly created yet`,`Whether deleting a pod would cause any other resources to break`], correct:0, why:`It's a permissions check, purely — it doesn't even need the target resource to actually exist.` },
    { q:`What's the point of checking permissions with "kubectl auth can-i" before running a command?`, options:[`Confirming access ahead of time instead of finding out only after a command fails`,`It's required by Kubernetes before any command is allowed to run at all`,`It automatically grants the permission if it doesn't already exist`,`It's purely informational and has no real practical use case`], correct:0, why:`Especially mid-incident, knowing you're blocked before you try beats a failed command wasting time.` },
    { q:`What does an RBAC Role define in Kubernetes?`, options:[`A specific set of permissions — which actions are allowed on which resources`,`A physical role assigned to one specific node in the cluster`,`The container image that a Pod is required to run`,`A naming convention that Pods must follow within a namespace`], correct:0, why:`Roles describe capability ("can list pods"), and a RoleBinding is what actually grants it to someone.` },
    { q:`What does "kubectl get nodes" show?`, options:[`Every node in the cluster and whether it's currently healthy and ready`,`Every Pod currently running, grouped by which node it's on`,`The total number of Deployments configured across the whole cluster`,`A live feed of network traffic between all nodes in the cluster`], correct:0, why:`It's the machine-level view — the actual servers Pods get scheduled onto.` },
    { q:`Why would a Pod fail to schedule even though the cluster has multiple nodes?`, options:[`None of the nodes currently have enough free resources to fit it`,`Kubernetes only ever schedules Pods onto exactly one node, chosen at random`,`Nodes are only usable for scheduling after being manually approved`,`Pods can only schedule onto a node with the exact same name as the Pod`], correct:0, why:`The scheduler needs an actual fit — capacity, taints, and affinity rules all factor in.` },
    { q:`What does a taint on a node do?`, options:[`Repels Pods from scheduling there, unless they have a matching toleration`,`Immediately deletes every Pod currently running on that node`,`Marks the node as permanently unusable for the rest of its lifetime`,`Forces every future Pod in the cluster to schedule there instead`], correct:0, why:`It's opt-in exclusion — only Pods that explicitly tolerate the taint can land there.` },
    { q:`What's the difference between a taint and node affinity?`, options:[`A taint repels Pods by default; affinity attracts Pods toward preferred nodes`,`They do exactly the same thing, just using two different YAML keys`,`Affinity repels Pods; taints attract Pods — the opposite of each other`,`Taints only apply to Services, while affinity only applies to Pods`], correct:0, why:`Taints push away by default; affinity is a softer pull toward — opposite directions, different strength.` },
    { q:`What does "kubectl port-forward svc/web 8080:80" let you do?`, options:[`Reach the service from your local machine without exposing it externally`,`Permanently change the service's port from 80 to 8080`,`Forward all cluster traffic through your local machine as a proxy`,`Expose the service publicly on the internet at port 8080`], correct:0, why:`It's a temporary tunnel just for you — nothing about the service itself changes.` },
    { q:`What does "kubectl get endpoints <service>" show?`, options:[`The actual Pod IPs that service is currently routing traffic to`,`The public internet-facing URL assigned to that service`,`How many times that service has been called in the last hour`,`The YAML configuration originally used to create that service`], correct:0, why:`Endpoints are the live, real-time list of Pods actually backing that service right now.` },
    { q:`What does it mean if "kubectl get endpoints <service>" returns an empty list?`, options:[`No healthy Pods currently match that service's selector — nothing will answer`,`The service has been deleted, even though get svc still shows it`,`The service is working perfectly and just has extremely low traffic`,`Endpoints are only populated once every 24 hours by default`], correct:0, why:`An empty endpoints list is a very specific, very common symptom of a broken or missing selector match.` },
    { q:`What does "kubectl top pods" show?`, options:[`Live CPU and memory usage for each Pod`,`The total number of Pods currently running in the cluster`,`A ranked list of which Pods have restarted the most times`,`The exact YAML definition used to create each Pod`], correct:0, why:`It's the Kubernetes equivalent of "docker stats" — real-time resource usage per Pod.` },
    { q:`What does "kubectl exec -it <pod> -- bash" let you do?`, options:[`Open an interactive shell inside a running Pod's container`,`Permanently modify that Pod's container image on disk`,`Execute a script located on your own local machine, not the Pod`,`Create a brand-new Pod using the same image as an existing one`], correct:0, why:`It's a live session inside the running container — same idea as docker exec, one layer up.` },
    { q:`What does "kubectl set image deployment/web web=myapp:v2.3" do?`, options:[`Updates the deployment's container image, triggering a rolling update automatically`,`Renames the deployment from web to myapp:v2.3`,`Only updates the image tag shown in kubectl get pods, not the real Pods`,`Requires manually deleting and recreating every Pod by hand afterward`], correct:0, why:`Changing the image spec is enough — the Deployment controller handles the actual rollout itself.` },
    { q:`What does "kubectl rollout history deployment/<name>" let you do?`, options:[`See every past revision of that deployment, to pick exactly which one to roll back to`,`See a live log of every command ever run against that deployment`,`Permanently delete every past revision except the current one`,`See which specific engineer created the deployment originally`], correct:0, why:`Sometimes "the previous one" isn't the fix — this is how you pick the actual right revision.` },
    { q:`Why might a DevOps engineer prefer "kubectl set image" over manually editing YAML and reapplying it?`, options:[`It's a quick one-line way to trigger exactly one focused change — the image version`,`It's the only method Kubernetes provides for changing an image at all`,`Manually editing YAML is technically impossible once a deployment exists`,`set image also automatically updates the service's exposed port`], correct:0, why:`Both approaches work — set image is just the fast path for this one specific, common change.` },
    { q:`What's the actual purpose of a readiness probe versus a liveness probe?`, options:[`Readiness controls whether traffic is sent to a Pod; liveness controls whether it gets restarted`,`They're the exact same check, just triggered at two different times`,`Liveness controls traffic; readiness controls whether the Pod restarts`,`Readiness only matters for Services, while liveness only matters for Deployments`], correct:0, why:`Readiness gates traffic in; liveness keeps the container healthy over its whole lifetime.` },
    { q:`What does "kubectl create configmap app-config --from-literal=LOG_LEVEL=debug" do?`, options:[`Creates a ConfigMap storing that one key-value pair for Pods to consume`,`Immediately restarts every Pod using the app-config ConfigMap`,`Sets an environment variable directly on the Kubernetes API server itself`,`Only works if a matching Secret with the same name already exists`], correct:0, why:`Just creates the object — Pods still need to actually reference it to pick up the value.` },
    { q:`Why store a database password in a Secret instead of a ConfigMap?`, options:[`Secrets are meant for sensitive values, kept separate from plain config`,`ConfigMaps are technically incapable of storing any string value at all`,`There's no real difference — Secret is just a longer name for the same thing`,`Secrets are the only resource type that supports more than one key`], correct:0, why:`It's about intent and handling — Secrets get treated with more care by Kubernetes and surrounding tooling.` },
    { q:`What does "kubectl create deployment web --image=myapp:v2 --replicas=3" create?`, options:[`A Deployment managing 3 identical replica Pods running that image`,`Three completely separate Deployments, each with a single replica`,`One Pod with three separate containers running inside of it`,`A Service exposing the image, without creating any Pods at all`], correct:0, why:`One Deployment object, one desired replica count — Kubernetes creates the matching Pods.` },
    { q:`What's the relationship between a Deployment and a ReplicaSet?`, options:[`A Deployment manages ReplicaSets, and each ReplicaSet manages a set of identical Pods`,`They're exactly the same object, just displayed under two different names`,`A ReplicaSet manages Deployments, which is the reverse of how it actually works`,`ReplicaSets are only used for Pods that don't belong to any Deployment`], correct:0, why:`This layering is exactly what makes rolling updates possible — old and new ReplicaSets coexist briefly.` },
    { q:`Scenario: a Pod keeps entering CrashLoopBackOff. What's the right first command to understand why?`, options:[`kubectl logs <pod> --previous — to see the crashed container's own output`,`kubectl get nodes — since node health is always the actual cause`,`kubectl create namespace — to give the Pod a completely fresh environment`,`kubectl expose deployment — since exposing it usually resolves crashes`], correct:0, why:`The crash's own output is exactly what --previous surfaces — start there before anything else.` },
    { q:`Scenario: a Pod has been stuck in "Pending" for several minutes. What do you check first?`, options:[`kubectl describe pod <pod> — the Events section explains why scheduling failed`,`kubectl logs <pod> — even though a Pending pod has no container running yet`,`kubectl rollout undo — since Pending always means the last rollout failed`,`kubectl top pods — since resource usage explains scheduling failures`], correct:0, why:`A Pending pod has no logs yet — describe's Events are where the scheduler explains itself.` },
    { q:`Scenario: another Pod can't reach a service, and you suspect no healthy Pods are behind it. What confirms this?`, options:[`kubectl get endpoints <service> — an empty list means nothing is actually behind it`,`kubectl get namespaces — since namespaces control which Pods can connect`,`kubectl auth can-i — since this is fundamentally a permissions problem`,`kubectl rollout history — since past revisions explain current connectivity`], correct:0, why:`Endpoints is the direct, factual answer to "is anything actually behind this service right now."` },
    { q:`Scenario: you need to test a service directly from your laptop without setting up a public LoadBalancer. What do you run?`, options:[`kubectl port-forward svc/<name> <local-port>:<remote-port>`,`kubectl expose deployment --type=LoadBalancer, since that's the only real option`,`kubectl create secret, since services require a secret to be reachable locally`,`kubectl top pods, since that also reveals a service's real network address`], correct:0, why:`port-forward is built exactly for this — a quick, local, no-infrastructure-change way in.` },
    { q:`Scenario: a deployment you just pushed is clearly broken in production. What's the fastest recovery?`, options:[`kubectl rollout undo deployment/<name> — instantly reverts to the last known-good revision`,`kubectl delete deployment, then manually recreate everything from scratch`,`kubectl scale deployment --replicas=0, and leave the app down until a fix ships`,`kubectl create configmap, since bad deploys are usually a config problem`], correct:0, why:`Undo restores service immediately — you can root-cause the real issue afterward, calmly.` },
    { q:`Scenario: you need to change an app's log level without rebuilding its container image. What's the move?`, options:[`Update the ConfigMap it reads from, then restart the Pods to pick up the change`,`Use kubectl set image, since that's how any configuration change is applied`,`This isn't possible — any config change always requires a new image build`,`Use kubectl rollout undo, since that resets all configuration to its defaults`], correct:0, why:`This is exactly the separation ConfigMaps exist for — config changes independent of the image.` },
    { q:`Scenario: before running a risky delete command, you want to confirm you're actually allowed to. What do you run?`, options:[`kubectl auth can-i delete pods --namespace production`,`kubectl get roles, since that alone confirms your own specific permissions`,`kubectl describe pod, since Pod details include your account's permissions`,`There's no way to check this — you can only find out by attempting it`], correct:0, why:`can-i answers the exact question — checking a role list still requires interpreting which one applies to you.` },
    { q:`Scenario: traffic is expected to spike significantly during a sale, and pods should scale automatically. What do you set up?`, options:[`kubectl autoscale deployment <name> --min=<n> --max=<n> --cpu-percent=<n>`,`kubectl scale deployment once, right before the sale begins, and leave it fixed`,`kubectl create namespace dedicated specifically to handling traffic spikes`,`kubectl rollout status, since that automatically triggers scaling when needed`], correct:0, why:`A fixed scale is a guess; an HPA actually reacts to real load as it happens.` },
    { q:`Scenario: "kubectl get pods" shows a deployment at 2/3 ready, and it's been stuck that way for a while. What's a good next step?`, options:[`kubectl describe pod on the pod that isn't ready, to see why it's failing`,`kubectl delete namespace, since a stuck rollout means the namespace is corrupted`,`kubectl create secret, since missing secrets always cause exactly this symptom`,`Nothing can be done — a stuck rollout can only be fixed by restarting the cluster`], correct:0, why:`Go straight to the specific pod that isn't ready — its own events usually explain the whole stall.` },
    { q:`Scenario: you want to see exactly which past revision of a deployment to roll back to, not just "the previous one." What do you check first?`, options:[`kubectl rollout history deployment/<name> — lists every revision and its change cause`,`kubectl get events, since events list every past deployment revision too`,`kubectl top pods, since resource usage differs meaningfully by revision`,`kubectl auth can-i, since permissions determine which revision is shown`], correct:0, why:`History gives you the actual list of revisions with context — exactly what's needed to pick the right one.` }
  ];
