  const NETDEVOPS_CMDS = {
    ipAddr: { syntax:`ip addr`, runs:[
      { cmd:`ip addr`, output:`2: eth0: &lt;BROADCAST,MULTICAST,UP,LOWER_UP&gt; mtu 1500\n    inet <span class="ok">192.168.1.100</span>/24 brd 192.168.1.255 scope global eth0\n\n1: lo: &lt;LOOPBACK,UP,LOWER_UP&gt; mtu 65536\n    inet <span class="hi">127.0.0.1</span>/8 scope host lo`, reading:`eth0 is the machine's real network interface, lo is always 127.0.0.1 (itself talking to itself) — this is the private IP everything else in this tab builds on top of.` },
      { cmd:`ip addr`, output:`2: eth0: &lt;NO-CARRIER,BROADCAST,MULTICAST,UP&gt; mtu 1500\n    <span class="err">(no inet line at all)</span>`, reading:`NO-CARRIER and no inet address means the interface is up but has no actual network connection — like a cable unplugged. No IP was ever assigned.` },
      { cmd:`ip addr show eth0`, output:`2: eth0: &lt;BROADCAST,MULTICAST,UP,LOWER_UP&gt; mtu 1500\n    inet <span class="ok">10.0.4.12</span>/20 brd 10.0.15.255 scope global eth0`, reading:`Filtering to just one interface — same command, one argument added — useful on a machine with several NICs when you only care about one.` }
    ], does:`Lists every network interface on this machine and the IP address(es) assigned to each one.`, where:`The very first command to run when you need to know "what is this machine's own IP address" — before you can SSH into a server, share it, or debug connectivity, you need this.`, breakdown:[{term:`ip addr`, desc:`show every network interface and its assigned address`},{term:`eth0`, desc:`a real network interface — this machine's actual connection`},{term:`192.168.1.100/24`, desc:`its private IP, in CIDR notation`},{term:`lo`, desc:`the "loopback" interface — always 127.0.0.1, the machine talking to itself`}], whyUseful:`<div class="found-p">You just launched a server and need to know its private IP to SSH into it, or to tell another service how to reach it.</div><div class="found-pre">$ ip addr\n2: eth0: ... inet 192.168.1.100/24 ...</div><div class="found-p">That's the machine's real address on the network — the number everything else in this tab builds on top of.</div>` },
    hostnameI: { syntax:`hostname -I`, runs:[
      { cmd:`hostname -I`, output:`<span class="ok">192.168.1.100</span> <span class="dim">172.17.0.1</span>`, reading:`Two addresses — the real network IP, plus a second one from Docker's own virtual bridge network. Both are legitimately "this machine's" IPs.` },
      { cmd:`MY_IP=$(hostname -I | awk '{print $1}')
echo $MY_IP`, output:`<span class="ok">192.168.1.100</span>`, reading:`awk '{print $1}' grabs just the FIRST address — exactly the pattern a deploy script uses to get one clean value instead of parsing the full multi-address line.` },
      { cmd:`hostname -I`, output:`<span class="err">(nothing printed)</span>`, reading:`Empty output means this machine has no IP address assigned on any interface at all right now — a real, if rare, networking-not-even-started state.` }
    ], does:`Prints just the IP address(es) for this machine — no extra interface details, one clean line.`, where:`A quick one-liner when you just need the IP and nothing else, especially inside a script.`, breakdown:[{term:`hostname`, desc:`the command — normally prints the machine's name`},{term:`-I`, desc:`instead, print every IP address assigned to it`}], whyUseful:`<div class="found-p">A deploy script needs this server's own IP to register itself with a load balancer — parsing the full "ip addr" output just for one number is overkill.</div><div class="found-pre">$ MY_IP=$(hostname -I | awk '{print $1}')</div><div class="found-p">One clean value, straight into a variable, no extra parsing needed.</div>` },
    ifconfigMe: { syntax:`curl ifconfig.me`, runs:[
      { cmd:`curl ifconfig.me`, output:`<span class="ok">203.0.113.45</span>`, reading:`This is the PUBLIC IP — what the rest of the internet sees this machine as, completely different from the private 192.168.x.x address.` },
      { cmd:`curl ifconfig.me`, output:`<span class="warn">203.0.113.45</span> <span class="dim">(same answer as yesterday)</span>`, reading:`Public IPs from most home/office ISPs are usually stable but NOT guaranteed permanent — checking again confirms whether it's still the same before whitelisting it somewhere.` },
      { cmd:`curl ifconfig.me`, output:`<span class="err">curl: (6) Could not resolve host: ifconfig.me</span>`, reading:`DNS itself is failing on this machine — this specific check can't even reach the outside service, which points at a local DNS problem, not a firewall or app issue.` }
    ], does:`Asks an external website what IP address your request came from — that's your machine's PUBLIC IP, as the internet actually sees it.`, where:`Your private IP (192.168.x.x) means nothing outside your own network — this is the address the rest of the internet uses to reach you.`, breakdown:[{term:`curl`, desc:`makes an HTTP request`},{term:`ifconfig.me`, desc:`a free service whose whole job is to reply with "here's the IP you just connected from"`}], whyUseful:`<div class="found-p">You need to whitelist your home/office IP in a cloud firewall rule so only you can SSH in — but "ip addr" only shows your PRIVATE IP, which is useless for that.</div><div class="found-pre">$ curl ifconfig.me\n203.0.113.45</div><div class="found-p">That's the number you actually put in the security group rule — your private IP behind a router is never what the outside world sees.</div>` },

    nslookup: { syntax:`nslookup &lt;domain&gt;`, runs:[
      { cmd:`nslookup google.com`, output:`Server:   8.8.8.8\nAddress:  8.8.8.8#53\n\nNon-authoritative answer:\nName:  google.com\n<span class="ok">Address: 142.250.80.14</span>`, reading:`Resolves cleanly — the domain points to a real IP, and 8.8.8.8 (Google's public DNS) is the server that answered.` },
      { cmd:`nslookup myapp.com`, output:`Server:   8.8.8.8\nAddress:  8.8.8.8#53\n\n<span class="err">** server can't find myapp.com: NXDOMAIN</span>`, reading:`NXDOMAIN means this domain simply doesn't exist in DNS at all — not a slow answer, not a network issue, the record itself was never created (or was mistyped).` },
      { cmd:`nslookup myapp.com 1.1.1.1`, output:`Server:   1.1.1.1\nAddress:  1.1.1.1#53\n\nNon-authoritative answer:\n<span class="ok">Address: 93.184.216.34</span>`, reading:`Same domain, a different DNS server (1.1.1.1 instead of the default) — and this one HAS the answer. This is exactly how you'd catch a DNS propagation delay on one specific resolver.` }
    ], does:`Asks a DNS server "what IP address does this domain point to" and prints the answer.`, where:`The quickest way to check whether a domain resolves at all, and to what.`, breakdown:[{term:`nslookup`, desc:`the DNS lookup tool`},{term:`google.com`, desc:`the domain you're asking about`},{term:`Address: 142.250.80.14`, desc:`the actual answer — this is the IP behind the domain`}], whyUseful:`<div class="found-p">Someone says "the site isn't loading" and you need to rule DNS in or out as the cause, fast.</div><div class="found-pre">$ nslookup myapp.com\n** server can't find myapp.com: NXDOMAIN</div><div class="found-p">That error means the domain isn't resolving at all — the problem is DNS, not the server, not the app, not the network path. You just saved yourself from debugging the wrong layer.</div>` },
    dig: { syntax:`dig &lt;domain&gt;`, runs:[
      { cmd:`dig google.com`, output:`;; ANSWER SECTION:\ngoogle.com.   <span class="dim">300</span>  IN  A  <span class="ok">142.250.80.14</span>\n\n;; Query time: 21 msec\n;; SERVER: 8.8.8.8#53(8.8.8.8)`, reading:`300 is the TTL in seconds — how long this answer can be cached before a resolver has to ask again. 21ms is how fast the answer came back.` },
      { cmd:`dig myapp.com`, output:`myapp.com.  <span class="warn">3600</span>  IN  A  93.184.216.34`, reading:`A TTL of 3600 (one hour) means old cached answers can still be handed out for up to an hour after a DNS record changes — exactly why DNS changes never feel instant.` },
      { cmd:`dig myapp.com +short`, output:`<span class="dim">(nothing printed)</span>`, reading:`+short with zero output means this domain has no A record at all right now — a cleaner way to check existence than parsing the full ANSWER SECTION.` }
    ], does:`A more detailed DNS lookup than nslookup — shows the record type, the TTL (how long it's cached for), and exactly which server answered.`, where:`When nslookup's answer isn't enough detail — checking a record's TTL, or confirming which specific DNS server responded.`, breakdown:[{term:`dig`, desc:`Domain Information Groper — the detailed DNS tool`},{term:`A`, desc:`the record type — this one maps a domain straight to an IPv4 address`},{term:`300`, desc:`the TTL in seconds — how long this answer can be cached before asking again`}], whyUseful:`<div class="found-p">You just changed a DNS record and need to know exactly when the change will actually take effect everywhere.</div><div class="found-pre">$ dig myapp.com\nmyapp.com.  <span class="warn">3600</span>  IN  A  93.184.216.34</div><div class="found-p">A TTL of 3600 means old, cached answers can still be handed out for up to an hour — this is exactly why DNS changes don't feel instant, and dig is how you confirm the real cache lifetime.</div>` },
    host: { syntax:`host &lt;domain&gt;`, runs:[
      { cmd:`host google.com`, output:`<span class="ok">google.com has address 142.250.80.14</span>`, reading:`One line, one answer — the fastest of the three DNS tools (nslookup/dig/host) when a script just needs the IP and nothing else.` },
      { cmd:`host github.com`, output:`<span class="ok">github.com has address 140.82.112.3</span>`, reading:`Same one-line shape for a different domain — this consistency is exactly why scripts parse "host" output instead of dig's more verbose format.` },
      { cmd:`host totallyfakehost123.com`, output:`<span class="err">Host totallyfakehost123.com not found: 3(NXDOMAIN)</span>`, reading:`host's error format is plain English ("not found") instead of dig's raw NXDOMAIN flag — same underlying meaning, easier to grep for in a script.` }
    ], does:`The simplest possible DNS lookup — one line, one answer, nothing else.`, where:`Fastest way to grab just an IP from a domain, especially inside a shell script.`, breakdown:[{term:`host`, desc:`the simplest DNS lookup tool`},{term:`google.com`, desc:`the domain to resolve`}], whyUseful:`<div class="found-p">A script needs to confirm three different domains all resolve before continuing a deploy — you don't need dig's full detail, just yes/no and the IP.</div><div class="found-pre">$ host github.com\ngithub.com has address 140.82.112.3</div><div class="found-p">One line in, one line out — the fastest of the three DNS tools when you just need the answer.</div>` },

    ssTuln: { syntax:`ss -tuln`, runs:[
      { cmd:`ss -tuln`, output:`Netid  State    Local Address:Port\ntcp    LISTEN   0.0.0.0:<span class="hi">22</span>\ntcp    LISTEN   0.0.0.0:<span class="hi">80</span>\ntcp    LISTEN   127.0.0.1:<span class="hi">3000</span>`, reading:`0.0.0.0 means reachable from anywhere; 127.0.0.1 means only the machine itself can reach it — port 3000 here is NOT exposed to the outside network at all.` },
      { cmd:`ss -tuln | grep 3000`, output:`<span class="dim">(nothing printed)</span>`, reading:`No output for port 3000 means the app isn't listening there at all — this rules out the network/firewall entirely; the problem is the app itself not starting or not binding.` },
      { cmd:`ss -tuln`, output:`Netid  State    Local Address:Port\ntcp    LISTEN   <span class="ok">0.0.0.0:3000</span>`, reading:`Now bound to 0.0.0.0 instead of 127.0.0.1 — this is exactly the config change (usually a "host" setting) that makes an app reachable from outside the machine.` }
    ], does:`Lists every port this machine is actively listening on, and whether it's reachable from anywhere (0.0.0.0) or only from itself (127.0.0.1).`, where:`Confirming a service actually started and is listening where you expect — one of the very first checks in any "my app isn't reachable" investigation.`, breakdown:[{term:`ss`, desc:`socket statistics — the modern tool for this`},{term:`-t / -u`, desc:`show TCP and UDP sockets`},{term:`-l`, desc:`only LISTENING sockets — services waiting for connections`},{term:`-n`, desc:`show port numbers, not service names — faster and unambiguous`}], whyUseful:`<div class="found-p">You just started a server and a request to it times out — is the app even running, and on the port you think it is?</div><div class="found-pre">$ ss -tuln | grep 3000\n<span class="dim">(nothing printed)</span></div><div class="found-p">No output for port 3000 means the app isn't actually listening there at all — the problem is the app itself, not the network, DNS, or firewall. This single check rules out an entire category of causes in seconds.</div>` },
    lsofPort: { syntax:`lsof -i :&lt;port&gt;`, runs:[
      { cmd:`lsof -i :3000`, output:`COMMAND  PID   USER   NAME\n<span class="ok">node</span>    4821  devops *:3000 (LISTEN)`, reading:`Confirms exactly which process (node, PID 4821) is holding the port — kill 4821 is now a precise action, not a guess.` },
      { cmd:`lsof -i :3000`, output:`<span class="dim">(nothing printed)</span>`, reading:`Empty output means genuinely nothing on this machine is using port 3000 — if an app just failed with "port in use" on this exact port, something else is going on.` },
      { cmd:`lsof -i :3000`, output:`COMMAND  PID   USER   NAME\nnode    4821  devops *:3000 (LISTEN)\n<span class="warn">node    4822  devops *:3000 (LISTEN)</span>`, reading:`Two different PIDs on the exact same port — a leftover process from a crashed restart that never released the port before the new one started.` }
    ], does:`Shows exactly which process — by name and PID — is holding open a specific port.`, where:`"Port already in use" errors, or confirming exactly which app is answering on a port before you kill anything.`, breakdown:[{term:`lsof`, desc:`list open files — sockets count as "files" in Linux`},{term:`-i :3000`, desc:`filter to just this one port`},{term:`4821`, desc:`the process ID — use this with "kill" if you need to stop it`}], whyUseful:`<div class="found-p">You try to start your app and get "Error: port 3000 already in use" — but you don't remember starting anything else.</div><div class="found-pre">$ lsof -i :3000\nnode  4821  devops  *:3000 (LISTEN)</div><div class="found-p">Now you know exactly what's squatting on the port and its PID — <span class="found-code">kill 4821</span> frees it up, instead of guessing.</div>` },

    ssT: { syntax:`ss -t`, runs:[
      { cmd:`ss -t`, output:`State   Local Address:Port     Peer Address:Port\n<span class="ok">ESTAB</span>   192.168.1.100:22        203.0.113.45:51820`, reading:`ESTAB means a real, fully-negotiated TCP connection exists right now on port 22 — proof someone is actually connected via SSH, not just attempting to.` },
      { cmd:`ss -t`, output:`<span class="dim">(nothing printed)</span>`, reading:`Zero established TCP connections at all — nobody is currently connected to anything on this machine over TCP.` },
      { cmd:`ss -t state established`, output:`State   Local Address:Port     Peer Address:Port\nESTAB   192.168.1.100:5432      10.0.4.9:48213\nESTAB   192.168.1.100:22         203.0.113.20:51820`, reading:`Filtering to just "established" state shows two live connections — one to the database port (5432), one SSH — a clean way to audit exactly who/what is actively talking to this machine right now.` }
    ], does:`Shows active TCP connections specifically — who this machine is actually talking to right now, over a reliable, connection-based protocol.`, where:`Confirming an SSH session, a database connection, or an API call is actually established, not just attempted.`, breakdown:[{term:`ss -t`, desc:`TCP sockets only`},{term:`ESTAB`, desc:`the connection is live and fully set up — both sides agreed to talk`}], whyUseful:`<div class="found-p">Someone claims they're connected to your server over SSH right now — you can actually verify that from the server's side.</div><div class="found-pre">$ ss -t\nESTAB  192.168.1.100:22  203.0.113.45:51820</div><div class="found-p">A live, established connection to port 22 — proof the SSH session is real and currently open, not just attempted.</div>` },
    ssU: { syntax:`ss -u`, runs:[
      { cmd:`ss -u`, output:`State    Local Address:Port    Peer Address:Port\n<span class="ok">UNCONN</span>  0.0.0.0:68              0.0.0.0:*`, reading:`UNCONN is completely normal for UDP — there's no handshake or persistent link like TCP's ESTAB, just a socket sitting ready to send or receive.` },
      { cmd:`ss -u | grep :53`, output:`UNCONN  127.0.0.53:53  0.0.0.0:*`, reading:`Port 53 (DNS) showing up here confirms the local DNS resolver is active and listening — a useful check when DNS lookups from this machine seem to be failing.` },
      { cmd:`ss -u | grep :53`, output:`<span class="err">(nothing printed)</span>`, reading:`No UDP socket on 53 at all means the local DNS resolver isn't running — this is the actual root cause if every DNS lookup on this machine is failing.` }
    ], does:`Shows UDP sockets — connectionless traffic where there's no persistent "connection" to display, just a port that's active.`, where:`DNS, DHCP, and other lightweight protocols that don't hold a connection open the way TCP does.`, breakdown:[{term:`ss -u`, desc:`UDP sockets only`},{term:`UNCONN`, desc:`normal for UDP — there's no handshake or persistent link, just a socket ready to send/receive`}], whyUseful:`<div class="found-p">You're debugging why DNS lookups from this machine seem to be failing, and want to confirm the local resolver is even active.</div><div class="found-pre">$ ss -u | grep :53</div><div class="found-p">UDP is genuinely the right tool to check here — DNS runs over UDP specifically because speed matters more than guaranteed delivery for a quick lookup.</div>` },

    curlPlain: { syntax:`curl &lt;url&gt;`, runs:[
      { cmd:`curl localhost:3000`, output:`<span class="ok">Hello from my app!</span>`, reading:`That text coming back is proof the app is alive, listening, and responding — the fastest possible confirmation, straight from the terminal, no browser needed.` },
      { cmd:`curl localhost:3000`, output:`<span class="err">curl: (7) Failed to connect to localhost port 3000: Connection refused</span>`, reading:`"Connection refused" means nothing is listening on this port at all — the app either crashed, never started, or is bound to a different port.` },
      { cmd:`curl google.com`, output:`&lt;!doctype html&gt;\n&lt;html&gt;...&lt;/html&gt;\n<span class="dim">(the full HTML body of the page)</span>`, reading:`curl assumes http:// automatically and prints the ENTIRE response body as raw text — this is exactly what a browser fetches before it renders anything visual.` }
    ], does:`Sends an HTTP GET request and prints the response body straight to your terminal.`, where:`The single most-used networking command in DevOps — testing whether any HTTP endpoint responds at all.`, breakdown:[{term:`curl`, desc:`the tool — makes an HTTP request from the command line`},{term:`google.com`, desc:`the URL — curl assumes http:// if you don't specify`}], whyUseful:`<div class="found-p">You just deployed an app and want to know if it's actually serving requests, without opening a browser.</div><div class="found-pre">$ curl localhost:3000\nHello from my app!</div><div class="found-p">If that text comes back, the app is alive, listening, and responding — the fastest possible confirmation, straight from the terminal.</div>` },
    curlI: { syntax:`curl -I &lt;url&gt;`, runs:[
      { cmd:`curl -I google.com`, output:`<span class="ok">HTTP/1.1 200 OK</span>\ncontent-type: text/html\nserver: gws\ndate: Wed, 12 Aug 2026 14:00:00 GMT`, reading:`-I fetches only headers, not the page body — 200 OK confirms success instantly, without downloading anything behind it.` },
      { cmd:`curl -I https://api.example.com`, output:`<span class="err">HTTP/1.1 503 Service Unavailable</span>\nretry-after: 30`, reading:`503 means the server itself is up but currently can't handle the request — often during a deploy or when it's overloaded. retry-after tells you exactly how long to wait.` },
      { cmd:`curl -I https://api.example.com`, output:`<span class="err">curl: (28) Failed to connect: Connection timed out</span>`, reading:`A timeout (no HTTP response at all) is a different failure than 503 — this means the request never even reached the server, pointing at a network or firewall problem instead.` }
    ], does:`Sends a HEAD request — fetches only the response headers, not the full page body.`, where:`A fast health check on an endpoint, or checking the status code without downloading everything behind it.`, breakdown:[{term:`-I`, desc:`"headers only" — much faster than downloading the whole response`},{term:`HTTP/1.1 200 OK`, desc:`the status line — 200 means success`}], whyUseful:`<div class="found-p">A monitoring script needs to check 50 different services every minute — downloading every full page every time would be slow and wasteful.</div><div class="found-pre">$ curl -I https://api.example.com\nHTTP/1.1 200 OK</div><div class="found-p">Just the status, instantly — this exact pattern is how uptime checks and health monitors work under the hood.</div>` },
    curlV: { syntax:`curl -v &lt;url&gt;`, runs:[
      { cmd:`curl -v google.com`, output:`*   Trying 142.250.80.14:80...\n* Connected to google.com (142.250.80.14) port 80\n<span class="hi">> GET / HTTP/1.1</span>\n<span class="hi">> Host: google.com</span>\n<span class="ok">< HTTP/1.1 200 OK</span>\n< content-type: text/html`, reading:`> lines are what YOUR request sent, < lines are what the SERVER sent back — full visibility into the exchange, not just the final result.` },
      { cmd:`curl -v https://api.example.com`, output:`* Connected to api.example.com (10.0.1.5) port 443\n* TLS handshake, Client hello (1)\n<span class="err">* TLS handshake failed: certificate has expired</span>`, reading:`The TCP connection itself succeeded — the failure is specifically at the TLS/certificate step. A completely different fix (renew the cert) than a network or DNS problem.` },
      { cmd:`curl -v https://totallyfakehost123.com`, output:`<span class="err">* Could not resolve host: totallyfakehost123.com</span>`, reading:`Failing before any "Trying..." line even appears means DNS itself never resolved the hostname — the problem is one layer earlier than a connection or TLS issue.` }
    ], does:`Shows the entire request/response cycle in detail — the DNS lookup, the TCP connection, every header sent and received.`, where:`When curl plain or curl -I isn't enough — debugging exactly where a request is failing (DNS? connection? TLS? the app itself?).`, breakdown:[{term:`-v`, desc:`verbose — show everything happening under the hood`},{term:`&gt; lines`, desc:`what YOUR request actually sent`},{term:`&lt; lines`, desc:`what the SERVER sent back`}], whyUseful:`<div class="found-p">A request is failing and a plain curl just says "connection refused" — not enough detail to know why.</div><div class="found-pre">$ curl -v https://api.example.com\n* Connected to api.example.com...\n* TLS handshake failed</div><div class="found-p">Now you know the TCP connection actually worked, but TLS is the problem specifically — a certificate issue, not a network or DNS one. That's a completely different fix than if the connection itself had failed.</div>` },

    sshKeygen: { syntax:`ssh-keygen`, runs:[
      { cmd:`ssh-keygen -t ed25519`, output:`Generating public/private ed25519 key pair.\nEnter file in which to save the key (/home/you/.ssh/id_ed25519):\nEnter passphrase (empty for no passphrase):\n<span class="ok">Your identification has been saved in /home/you/.ssh/id_ed25519</span>\n<span class="ok">Your public key has been saved in /home/you/.ssh/id_ed25519.pub</span>`, reading:`Two files are created — id_ed25519 (private, NEVER shared) and id_ed25519.pub (public, safe to copy anywhere). Run this once per machine, not once per server.` },
      { cmd:`ssh-keygen -t ed25519`, output:`Enter file in which to save the key (/home/you/.ssh/id_ed25519): <span class="err">/home/you/.ssh/id_ed25519 already exists.\nOverwrite (y/n)? </span>`, reading:`Running it again on a machine that already has a key pair asks before overwriting — a real safeguard, since overwriting would break every server that already trusts the old public key.` },
      { cmd:`ssh-keygen -t ed25519 -f ~/.ssh/id_work -C "work laptop"`, output:`<span class="ok">Your identification has been saved in /home/you/.ssh/id_work</span>`, reading:`-f names the key file explicitly and -C adds a label comment — this is how you generate a SEPARATE, distinctly-named key pair instead of overwriting your default one.` }
    ], does:`Generates a matching pair of keys — a private key that never leaves your machine, and a public key you can safely share.`, where:`Run this once, ever, per machine you SSH from — the foundation every SSH connection and every Git-over-SSH setup is built on.`, breakdown:[{term:`ssh-keygen`, desc:`the key generator`},{term:`-t ed25519`, desc:`the key type — a modern, fast, secure default`},{term:`id_ed25519`, desc:`your PRIVATE key — never share this, ever`},{term:`id_ed25519.pub`, desc:`your PUBLIC key — this is the one you copy to servers`}], whyUseful:`<div class="found-p">Typing a password every single time you SSH into a server gets old fast, and passwords can be guessed or brute-forced.</div><div class="found-pre">$ ssh-keygen -t ed25519\n...\nYour public key has been saved in ~/.ssh/id_ed25519.pub</div><div class="found-p">Put that public key on a server once, and every future connection authenticates automatically and more securely — no password typed, ever again.</div>` },
    sshConnect: { syntax:`ssh &lt;user&gt;@&lt;ip-address&gt;`, runs:[
      { cmd:`ssh devops@203.0.113.45`, output:`<span class="dim">Welcome to Ubuntu 22.04 LTS</span>\n<span class="ok">devops@ip-203-0-113-45:~$</span> <span class="dim">_</span>`, reading:`The prompt itself changes to show the remote hostname — everything typed from here on runs ON that server, not your own laptop.` },
      { cmd:`ssh devops@203.0.113.45`, output:`<span class="err">ssh: connect to host 203.0.113.45 port 22: Connection refused</span>`, reading:`"Refused" means the network path is fine, but nothing is listening on port 22 — the SSH daemon on that server is down, or a firewall is actively rejecting it.` },
      { cmd:`ssh devops@203.0.113.45`, output:`<span class="err">Permission denied (publickey).</span>`, reading:`The server IS reachable and SSH itself is running — but none of your keys are authorized on this account. A completely different problem than a connection failure.` }
    ], does:`Opens a secure, encrypted remote terminal session on another machine.`, where:`How you actually get onto a real cloud server to run any other command in this tab — nothing else here works until you're on the box.`, breakdown:[{term:`ssh`, desc:`the client — opens a secure remote session`},{term:`devops`, desc:`the username to log in as`},{term:`203.0.113.45`, desc:`the server's IP — its public one, since you're connecting from outside`}], whyUseful:`<div class="found-p">You just launched a cloud server (see the "Build a lab" below) and need to actually get onto it to install anything.</div><div class="found-pre">$ ssh devops@203.0.113.45\nWelcome to Ubuntu 22.04 LTS\ndevops@ip-203-0-113-45:~$</div><div class="found-p">You're now typing commands that run ON that remote server, not your own laptop — this is the line between "reading about a server" and "actually operating one."</div>` },
    scpCopy: { syntax:`scp &lt;file&gt; &lt;user&gt;@&lt;ip-address&gt;:&lt;path&gt;`, runs:[
      { cmd:`scp app.tar.gz devops@203.0.113.45:/home/devops`, output:`app.tar.gz    100%   14MB   8.2MB/s   00:01\n<span class="ok">✓ transfer complete</span>`, reading:`Same encrypted connection as SSH, just moving a file instead of opening a shell — the progress bar confirms exactly how much transferred and how fast.` },
      { cmd:`scp devops@203.0.113.45:/var/log/app.log ./app.log`, output:`app.log    100%   2.1MB  5.4MB/s   00:00\n<span class="ok">✓ downloaded to current directory</span>`, reading:`Reversing the order — remote path first, then local path — pulls a file FROM the server instead of pushing one to it. Same command, opposite direction.` },
      { cmd:`scp app.tar.gz devops@203.0.113.45:/home/devops`, output:`<span class="err">scp: /home/devops/app.tar.gz: Permission denied</span>`, reading:`The connection and login both succeeded — the failure is specifically a filesystem permission on the destination path, not a network or auth problem.` }
    ], does:`Securely copies a file from your machine to a remote server (or the other way around), reusing the exact same encrypted connection as SSH.`, where:`Getting a build artifact, a config file, or a backup onto or off of a server, without setting up any separate file-transfer tool.`, breakdown:[{term:`scp`, desc:`secure copy`},{term:`app.tar.gz`, desc:`the local file being sent`},{term:`devops@203.0.113.45:/home/devops`, desc:`where it lands — same user@host as ssh, plus a destination path`}], whyUseful:`<div class="found-p">You built a deployable app locally and need it on the actual server, without setting up Git or a CI pipeline just for a quick manual test.</div><div class="found-pre">$ scp app.tar.gz devops@203.0.113.45:/home/devops\napp.tar.gz  100%  14MB  8.2MB/s  00:01</div><div class="found-p">One command, and the file is on the server, ready to unpack and run — the same trust and encryption as SSH, just moving a file instead of opening a shell.</div>` },

    useraddExpireNet: { syntax:`useradd -e &lt;YYYY-MM-DD&gt; &lt;username&gt;`, runs:[
      { cmd:`sudo useradd -e 2026-12-31 contractor_mike
echo $?`, output:`<span class="ok">0</span>`, reading:`useradd prints nothing on success — silence is the signal. This account can now authenticate over SSH like anyone else, but only until the date you just set.` },
      { cmd:`ssh contractor_mike@203.0.113.45`, output:`<span class="err">Your account has expired; please contact your system administrator\nConnection closed by 203.0.113.45 port 22</span>`, reading:`The password/key are still technically correct — the SERVER itself refuses the login because the account expired. Access control enforced without touching a single firewall rule.` },
      { cmd:`ssh sarah_devops@203.0.113.45`, output:`<span class="ok">Welcome to Ubuntu 22.04 LTS</span>`, reading:`Everyone else on the same server, on the same network, logs in completely normally — -e only ever affects the one account it was specifically set on.` }
    ], does:`Creates an account whose network access (SSH, or any other login method) automatically stops working after a set date — enforced by the server itself, not by any firewall rule.`, where:`Time-boxed remote access — a contractor, an auditor, a temporary support engineer — where you want the access to genuinely expire, not just rely on someone remembering to revoke it.`, breakdown:[{term:`useradd -e &lt;YYYY-MM-DD&gt;`, desc:`account-level expiration — the server itself refuses login after this date`},{term:`contractor_mike`, desc:`the account this specifically applies to`}], whyUseful:`<div class="found-p">A contractor needs SSH access to a production server for exactly one month — and "remember to revoke their access later" is precisely the kind of task that slips through the cracks.</div><div class="found-pre">$ sudo useradd -e 2026-12-31 contractor_mike</div><div class="found-p">No firewall rule to remember, no calendar reminder — the network access itself stops working on the date you set, automatically, the moment they try to log in after it.</div>` },
    chageListNet: { syntax:`chage -l &lt;username&gt;`, runs:[
      { cmd:`chage -l contractor_mike`, output:`Account expires : <span class="warn">Dec 31, 2026</span>`, reading:`This is the exact date network access will stop working for this account — confirmed straight from the server, not from anyone's memory of what was configured.` },
      { cmd:`chage -l sarah_devops`, output:`Account expires : <span class="ok">never</span>`, reading:`"never" means this account's network access has no built-in end date at all — it stays valid until someone manually disables it.` },
      { cmd:`for u in contractor_mike sarah_devops tony_ops; do
  echo "$u:"; chage -l $u | grep "Account expires"
done`, output:`contractor_mike:\nAccount expires : <span class="warn">Dec 31, 2026</span>\nsarah_devops:\nAccount expires : <span class="ok">never</span>\ntony_ops:\nAccount expires : <span class="ok">never</span>`, reading:`Looping chage -l over every account is exactly how you'd answer "which of these accounts actually have time-boxed network access?" during a real security review.` }
    ], does:`Reports whether an account's network access has an expiration date, and exactly when — read straight from the server being audited.`, where:`Security reviews and access audits — confirming which accounts on a server have genuinely time-boxed access, and which ones don't expire at all.`, breakdown:[{term:`chage -l`, desc:`list current account aging/expiration settings`},{term:`&lt;username&gt;`, desc:`checked against this specific server`}], whyUseful:`<div class="found-p">A security audit asks exactly one question: "of everyone who can currently SSH into this server, whose access is set to expire, and whose isn't?"</div><div class="found-pre">$ chage -l contractor_mike
Account expires : Dec 31, 2026</div><div class="found-p">One command per account gives a definite answer — no guessing based on who you remember was supposed to be temporary.</div>` },

    ufwStatus: { syntax:`sudo ufw status`, runs:[
      { cmd:`sudo ufw status`, output:`Status: <span class="ok">active</span>\n\nTo                         Action      From\n--                         ------      ----\n22/tcp                     ALLOW       Anywhere\n80/tcp                     ALLOW       Anywhere`, reading:`The firewall is on, and SSH (22) plus HTTP (80) are both explicitly allowed — everything else is blocked by default.` },
      { cmd:`sudo ufw status`, output:`Status: <span class="err">inactive</span>`, reading:`Inactive means ufw is doing absolutely nothing right now — every port is reachable, or blocked, based on whatever else is configured (cloud security groups, iptables directly) — not this firewall at all.` },
      { cmd:`sudo ufw status`, output:`Status: active\n\nTo                         Action      From\n--                         ------      ----\n22/tcp                     ALLOW       Anywhere\n<span class="err">(port 3000 is not listed at all)</span>`, reading:`Your app is running (confirmed with ss -tuln) but port 3000 isn't in the allowed list — that's the actual problem, confirmed here before wasting time debugging the app itself.` }
    ], does:`Shows whether the firewall is even turned on, and exactly which rules are currently active.`, where:`Always the first command to run when something "should" be reachable but isn't — confirming whether the firewall is the culprit.`, breakdown:[{term:`ufw`, desc:`Uncomplicated Firewall — a friendly frontend over Linux's real firewall`},{term:`status`, desc:`show current state and rules`},{term:`22/tcp ALLOW Anywhere`, desc:`SSH is allowed in from any source`}], whyUseful:`<div class="found-p">Your app is running (confirmed with ss -tuln) but nobody outside the server can reach it — the firewall is a prime suspect.</div><div class="found-pre">$ sudo ufw status\n22/tcp   ALLOW   Anywhere\n<span class="dim">(port 3000 is not listed at all)</span></div><div class="found-p">Port 3000 isn't in the allowed list — that's the actual problem, confirmed in one command, before you waste time debugging the app itself.</div>` },
    ufwAllow80: { syntax:`sudo ufw allow &lt;port&gt;`, runs:[
      { cmd:`sudo ufw allow 80`, output:`<span class="ok">Rule added</span>\n<span class="ok">Rule added (v6)</span>`, reading:`One rule added for both IPv4 and IPv6 — port 80 (HTTP) is now reachable from anywhere.` },
      { cmd:`sudo ufw allow 80
sudo ufw status`, output:`80/tcp                     <span class="ok">ALLOW</span>       Anywhere`, reading:`Checking status right after confirms the rule actually took effect — a good habit instead of assuming the "Rule added" message means it's live.` },
      { cmd:`sudo ufw allow from 203.0.113.0/24 to any port 80`, output:`<span class="ok">Rule added</span>`, reading:`Adding a source range restricts port 80 to only that specific network block, instead of "Anywhere" — a tighter, more deliberate rule than the plain version above.` }
    ], does:`Adds a rule allowing inbound traffic on this port, for both IPv4 and IPv6.`, where:`Opening up exactly the port a web server needs — HTTP traffic — nothing more, nothing less.`, breakdown:[{term:`ufw allow`, desc:`add an ALLOW rule`},{term:`80`, desc:`the port — HTTP's standard port`}], whyUseful:`<div class="found-p">You just installed Nginx (see the Reverse Proxy section below), but the firewall is still blocking regular web traffic from reaching it.</div><div class="found-pre">$ sudo ufw allow 80\nRule added</div><div class="found-p">Now anyone on the internet can actually reach port 80 — one command, and the exact gap found with "ufw status" is closed.</div>` },
    ufwAllow443: { syntax:`sudo ufw allow &lt;port&gt;`, runs:[
      { cmd:`sudo ufw allow 443`, output:`<span class="ok">Rule added</span>\n<span class="ok">Rule added (v6)</span>`, reading:`Port 80 being open doesn't automatically open 443 too — they're two separate rules for two separate ports, and this is the one that handles encrypted HTTPS traffic.` },
      { cmd:`curl https://mysite.com`, output:`<span class="err">curl: (28) Connection timed out</span>`, reading:`http:// works fine but https:// times out completely — a very common, very specific symptom of forgetting this exact rule.` },
      { cmd:`sudo ufw allow 443
curl https://mysite.com`, output:`<span class="ok">HTTP/1.1 200 OK</span>`, reading:`Same site, same server — adding the missing rule alone fixed it. Nothing about the app or its TLS certificate needed to change at all.` }
    ], does:`Same idea as allowing port 80, but for encrypted HTTPS traffic.`, where:`Any real production website — HTTPS is the default expectation today, not an extra.`, breakdown:[{term:`443`, desc:`the port — HTTPS's standard port, encrypted web traffic`}], whyUseful:`<div class="found-p">A site works fine over plain http:// but https:// times out completely — a very common, very specific symptom.</div><div class="found-pre">$ sudo ufw allow 443\nRule added</div><div class="found-p">Port 80 being open doesn't automatically open 443 too — they're two separate rules for two separate ports, and this is the one that was still missing.</div>` },

    ipRoute: { syntax:`ip route`, runs:[
      { cmd:`ip route`, output:`default via <span class="hi">192.168.1.1</span> dev eth0\n192.168.1.0/24 dev eth0 scope link src 192.168.1.100`, reading:`"default via" is the gateway — where ANY traffic goes if no more specific route matches, which is almost everything bound for outside the local network.` },
      { cmd:`ip route`, output:`192.168.1.0/24 dev eth0 scope link src 192.168.1.100\n<span class="err">(no "default via" line at all)</span>`, reading:`No default route means this machine can reach other devices on its own local network fine, but has genuinely no idea where to send traffic bound for the internet — the real root cause, not DNS or the firewall.` },
      { cmd:`sudo ip route add default via 192.168.1.1
ip route`, output:`<span class="ok">default via 192.168.1.1 dev eth0</span>\n192.168.1.0/24 dev eth0 scope link src 192.168.1.100`, reading:`Manually adding the missing default route immediately fixes internet-bound traffic — proof the routing table itself, not any app or DNS setting, was the actual gap.` }
    ], does:`Shows this machine's routing table — where it sends traffic depending on the destination, and critically, its default gateway.`, where:`Confirming a machine actually knows how to reach the internet at all, before blaming DNS or a firewall for a connectivity issue.`, breakdown:[{term:`default via 192.168.1.1`, desc:`the default gateway — where ANY traffic goes if no more specific route matches (almost everything)`},{term:`192.168.1.0/24 dev eth0`, desc:`traffic to other machines on this same local network goes straight out eth0, no gateway needed`}], whyUseful:`<div class="found-p">A server can reach other machines on its own local network fine, but can't reach the internet at all.</div><div class="found-pre">$ ip route\n192.168.1.0/24 dev eth0\n<span class="dim">(no "default via" line at all)</span></div><div class="found-p">No default route means the machine genuinely has no idea where to send traffic bound for anywhere outside its local network — that's the actual root cause, not DNS, not the firewall.</div>` },
    traceroute: { syntax:`traceroute &lt;host&gt;`, runs:[
      { cmd:`traceroute google.com`, output:` 1  192.168.1.1        1.1 ms\n 2  isp-edge-router     8.3 ms\n 3  <span class="warn">* * * (timeout)</span>\n 4  142.250.80.14      40.2 ms`, reading:`Reached the destination at hop 4 despite hop 3 timing out — a quiet router that doesn't reply is common and not itself a problem, since the path still completes.` },
      { cmd:`traceroute internal-db.local`, output:` 1  192.168.1.1        1.0 ms\n 2  10.0.0.1            4.2 ms\n 3  * * *\n 4  * * *\n 5  * * *\n<span class="err">↳ never reaches the destination</span>`, reading:`Every hop after #2 times out and the trace never arrives — this is a genuinely broken path, not one quiet router. Something between hop 2 and the destination is actually down.` },
      { cmd:`traceroute myserver.com`, output:` 1  1.1 ms\n 2  8.3 ms\n 3  <span class="err">210 ms  ← huge jump here</span>\n 4  212 ms`, reading:`The delay appears at hop 3 and never recovers — that's specifically where the slowdown is, information a plain ping alone could never give you.` }
    ], does:`Shows every network hop between you and a destination, and how long each one takes — not just whether you got there, but the exact path.`, where:`When ping or curl fails and you need to know WHERE along the way things break down, not just that they did.`, breakdown:[{term:`traceroute`, desc:`traces the path, hop by hop`},{term:`1.1 ms / 8.3 ms`, desc:`round-trip time to each hop — rising numbers are normal as you get farther away`},{term:`* * * (timeout)`, desc:`one hop didn't respond — often normal (some routers hide themselves), but a good clue if everything after it also fails`}], whyUseful:`<div class="found-p">A connection to a server is slow, and you need to know if it's your network, your ISP, or the destination that's the actual bottleneck.</div><div class="found-pre">$ traceroute myserver.com\n1  1.1ms\n2  8.3ms\n3  210ms  ← huge jump here\n4  212ms</div><div class="found-pre">The delay appears at hop 3 and never recovers — that's specifically where the slowdown is happening, information a plain ping could never give you.</div>` },

    nginxInstall: { syntax:`sudo apt install nginx`, runs:[
      { cmd:`sudo apt install nginx
curl localhost`, output:`Reading package lists... Done\nSetting up nginx...\n<span class="ok">nginx is now running</span>\n\n&lt;h1&gt;Welcome to nginx!&lt;/h1&gt;`, reading:`The default "Welcome to nginx!" page confirms two things at once: it installed successfully, AND it's already running and listening on port 80.` },
      { cmd:`sudo systemctl status nginx`, output:`● nginx.service - A high performance web server\n   Active: <span class="ok">active (running)</span>`, reading:`Nginx installs itself as a systemd service and starts automatically — no extra step needed to have it running after install or after a reboot.` },
      { cmd:`sudo apt install nginx`, output:`<span class="warn">nginx is already the newest version (1.24.0-2ubuntu1).\n0 upgraded, 0 newly installed</span>`, reading:`Running install again when it's already there is completely safe — apt just confirms nothing needs to change instead of erroring or reinstalling.` }
    ], does:`Installs and starts Nginx, a web server that's also the standard tool DevOps uses as a reverse proxy — a "front door" that sits in front of your actual app.`, where:`The very first step before Nginx can do anything for you — proxy traffic, load balance, serve static files, terminate HTTPS.`, breakdown:[{term:`apt install nginx`, desc:`installs Nginx from the system's package manager`},{term:`Welcome to nginx!`, desc:`its default page — confirms it installed AND is already running, listening on port 80`}], whyUseful:`<div class="found-p">Your Node app runs fine on port 3000, but you don't want users typing ":3000" into a URL, and you eventually want HTTPS — a raw Node server doesn't handle that well on its own.</div><div class="found-pre">$ sudo apt install nginx\n$ curl localhost\n&lt;h1&gt;Welcome to nginx!&lt;/h1&gt;</div><div class="found-p">Nginx is now running on port 80, ready to be pointed at your actual app — the next pill below is exactly that.</div>` },
    nginxConfig: { syntax:`server { listen 80; location / { proxy_pass &lt;url&gt;; } }`, runs:[
      { cmd:`cat /etc/nginx/sites-available/default`, output:`server {\n  listen <span class="v">80</span>;\n  location / {\n    proxy_pass <span class="s">http://localhost:3000</span>;\n  }\n}`, reading:`"listen 80" accepts incoming web traffic, and "proxy_pass" quietly forwards it to the real app on port 3000 — the browser only ever sees Nginx.` },
      { cmd:`sudo systemctl reload nginx
curl localhost`, output:`<span class="ok">✓ nginx reloaded</span>\nHello from my Node app!`, reading:`Reload applies a config change WITHOUT dropping active connections (unlike a full restart) — and curl confirms traffic is actually reaching the real app through Nginx now.` },
      { cmd:`sudo nginx -t`, output:`<span class="err">nginx: [emerg] unexpected "}" in /etc/nginx/sites-available/default:5\nnginx: configuration file test failed</span>`, reading:`-t tests the config for syntax errors BEFORE reloading — catching a stray brace here means nginx never actually goes down from a bad config in production.` }
    ], does:`Tells Nginx: "when a request comes in on port 80, quietly forward it to my actual app running on port 3000, and hand the response back."`, where:`This exact block is what makes reverse proxying real — the browser only ever sees Nginx, never your app's real port.`, breakdown:[{term:`listen 80`, desc:`accept incoming connections on the standard web port`},{term:`location /`, desc:`applies to every URL path, unless a more specific location block overrides it`},{term:`proxy_pass http://localhost:3000`, desc:`forward the request here — your app, running locally, on its own port`}], whyUseful:`<div class="found-p">A user visits your-site.com (port 80, no port number needed), but the actual app only knows how to listen on port 3000.</div><div class="found-pre">Browser → your-site.com  (port 80)\n            ↓ Nginx quietly forwards it\n         localhost:3000  (your real app)</div><div class="found-p">The user never sees ":3000" anywhere, and later, adding HTTPS or swapping the app underneath means changing this one config file — not anything the user-facing URL depends on.</div>` },

    nginxUpstream: { syntax:`upstream backend { server &lt;ip&gt;:3000; server &lt;ip&gt;:3001; }`, runs:[
      { cmd:`cat /etc/nginx/sites-available/default`, output:`upstream backend {\n  server <span class="s">localhost:3000</span>;\n  server <span class="s">localhost:3001</span>;\n}\nserver {\n  listen 80;\n  location / { proxy_pass <span class="s">http://backend</span>; }\n}`, reading:`proxy_pass now points at the named GROUP ("backend"), not one single instance — Nginx picks one of the two servers for each incoming request.` },
      { cmd:`curl localhost
curl localhost`, output:`Hello from server on <span class="hi">3000</span>\nHello from server on <span class="hi">3001</span>`, reading:`Two back-to-back requests landed on two DIFFERENT backend instances — this is load balancing actually happening, spreading traffic instead of hammering one process.` },
      { cmd:`sudo systemctl stop app-on-3001
curl localhost
curl localhost`, output:`Hello from server on <span class="ok">3000</span>\nHello from server on <span class="ok">3000</span>`, reading:`With one backend stopped, Nginx quietly routes every request to the remaining healthy one — the site stays up even though half the capacity just disappeared.` }
    ], does:`Instead of forwarding to one single app, Nginx now spreads requests across a whole list of them — this is load balancing, and it's a small addition to the exact same reverse proxy config.`, where:`Running the same app on two or more ports (or servers) so that no single instance carries all the traffic — and so if one goes down, the other keeps serving.`, breakdown:[{term:`upstream backend { ... }`, desc:`defines a named group of servers to choose between`},{term:`server localhost:3000 / :3001`, desc:`each one a separate running copy of the exact same app`},{term:`proxy_pass http://backend`, desc:`now points at the GROUP, not one single instance — Nginx picks one for each request`}], whyUseful:`<div class="found-p">One instance of your app can only handle so much traffic — and if that one instance crashes, the whole site goes down with it.</div><div class="found-pre">Users → Nginx → 3000\n              → 3001</div><div class="found-p">Two independent copies of the same app, and Nginx quietly spreads requests between them — more capacity, and if one dies, the other keeps the site up. This is genuinely what "high availability" means in practice.</div>` },

    curlApi: { syntax:`curl &lt;api-url&gt;`, runs:[
      { cmd:`curl https://api.example.com/users/1`, output:`{"id":1,"name":"Tony Stark","email":"tony@example.com"}`, reading:`Same tool as every other curl command in this tab — an API is just an HTTP endpoint, and this is the raw, unfiltered response with nothing in between.` },
      { cmd:`curl https://api.example.com/users/999`, output:`<span class="err">HTTP/1.1 404 Not Found</span>\n{"error":"user not found"}`, reading:`404 plus a JSON error body is the API explicitly telling you this specific resource doesn't exist — a very different problem than a timeout or 500.` },
      { cmd:`curl https://api.example.com/orders`, output:`<span class="err">HTTP/1.1 401 Unauthorized</span>\n{"error":"missing or invalid token"}`, reading:`401 means the request reached the API fine, but wasn't authenticated — the next step is adding an Authorization header, not debugging the network.` }
    ], does:`Calls a REST API exactly like a browser or an app would — sends a GET request, gets JSON back as plain text.`, where:`Testing any API — your own, or a third-party one — without writing any code just to see what it returns.`, breakdown:[{term:`curl`, desc:`same tool as every other curl command in this tab — an API is just an HTTP endpoint`},{term:`/posts/1`, desc:`the specific resource being requested`},{term:`{"userId":1, ...}`, desc:`the response body — JSON, a plain-text way of representing structured data`}], whyUseful:`<div class="found-p">A frontend developer says "the API is returning weird data" and you need to see exactly what it actually sends back, with nothing in between.</div><div class="found-pre">$ curl https://api.example.com/users/1\n{"id":1,"name":"..."}</div><div class="found-p">The raw, unfiltered response — no app code, no framework, no possible frontend bug in the way. If it's wrong here, the problem is the API itself.</div>` },
    curlJq: { syntax:`curl &lt;api-url&gt; | jq`, runs:[
      { cmd:`curl https://api.example.com/users/1 | jq`, output:`{\n  "id": 1,\n  "name": "Tony Stark",\n  "email": "tony@example.com"\n}`, reading:`Same exact data as plain curl, just indented and colorized — instantly scannable instead of one dense unreadable line.` },
      { cmd:`curl https://api.example.com/users/1 | jq '.name'`, output:`<span class="ok">"Tony Stark"</span>`, reading:`jq can also extract just ONE field by path — no need to eyeball the whole response when a script only cares about a single value.` },
      { cmd:`curl https://api.example.com/users/1 | jq '.name'`, output:`<span class="err">parse error: Invalid numeric literal at line 1, column 8</span>`, reading:`jq failed to parse the response as JSON at all — this usually means the API actually returned an HTML error page (like a 502 from a load balancer), not real JSON.` }
    ], does:`Pretty-prints raw JSON — same data as plain curl, but indented, colored, and actually readable.`, where:`Any time an API response is more than a couple of fields — raw JSON on one line is genuinely unreadable past a certain size.`, breakdown:[{term:`|`, desc:`the pipe — sends curl's raw output straight into jq instead of printing it directly`},{term:`jq`, desc:`a dedicated JSON formatter/query tool`}], whyUseful:`<div class="found-p">An API response comes back as one dense, unreadable wall of text — spotting a single wrong field in it by eye is nearly impossible.</div><div class="found-pre">$ curl .../posts/1\n{"userId":1,"id":1,"title":"...", ...}\n\n$ curl .../posts/1 | jq\n{\n  "userId": 1,\n  "id": 1,\n  ...\n}</div><div class="found-p">Same exact data, instantly scannable — this one habit alone makes debugging any API dramatically less painful.</div>` }
  };

  function runNetDevopsCmd(key, btn) {
    const d = NETDEVOPS_CMDS[key];
    if (!d) return;
    const runsArea = document.getElementById('ndRunsArea');
    if (d.runs && d.runs.length) {
      renderCmdRuns(d.runs, runsArea);
    } else {
      // legacy shape — single cmd/output pair, not yet migrated to runs:[]
      const lines = d.cmd.split('\n');
      let extra = '';
      if (lines.length > 1) {
        extra = lines.slice(1).map(l => '<span class="ld-prompt">devops@server:~$</span> ' + l).join('\n') + '\n';
      }
      renderCmdRuns([{ cmd: lines[0], output: extra + d.output }], runsArea);
    }
    document.getElementById('ndSyntax').innerHTML = d.syntax || (d.runs ? d.runs[0].cmd.split('\n')[0] : d.cmd.split('\n')[0]);
    document.getElementById('ndDoes').innerHTML = d.does;
    document.getElementById('ndWhere').innerHTML = d.where;
    const bdList = document.getElementById('ndBreakdownList');
    if (bdList) {
      bdList.innerHTML = (d.breakdown && d.breakdown.length)
        ? d.breakdown.map(b => `<div class="sl-breakdown-item"><span class="sl-breakdown-term">${b.term}</span><span class="sl-breakdown-desc">${b.desc}</span></div>`).join('')
        : '<span class="dim">No further breakdown needed for this one.</span>';
    }
    const whyEl = document.getElementById('ndWhyUseful');
    if (whyEl) whyEl.innerHTML = d.whyUseful || '<span class="dim">—</span>';
    document.querySelectorAll('#tab-networkingdevops .ld-pill').forEach(p => p.classList.remove('active'));
    if (btn) btn.classList.add('active');
  }
