  /* ============ NETWORKING — mini terminal simulator, same pattern
     as runLinuxCmd but targeting its own net* element ids so the two
     tabs' simulators never interfere with each other. ============ */
  const NETWORK_CMDS = {
    ping: { syntax:`ping -c &lt;count&gt; &lt;host&gt;`, cmd:`ping -c 4 google.com`, output:`64 bytes from google.com: icmp_seq=1 time=11.2 ms\n64 bytes from google.com: icmp_seq=2 time=10.8 ms\n64 bytes from google.com: icmp_seq=3 time=11.5 ms\n64 bytes from google.com: icmp_seq=4 time=10.9 ms\n<span class="ok">4 packets transmitted, 4 received, 0% packet loss</span>`, does:`Sends ICMP echo requests and reports whether — and how fast — the host responds.`, where:`The cheapest first check for "is this thing even reachable at all" before debugging anything more specific.` },
    curlHead: { syntax:`curl -I &lt;url&gt;`, cmd:`curl -I https://api.example.com`, output:`<span class="ok">HTTP/1.1 200 OK</span>\ncontent-type: application/json\nx-response-time: 12ms`, does:`Sends a HEAD request — fetches only the response headers, not the body.`, where:`A fast health check on an endpoint without downloading the whole page.` },
    curlVerbose: { syntax:`curl -v &lt;url&gt;`, cmd:`curl -v https://api.example.com/health`, output:`* Connected to api.example.com (10.0.1.5) port 443\n* TLS handshake, Client hello (1)\n* TLS handshake, Server hello (2)\n<span class="hi">> GET /health HTTP/1.1</span>\n<span class="hi">> Host: api.example.com</span>\n<span class="ok">< HTTP/1.1 200 OK</span>`, does:`Shows the entire request/response cycle, including the TLS handshake — not just the final result.`, where:`Debugging at the protocol level when a plain curl's error message alone isn't enough to explain what's happening.` },
    wget: { syntax:`wget &lt;url&gt;`, cmd:`wget https://example.com/release.tar.gz`, output:`Saving to: 'release.tar.gz'\nrelease.tar.gz   100%[==================>]  14.2M  8.1MB/s\n<span class="ok">'release.tar.gz' saved</span>`, does:`Downloads a file from a URL straight to disk.`, where:`Pulling a release artifact onto a server that doesn't have — and doesn't need — a browser.` },
    mtr: { syntax:`mtr &lt;host&gt;`, cmd:`mtr google.com`, output:`HOST                    Loss%   Avg\n1. gateway                0.0%   0.8ms\n2. isp-edge-router        0.0%   4.2ms\n3. transit-hop-7          <span class="warn">2.0%</span>   9.1ms\n4. google-edge             0.0%  11.4ms`, does:`Combines ping and traceroute, continuously — shows live loss % and latency at every hop, not just one snapshot.`, where:`Finding exactly which hop along a route is dropping packets or adding latency, when a one-shot traceroute isn't conclusive.` },
    telnet: { syntax:`telnet &lt;host&gt; &lt;port&gt;`, cmd:`telnet db.internal 5432`, output:`Trying 10.0.1.20...\n<span class="ok">Connected to db.internal.</span>`, does:`Opens a raw TCP connection to a specific port — legacy tool, but still works for a quick reachability test.`, where:`Same use case as nc -zv — confirming a port is open, though nc is the more modern choice today.` },
    dig: { syntax:`dig &lt;domain&gt;`, cmd:`dig example.com`, output:`;; ANSWER SECTION:\nexample.com.  3600  IN  A  <span class="ok">93.184.216.34</span>\n\n;; Query time: 24 msec\n;; SERVER: 8.8.8.8#53`, does:`Runs a detailed DNS query and shows the resolved record, TTL, and which server answered.`, where:`The standard tool for "is DNS actually resolving this correctly" — more detail than nslookup.` },
    digTrace: { syntax:`dig +trace &lt;domain&gt;`, cmd:`dig +trace example.com`, output:`. 518400 IN NS a.root-servers.net.\ncom. 172800 IN NS a.gtld-servers.net.\nexample.com. 172800 IN NS ns1.example.com.\n<span class="ok">example.com. 3600 IN A 93.184.216.34</span>`, does:`Traces the FULL DNS resolution path step by step — root servers, then TLD servers, then the authoritative nameserver.`, where:`Debugging delegation issues — e.g. "why isn't my new nameserver being used yet."` },
    nslookup: { syntax:`nslookup &lt;domain&gt;`, cmd:`nslookup example.com`, output:`Server:    8.8.8.8\nAddress:   8.8.8.8#53\n\nName:   example.com\n<span class="ok">Address: 93.184.216.34</span>`, does:`A simpler, older DNS lookup tool than dig.`, where:`Quick DNS checks — also the tool most commonly available by default on Windows.` },
    host: { syntax:`host &lt;domain&gt;`, cmd:`host example.com`, output:`<span class="ok">example.com has address 93.184.216.34</span>`, does:`The simplest possible one-line DNS lookup.`, where:`Fastest way to grab just an IP from a hostname inside a shell script.` },
    resolvConf: { syntax:`cat /etc/resolv.conf`, cmd:`cat /etc/resolv.conf`, output:`nameserver 8.8.8.8\nnameserver 8.8.4.4`, does:`Shows which DNS servers this machine is actually configured to query.`, where:`Debugging "DNS lookups are slow or failing" — confirm the resolver itself before blaming anything else.` },
    etcHosts: { syntax:`cat /etc/hosts`, cmd:`cat /etc/hosts`, output:`127.0.0.1   localhost\n10.0.1.5    api.internal`, does:`Shows manual hostname-to-IP overrides that bypass DNS entirely for this one machine.`, where:`The classic gotcha — a stale /etc/hosts entry can make a domain resolve "wrong" even though DNS itself is perfectly fine.` },
    ssTulpn: { syntax:`ss -tulpn`, cmd:`ss -tulpn`, output:`Proto  Local Address:Port   Process\ntcp    0.0.0.0:3000        node (pid 4821)\ntcp    127.0.0.1:5432       postgres (pid 990)`, does:`Lists every listening socket and exactly which process owns it.`, where:`The first command for "what's actually listening on this server" — port conflicts, misconfigured binds.` },
    netstat: { syntax:`netstat -tlnp`, cmd:`netstat -tlnp`, output:`Proto  Local Address    PID/Program\ntcp    0.0.0.0:3000     4821/node\ntcp    127.0.0.1:5432   990/postgres`, does:`The older, legacy equivalent of ss — same idea, different tool.`, where:`Still shows up in older systems and documentation — worth recognizing even though ss is preferred now.` },
    lsofPort: { syntax:`lsof -i :&lt;port&gt;`, cmd:`lsof -i :443`, output:`COMMAND  PID   USER   NAME\nnginx    990   root   *:https (LISTEN)`, does:`Shows exactly which process is holding open a specific port.`, where:`"Port already in use" errors — reveals exactly what's already there.` },
    ncZv: { syntax:`nc -zv &lt;host&gt; &lt;port&gt;`, cmd:`nc -zv payment-api.internal 8443`, output:`<span class="ok">Connection to payment-api.internal 8443 port [tcp/*] succeeded!</span>`, does:`Tests whether a specific port is reachable, without doing a full protocol handshake.`, where:`Confirming the network/firewall path is open before debugging the application layer on top of it.` },
    ipAddr: { syntax:`ip addr show`, cmd:`ip addr show`, output:`eth0: <span class="ok">inet 10.0.1.42/24</span> brd 10.0.1.255 scope global`, does:`Shows every network interface and its assigned IP address(es).`, where:`"What's this server's actual IP" — the modern replacement for ifconfig.` },
    ipRoute: { syntax:`ip route show`, cmd:`ip route show`, output:`<span class="ok">default via 10.0.0.1 dev eth0</span>\n10.0.1.0/24 dev eth0 proto kernel`, does:`Shows the routing table — where traffic goes by default and for specific subnets.`, where:`Diagnosing "can reach some hosts but not others" — a missing or wrong route is often the cause.` },
    ipLink: { syntax:`ip link show`, cmd:`ip link show`, output:`2: eth0: &lt;BROADCAST,MULTICAST,<span class="ok">UP</span>,LOWER_UP&gt; mtu 1500`, does:`Shows network interfaces and whether they're physically/logically up.`, where:`Confirming an interface isn't simply down before debugging anything further up the stack.` },
    hostnameI: { syntax:`hostname -I`, cmd:`hostname -I`, output:`<span class="ok">10.0.1.42</span>`, does:`The fastest one-line way to get this machine's own IP address(es).`, where:`Grabbing a server's IP quickly inside a script, without parsing ip addr's fuller output.` },
    ifconfig: { syntax:`ifconfig`, cmd:`ifconfig`, output:`eth0: flags=4163&lt;UP,BROADCAST,RUNNING&gt;\n      inet <span class="ok">10.0.1.42</span>  netmask 255.255.255.0`, does:`The legacy tool that ip addr replaced — same basic information, older format.`, where:`Still shows up on older systems and in a lot of existing documentation — worth recognizing.` },
    routeN: { syntax:`route -n`, cmd:`route -n`, output:`Destination   Gateway      Genmask\n0.0.0.0       <span class="ok">10.0.0.1</span>     0.0.0.0`, does:`The older equivalent of ip route show.`, where:`Legacy systems that still expect the old net-tools package instead of iproute2.` },
    opensslConnect: { syntax:`openssl s_client -connect &lt;host&gt;:443`, cmd:`openssl s_client -connect example.com:443`, output:`CONNECTED(00000003)\nsubject=CN = example.com\nissuer=CN = R3\n<span class="ok">Verify return code: 0 (ok)</span>`, does:`Manually performs a TLS handshake and shows the full certificate chain.`, where:`Debugging TLS/certificate issues at the lowest possible level, when curl's own error message isn't detailed enough.` },
    opensslX509: { syntax:`openssl x509 -in &lt;cert&gt; -text -noout`, cmd:`openssl x509 -in cert.pem -text -noout`, output:`Issuer: CN = R3\nValidity\n    Not After : <span class="warn">Sep 12 08:00:00 2026 GMT</span>`, does:`Reads and decodes a certificate file into human-readable details.`, where:`Checking exactly when a certificate expires before it silently takes production down.` },
    curlVi: { syntax:`curl -vI &lt;url&gt;`, cmd:`curl -vI https://example.com`, output:`* expire date: <span class="warn">Sep 12 08:00:00 2026 GMT</span>\n<span class="ok">HTTP/1.1 200 OK</span>`, does:`Combines verbose TLS output with a headers-only request in one command.`, where:`Checking connectivity AND certificate validity at the same time, in a single line.` },
    tcpdump: { syntax:`tcpdump -i &lt;interface&gt; port &lt;port&gt;`, cmd:`sudo tcpdump -i eth0 port 80`, output:`14:02:11 IP 10.0.1.9.51322 > 10.0.1.5.80: Flags [S]\n14:02:11 IP 10.0.1.5.80 > 10.0.1.9.51322: Flags [S.]`, does:`Captures and prints raw network packets matching a filter, live.`, where:`The deepest level of network debugging — literally watching packets arrive and leave, when everything above this layer looks fine.` },
    traceroute: { syntax:`traceroute &lt;host&gt;`, cmd:`traceroute google.com`, output:`1  gateway (192.168.1.1)   1.2 ms\n2  10.0.0.1               8.4 ms\n3  google-edge             24.1 ms`, does:`Shows every network hop between your machine and the destination, one snapshot.`, where:`A quicker, one-time version of mtr — good for a fast first look at a routing path.` },
    arp: { syntax:`arp -a`, cmd:`arp -a`, output:`gateway (10.0.1.1) at <span class="ok">aa:bb:cc:00:11:22</span> [ether] on eth0`, does:`Shows the local network's IP-to-MAC-address mappings.`, where:`Debugging local network/LAN-level connectivity issues, distinct from routing problems further away.` },
    iptablesL: { syntax:`iptables -L -n`, cmd:`sudo iptables -L -n`, output:`Chain INPUT (policy DROP)\ntarget  prot  dpt\n<span class="ok">ACCEPT</span>  tcp   22\n<span class="err">REJECT</span>  tcp   8080`, does:`Lists the server's own local firewall rules.`, where:`"Why is this port unreachable even though the app IS listening" — a local firewall rule is very often the answer.` },
    ufwStatus: { syntax:`ufw status verbose`, cmd:`sudo ufw status verbose`, output:`Status: active\n<span class="ok">22/tcp   ALLOW IN   Anywhere</span>\n<span class="err">8080/tcp DENY IN   Anywhere</span>`, does:`Shows Ubuntu's simpler firewall frontend's current rules.`, where:`A friendlier alternative to reading raw iptables output when ufw is what's actually managing the rules.` },
    iptablesAdd: { syntax:`iptables -A INPUT -p tcp --dport &lt;port&gt; -j ACCEPT`, cmd:`sudo iptables -A INPUT -p tcp --dport 8080 -j ACCEPT`, output:`<span class="dim">(no output — rule added silently)</span>`, does:`Adds a new firewall rule allowing incoming traffic on a specific port.`, where:`Opening a port at the OS level — the Linux equivalent of adding a cloud Security Group rule.` },
    curlPost: { syntax:`curl -X POST -d '&lt;data&gt;' &lt;url&gt;`, cmd:`curl -X POST -d '{"name":"test"}' -H "Content-Type: application/json" https://api.example.com/users`, output:`<span class="ok">HTTP/1.1 201 Created</span>\n{"id": 42, "name": "test"}`, does:`Sends a POST request with a JSON body.`, where:`Testing an API endpoint manually from the terminal before writing real client code around it.` },
    curlHeader: { syntax:`curl -H "&lt;Header&gt;: &lt;value&gt;" &lt;url&gt;`, cmd:`curl -H "Authorization: Bearer abc123" https://api.example.com/me`, output:`<span class="ok">HTTP/1.1 200 OK</span>\n{"user": "alice"}`, does:`Sends a custom header — most often an auth token.`, where:`Testing authenticated API endpoints directly from the command line.` },
    curlL: { syntax:`curl -L &lt;url&gt;`, cmd:`curl -L http://example.com`, output:`<span class="dim">HTTP/1.1 301 Moved Permanently</span>\n<span class="ok">HTTP/1.1 200 OK</span>`, does:`Follows HTTP redirects automatically instead of stopping at the first 301/302.`, where:`Confirming a redirect chain actually ends up exactly where you expect it to.` },
    curlOutput: { syntax:`curl -o &lt;file&gt; &lt;url&gt;`, cmd:`curl -o release.tar.gz https://cdn.example.com/release.tar.gz`, output:`<span class="ok">100%  14.2M  downloaded</span>`, does:`Saves the response body to a file instead of printing it to the screen.`, where:`Downloading files via curl instead of reaching for wget.` },
    curlResolve: { syntax:`curl --resolve &lt;host&gt;:&lt;port&gt;:&lt;ip&gt; &lt;url&gt;`, cmd:`curl --resolve api.example.com:443:10.0.1.5 https://api.example.com/health`, output:`<span class="ok">HTTP/1.1 200 OK</span> <span class="dim">(forced to 10.0.1.5, bypassing DNS)</span>`, does:`Forces curl to use a specific IP for a hostname, bypassing DNS entirely.`, where:`Testing one specific server directly before it's even in DNS or load balancer rotation yet.` },
    nmapPort: { syntax:`nmap -p &lt;port&gt; &lt;host&gt;`, cmd:`nmap -p 443 example.com`, output:`PORT     STATE  SERVICE\n443/tcp  <span class="ok">open</span>   https`, does:`Scans and reports whether a specific port is open, closed, or filtered.`, where:`A more thorough alternative to nc for confirming reachability — only ever run against systems you're authorized to test.` },
    ssS: { syntax:`ss -s`, cmd:`ss -s`, output:`Total: 412\nTCP:   <span class="warn">380</span> (estab 210, closed 90, ...)`, does:`Gives a quick summary of total socket/connection counts on the machine.`, where:`Spotting an unusually high connection count fast — a possible leak or a flood, before digging into individual sockets.` }
  };
  function runNetworkCmd(key, btn) {
    const d = NETWORK_CMDS[key];
    if (!d) return;
    const lines = d.cmd.split('\n');
    document.getElementById('netCmd').textContent = lines[0];
    let extra = '';
    if (lines.length > 1) {
      extra = lines.slice(1).map(l => '<span class="ld-prompt">devops@server:~$</span> ' + l).join('\n') + '\n';
    }
    document.getElementById('netOutput').innerHTML = extra + d.output;
    document.getElementById('netSyntax').innerHTML = d.syntax || lines[0];
    document.getElementById('netDoes').innerHTML = d.does;
    document.getElementById('netWhere').innerHTML = d.where;
    document.querySelectorAll('#tab-networking .ld-pill').forEach(p => p.classList.remove('active'));
    if (btn) btn.classList.add('active');
  }

  const NETWORKING_QUIZ_JOKES = [
    `Why did the network administrator get promoted? He knew how to manage all the important connections.`,
    `There are only 10 types of people who understand binary — and an infinite number who understand IPv6 addresses even less.`,
    `My favorite HTTP status code is 418 — I'm a teapot. Deeply relatable.`,
    `TCP walks into a bar and says "I'd like a beer." Bartender asks "You'd like a beer?" TCP replies "Yes, I'd like a beer."`,
    `DNS is basically the internet's contact list — except sometimes it forgets to update itself for hours.`
  ];

  const NETWORKING_QUIZ_QUESTIONS = [
    { q:`Which OSI layer handles IP addressing and routing?`, options:[`The Application layer, at the very top`,`The Transport layer, one level below`,`The Network layer`,`The Data Link layer, near the bottom`], correct:2, why:`Layer 3 (Network) is where IP addressing and routing decisions actually happen.` },
    { q:`Which OSI layer do TCP and UDP operate at?`, options:[`The Transport layer`,`The Session layer, one level above`,`The Presentation layer, near the top`,`The Physical layer, at the very bottom`], correct:0, why:`Port numbers and reliable/unreliable delivery both live at Layer 4, Transport.` },
    { q:`What does the memory trick "Please Do Not Throw Sausage Pizza Away" help you remember?`, options:[`HTTP status codes, listed in numeric order`,`The 7 OSI layers, from bottom to top`,`The individual steps of a TCP handshake`,`The main DNS record types and their uses`], correct:1, why:`Physical, Data Link, Network, Transport, Session, Presentation, Application — bottom to top.` },
    { q:`Which OSI layer is responsible for encryption, like TLS/SSL?`, options:[`The Network layer, lower in the stack`,`The Transport layer, one level below`,`The Presentation layer`,`The Physical layer, at the very bottom`], correct:2, why:`Presentation (Layer 6) handles encoding and encryption/decryption.` },
    { q:`At which OSI layer do MAC addresses and switches operate?`, options:[`The Data Link layer`,`The Network layer, one level above`,`The Session layer, further up the stack`,`The Application layer, at the very top`], correct:0, why:`Layer 2 (Data Link) deals with MAC addresses and frames within a local network.` },
    { q:`What's the key difference between TCP and UDP?`, options:[`TCP is always faster than UDP, in every single case`,`TCP guarantees ordered, reliable delivery; UDP is fire-and-forget with no guarantee`,`UDP requires a handshake and TCP does not require one`,`They both guarantee delivery in exactly the same way`], correct:1, why:`TCP retransmits lost packets and keeps order; UDP just sends and moves on.` },
    { q:`Why does DNS typically use UDP instead of TCP?`, options:[`DNS queries are small, and speed matters more than guaranteed delivery`,`TCP technically doesn't support running on port 53 at all`,`UDP is generally considered more secure than TCP`,`DNS is legally required by standard to use UDP only`], correct:0, why:`A quick, small query doesn't need TCP's overhead — though DNS does fall back to TCP for large responses.` },
    { q:`What are the three steps of a TCP handshake, in order?`, options:[`SYN, then SYN-ACK, then ACK`,`GET, then POST, then PUT`,`Request, then Response, then Close`,`Connect, then Verify, then Send`], correct:0, why:`This three-way handshake is how a reliable TCP connection gets established before any real data flows.` },
    { q:`Why would you choose UDP for something like video streaming or VoIP?`, options:[`UDP actually guarantees that every packet arrives intact`,`Lower latency matters more than occasionally dropping a packet`,`UDP is considered fundamentally more secure than TCP`,`TCP is technically unable to carry video data at all`], correct:1, why:`A dropped video frame is barely noticeable; the delay from waiting for a TCP retransmit is far worse for real-time media.` },
    { q:`What port does SSH use by default?`, options:[`Port 21, commonly used for FTP`,`Port 22`,`Port 443, used for HTTPS`,`Port 3389, used for remote desktop`], correct:1, why:`Port 22 is the SSH default — often the very first port to lock down to known IPs.` },
    { q:`What port does HTTPS use by default?`, options:[`Port 80, used for plain HTTP`,`Port 443`,`Port 8080, a common alternate HTTP port`,`Port 22, used for SSH`], correct:1, why:`443 is HTTP-over-TLS — all production web traffic should end up here, not plain 80.` },
    { q:`Why should a database port like 5432 (PostgreSQL) never be exposed to the public internet?`, options:[`Because it measurably slows down every query once exposed`,`It's a direct path for attackers to reach your data — it should only be reachable from app servers`,`Because databases technically can't accept any external connections at all`,`Because it's physically impossible to expose that specific port`], correct:1, why:`A publicly reachable database port is one of the most common, most dangerous misconfigurations there is.` },
    { q:`What's port 53 used for?`, options:[`SSH, for secure remote access`,`DNS`,`HTTP, for plain web traffic`,`MySQL, for database connections`], correct:1, why:`Port 53 is the standard port for DNS queries, primarily over UDP.` },
    { q:`When your browser looks up a domain, what's checked first, before any network request is made?`, options:[`The root DNS server, contacted directly`,`Browser cache, then OS cache, then /etc/hosts`,`The domain's authoritative nameserver directly`,`Google's public DNS server, every single time`], correct:1, why:`Local caches are checked first specifically to avoid a real network lookup whenever possible.` },
    { q:`What does a CNAME DNS record actually do?`, options:[`Maps a domain directly to a specific IPv4 address`,`Creates an alias pointing one domain name at another domain name`,`Specifies which mail server handles a domain's email`,`Stores arbitrary verification text for a domain`], correct:1, why:`A CNAME doesn't point at an IP at all — it points at another hostname, which then gets resolved itself.` },
    { q:`What does an MX record specify?`, options:[`The IPv6 address associated with a domain`,`Which mail server handles email for that domain`,`The domain's authoritative nameservers`,`A text string used purely for domain verification`], correct:1, why:`MX records tell the world where to deliver email for a given domain.` },
    { q:`What does TTL control in a DNS record?`, options:[`How many network hops a packet is allowed to take`,`How long resolvers are allowed to cache that record before asking again`,`The maximum allowed size of a file transfer`,`How many separate DNS servers a domain can have`], correct:1, why:`A shorter TTL means changes propagate faster, at the cost of more frequent lookups.` },
    { q:`You just changed a DNS record, but visitors still hit the old IP hours later. What's the most likely explanation?`, options:[`DNS itself is broken and needs a full restart`,`The old record's TTL hasn't expired yet, so it's still cached at various resolvers`,`Only your own personal browser cache needs to be cleared`,`DNS changes are permanently blocked once originally set`], correct:1, why:`This is expected caching behavior, not a failure — resolvers are just honoring the TTL that was set.` },
    { q:`What does "dig +trace" actually show you?`, options:[`Only the final resolved IP address that was found, and absolutely nothing else`,`The full resolution path — root servers, then TLD servers, then the authoritative nameserver`,`A complete list of every other domain name currently hosted on that same server`,`The physical geographic location where the server is currently sitting`], correct:1, why:`It walks the entire delegation chain, one level at a time, instead of just returning the final answer.` },
    { q:`What's the actual purpose of the TLS handshake before HTTPS data is sent?`, options:[`To compress the outgoing data down before it actually gets transmitted`,`To verify the server's certificate and negotiate encryption keys before any real data moves`,`To silently check the end user's stored account password`,`To simply decide which specific network port should be used`], correct:1, why:`Nothing meaningful is exchanged until both sides agree on trust and encryption first.` },
    { q:`Where does "SSL termination" commonly happen in a production setup?`, options:[`Only ever on the end user's own personal device`,`At the load balancer, so backend servers can talk over plain HTTP internally`,`It genuinely never happens — encryption must always be fully end-to-end`,`Inside the database server itself, before any query runs`], correct:1, why:`Terminating TLS at the edge simplifies backend servers while still encrypting everything the public sees.` },
    { q:`Why does a browser show a certificate warning even though HTTPS is technically active?`, options:[`Because HTTPS as a whole protocol is completely broken in that particular situation`,`The certificate might be expired, self-signed, or issued for the wrong domain — encrypted but not properly verified`,`Because the website in question simply has no internet connection at all`,`Because the browser software itself is always just generally out of date`], correct:1, why:`Encryption and trust/verification are two separate things — you can have one without the other.` },
    { q:`What does "curl -vI" show that a plain "curl -I" doesn't?`, options:[`Nothing meaningfully different from what the plain version already shows`,`The full TLS handshake details, including certificate expiry, alongside the headers`,`It additionally downloads the entire page body content as well`,`It only works over plain HTTP, and never functions over HTTPS`], correct:1, why:`Combining verbose mode with a HEAD request gets you both connectivity and certificate info in one line.` },
    { q:`What does a 200 status code mean?`, options:[`The client made a malformed or invalid request`,`The request succeeded`,`The server crashed unexpectedly while handling it`,`The requested resource was permanently moved`], correct:1, why:`200 OK is the standard "everything worked" response.` },
    { q:`What's the actual difference between a 401 and a 403 status code?`, options:[`They mean exactly the same underlying thing, in any practical sense`,`401 means you're not authenticated at all; 403 means you ARE authenticated but lack permission`,`401 is classified as always a server-side error, while 403 is client-side`,`403 always means that the entire server is currently sitting down`], correct:1, why:`401 = "who are you?" 403 = "I know who you are, and the answer is still no."` },
    { q:`What does a 502 Bad Gateway typically indicate?`, options:[`The client sent an incorrectly malformed request body to the server`,`A proxy (Nginx, ALB) couldn't reach its upstream server — the upstream is down or unreachable`,`The DNS lookup performed for the domain itself simply failed`,`The user account simply typed their own password incorrectly`], correct:1, why:`502 specifically points at the proxy layer failing to get a response from whatever's behind it.` },
    { q:`What does a 504 Gateway Timeout typically indicate?`, options:[`The client's own personal internet connection dropped mid-request`,`The proxy waited too long for a response from upstream — usually a slow app or database`,`The TLS certificate configured for the site has since expired`,`The requested domain name simply doesn't exist anymore`], correct:1, why:`Unlike 502, the upstream did respond eventually — or never did — just too slowly for the proxy's patience.` },
    { q:`What's the practical difference between a 301 and a 302 redirect?`, options:[`They behave in an identical way, in every meaningful sense`,`301 is a permanent redirect (cached, SEO value transfers); 302 is temporary`,`302 only ever works for pure HTTPS requests`,`301 redirects can only ever fire once per domain, total`], correct:1, why:`Browsers and search engines cache 301s aggressively — get the redirect type wrong and it's hard to undo.` },
    { q:`What does ping actually measure?`, options:[`Only the speed of a DNS resolution, nothing more`,`Whether a host responds to ICMP echo requests, and how long that takes`,`The exact route that packets take to reach a destination`,`How much total bandwidth is currently available`], correct:1, why:`It's purely a reachability + round-trip-time check, nothing about the path or bandwidth itself.` },
    { q:`What's the real advantage of mtr over a one-time traceroute?`, options:[`mtr is a tool that's exclusively available on Windows machines`,`mtr continuously re-pings every hop and shows ongoing packet loss, not just one snapshot`,`traceroute is fundamentally unable to show any hop names`,`mtr somehow works without needing any network access at all`], correct:1, why:`A single traceroute can miss intermittent loss that mtr's continuous sampling reveals clearly.` },
    { q:`What does "ss -tulpn" actually show?`, options:[`The system's current routing table, nothing else`,`Every listening socket, its port, and the process that owns it`,`Only cached DNS entries stored on the machine`,`Firewall rules, and only firewall rules`], correct:1, why:`It's the modern go-to for "what's actually listening on this machine, and what owns it."` },
    { q:`Why is "Connection refused" a meaningfully different error from a connection timing out?`, options:[`Because in reality, the two errors actually mean exactly the same underlying thing in every single case`,`Refused means the network path works but nothing is listening on that port; a timeout often means a firewall is silently blocking it`,`Because a connection timeout always very specifically means that the server itself has already crashed`,`Because refused errors are, as a rule, a thing that can only ever happen over plain UDP connections`], correct:1, why:`One tells you "wrong port/service," the other tells you "something is blocking me" — very different next steps.` },
    { q:`What does "nc -zv" actually test?`, options:[`Only the raw speed of DNS resolution for a given host`,`Whether a specific TCP port is reachable, without completing a full protocol handshake`,`The server's current CPU usage percentage at that moment`,`How many separate users are presently connected to a service`], correct:1, why:`It's a lightweight connectivity probe — confirms the port is open without speaking the real application protocol.` },
    { q:`What does "ip addr show" display?`, options:[`The system's current routing table, specifically`,`Every network interface and its assigned IP address(es)`,`The machine's current DNS server configuration`,`A list of which firewall ports are currently open`], correct:1, why:`It's the modern replacement for ifconfig — same core information, current tooling.` },
    { q:`If a service is bound to 127.0.0.1 instead of 0.0.0.0, what happens?`, options:[`It becomes freely reachable from anywhere at all on the public internet`,`It only accepts connections originating from the same machine — nothing external can reach it`,`It automatically starts load-balancing every bit of incoming traffic`,`It quietly disables all networking on that entire machine`], correct:1, why:`This is one of the most common "works locally, unreachable from anywhere else" bugs.` },
    { q:`What does "openssl s_client -connect" actually do?`, options:[`It quietly starts up a lightweight local web server`,`Manually performs a TLS handshake against a host and shows the full certificate chain`,`It permanently and irreversibly deletes an existing SSL certificate`,`It simply generates a brand-new domain name on your behalf`], correct:1, why:`It's the lowest-level way to inspect exactly what a TLS handshake actually returns.` },
    { q:`What does tcpdump actually capture?`, options:[`Only DNS queries specifically, and absolutely nothing else`,`Raw network packets matching a filter, live, as they arrive and leave the interface`,`Just the application's own internal error log entries`,`General CPU and memory performance metrics only`], correct:1, why:`It's genuinely watching packets at the wire level — the deepest layer of network debugging available.` },
    { q:`What's the purpose of "iptables -L -n"?`, options:[`It lists all currently running processes on the system`,`Lists the server's own local firewall rules`,`It lists every DNS record configured for a domain`,`It simply lists which files are currently open`], correct:1, why:`This shows exactly what the local firewall is set to allow or block, chain by chain.` },
    { q:`Why might a port be reachable to the app itself but blocked for everyone else?`, options:[`Because this exact situation is actually impossible in practice`,`A local firewall rule (or cloud Security Group) can block external traffic even while the app listens fine`,`Because ports can only ever be fully open or fully closed for an entire machine`,`Because only DNS configuration ever controls this, never firewalls`], correct:1, why:`The app listening and the OS permitting outside traffic to reach it are two completely separate concerns.` },
    { q:`What does "curl -L" do differently from a plain curl?`, options:[`Nothing at all — the two behave in an identical way`,`It automatically follows HTTP redirects instead of stopping at the first 301/302`,`It only functions correctly with FTP-based transfers`,`It disables TLS/HTTPS support entirely for that request`], correct:1, why:`Without -L, curl shows you the redirect response itself and stops right there.` },
    { q:`What does "curl --resolve" let you do?`, options:[`Remotely delete an existing DNS record`,`Force curl to use a specific IP for a hostname, bypassing DNS entirely`,`Encrypt a request without needing TLS at all`,`It only ever works when downloading files, nothing else`], correct:1, why:`Useful for testing one specific server directly before it's even in DNS or load-balancer rotation.` },
    { q:`What's the point of testing with "nc -zv" before debugging the application itself?`, options:[`It completely replaces the need for reading any application logs`,`It isolates whether the problem is network/firewall-level or actually inside the application`,`It automatically fixes any network issues that it happens to find`,`It only ever works for testing websites, never for databases`], correct:1, why:`Confirming the network path is fine (or isn't) first saves you from debugging the wrong layer entirely.` },
    { q:`Scenario: your app can't reach the database, and "nc -zv" returns "Connection refused." What does that tell you?`, options:[`That the database server's own configured firewall rules are actively blocking the request`,`The network path is fine, but nothing is actually listening on that port yet — the problem is on the database side`,`That your own local machine's network connection is currently sitting down`,`That DNS itself simply failed to resolve the given hostname at all`], correct:1, why:`Refused (not a timeout) specifically means the network got through, but found no listener there.` },
    { q:`Scenario: you changed a domain's IP, but dig still shows the old IP hours later. What's actually happening?`, options:[`DNS as a whole system is broken and needs a complete restart`,`The record's TTL hasn't expired at various resolvers yet — this is expected caching behavior`,`You personally need to go change your own computer's IP address`,`The DNS change was silently rejected somewhere by the domain registrar`], correct:1, why:`This is DNS propagation working exactly as designed, not a malfunction.` },
    { q:`Scenario: "curl -vI" shows a certificate "expire date" a week from now. What should you do?`, options:[`Nothing at all — since it hasn't expired yet, it doesn't matter`,`Renew it now — waiting until expiry risks a production outage the moment it lapses`,`Simply wait until real users actually start complaining first`,`Nothing can really be done — certificates can't be renewed early`], correct:1, why:`Renewing well ahead of expiry is the whole point of monitoring this in the first place.` },
    { q:`Scenario: a service works from the same server but gets "connection refused" from every other server. "ss -tulpn" shows it bound to 127.0.0.1. What's the fix?`, options:[`Restart the entire server completely and totally from scratch`,`Rebind the service to listen on 0.0.0.0 (or its real interface IP) instead of localhost only`,`Simply go change the domain's already-existing DNS record`,`Go install an entirely new, completely separate firewall`], correct:1, why:`Once it's listening on all interfaces instead of just localhost, other machines can actually reach it.` },
    { q:`Scenario: European users report slow load times but US tests look fine. mtr shows 18% loss at one specific hop. What does that tell you?`, options:[`That the application server itself is fundamentally and completely broken somehow`,`The problem is at a specific point along that regional network path, not the app or destination server`,`That the users' own personal home computers are somehow all simultaneously broken`,`That the site's HTTPS security certificate has recently and quietly expired`], correct:1, why:`mtr pinpointing loss at one particular hop isolates the issue to that segment of the route.` },
    { q:`Scenario: a load balancer keeps marking a server unhealthy. "curl -I" against the health endpoint locally returns 500. What does this confirm?`, options:[`That the load balancer itself is malfunctioning and simply needs a restart`,`The application is genuinely failing its own health check — the load balancer was right to pull it`,`That DNS is somehow misconfigured for that one particular server`,`That the site's TLS certificate has already quietly expired`], correct:1, why:`Reproducing the exact health check yourself proves the failure is real, not a load balancer glitch.` },
    { q:`Scenario: a teammate gets 401 from an API that works fine for you. Reproducing their exact request with "curl -H" shows "token expired." What does this prove?`, options:[`That the API itself is currently broken for every single one of its users`,`The problem was isolated to their specific token, not the API, their code, or their environment`,`That their computer simply has no internet access of any kind`,`That the DNS record configured for that API is wrong`], correct:1, why:`Reproducing the exact request removes every other variable and pins the cause down precisely.` },
    { q:`Scenario: you open a port, confirm with "ss -tulpn" it's listening, but external connections still can't reach it. "iptables -L -n" shows a REJECT rule on that port. What does this mean?`, options:[`That the application in question simply needs to be restarted again`,`A local firewall rule is blocking traffic to that port, independent of the app listening fine`,`That DNS needs to be freshly updated for that particular server`,`That the port number was simply typed incorrectly somewhere along the way`], correct:1, why:`The app is doing its job — the OS-level firewall is what's actually standing in the way.` }
  ];
