  /* ============ SHELL SCRIPTING — extra command simulator (cron, signals, etc.) ============ */
  const SH_CMDS = {
    crontabEdit: { syntax:`crontab -e`, cmd:`crontab -e`, output:`<span class="dim"># opens your crontab in the default editor</span>\n0 2 * * * /scripts/backup.sh\n<span class="ok">*/15 * * * * /scripts/health.sh</span>`, does:`Opens (and creates, if missing) the current user's crontab for editing.`, where:`How every scheduled job — backups, health checks, cleanups — actually gets registered with cron.` },
    crontabList: { syntax:`crontab -l`, cmd:`crontab -l`, output:`0 2 * * * /scripts/backup.sh\n<span class="ok">*/15 * * * * /scripts/health.sh</span>\n0 0 * * 0 /scripts/cleanup.sh`, does:`Lists the current user's scheduled cron jobs without opening an editor.`, where:`Quickly checking what's already scheduled on a server before adding something new.` },
    crontabRemove: { syntax:`crontab -r`, cmd:`crontab -r`, output:`<span class="warn">(no output — every scheduled job for this user is now gone)</span>`, does:`Deletes the current user's entire crontab in one shot.`, where:`Rarely used deliberately — usually shows up as the answer to "why did all my cron jobs vanish?"` },
    cronSyntax: { syntax:`&lt;min&gt; &lt;hour&gt; &lt;day&gt; &lt;month&gt; &lt;weekday&gt; &lt;command&gt;`, cmd:`0 9 * * 1-5 /scripts/report.sh`, output:`<span class="dim"># minute=0, hour=9, every day-of-month, every month, weekdays 1-5 (Mon-Fri)</span>\n<span class="ok">→ runs /scripts/report.sh at 9:00 AM, Monday through Friday</span>`, does:`The five fields are minute, hour, day-of-month, month, and day-of-week — a * in any field means "every."`, where:`Reading (or writing) any cron schedule starts with decoding these five fields in order.` },
    atCommand: { syntax:`at &lt;time&gt;`, cmd:`echo "/scripts/one-off.sh" | at 23:00`, output:`<span class="ok">job 7 at Mon Aug 10 23:00:00 2026</span>`, does:`Schedules a command to run once, at a specific future time — unlike cron, which repeats.`, where:`A one-time deferred task, like "run this maintenance script tonight at 11pm," without needing a recurring cron entry.` },
    caseStatement: { syntax:`case &lt;var&gt; in &lt;pattern&gt;) ... ;; esac`, cmd:`case "$1" in\n  start) echo "Starting...";;\n  stop) echo "Stopping...";;\n  *) echo "Usage: $0 start|stop";;\nesac`, output:`<span class="dim">$ ./service.sh start</span>\n<span class="ok">Starting...</span>`, does:`Matches a variable against a list of patterns and runs the block for whichever one matches — cleaner than a long if/elif chain.`, where:`Handling a fixed set of expected arguments, like a start/stop/restart control script.` },
    untilLoop: { syntax:`until [ &lt;test&gt; ]; do ... done`, cmd:`until curl -sf http://localhost:3000/health; do\n  echo "Waiting for app to be ready..."\n  sleep 2\ndone`, output:`Waiting for app to be ready...\nWaiting for app to be ready...\n<span class="ok">(loop exits once curl succeeds)</span>`, does:`Repeats a block until its test becomes true — the opposite of "while," which repeats while true.`, where:`Waiting for a service to become ready before continuing a deploy script — poll until it responds.` },
    selectMenu: { syntax:`select &lt;var&gt; in &lt;options&gt;; do ... done`, cmd:`select env in staging production; do\n  echo "Deploying to $env"\n  break\ndone`, output:`1) staging\n2) production\n#? <span class="hi">2</span>\n<span class="ok">Deploying to production</span>`, does:`Prints a numbered menu and waits for the user to pick an option by number.`, where:`Simple interactive scripts where a human picks from a short, fixed list of choices.` },
    trapSignal: { syntax:`trap '&lt;command&gt;' &lt;signal&gt;`, cmd:`trap 'echo "Cleaning up..."; rm -f /tmp/lockfile' EXIT`, output:`<span class="dim">(script runs normally)</span>\n<span class="ok">Cleaning up...</span>\n<span class="dim"># the EXIT trap fires whether the script succeeds, fails, or is interrupted</span>`, does:`Registers a command to run automatically when the script receives a signal — EXIT fires on any script termination.`, where:`Guaranteeing cleanup (removing a lockfile, killing a background process) even if the script fails partway through.` },
    waitCmd: { syntax:`wait &lt;PID&gt;`, cmd:`./task1.sh &\n./task2.sh &\nwait\necho "Both finished"`, output:`<span class="dim">(both background jobs run in parallel)</span>\n<span class="ok">Both finished</span>`, does:`Pauses the script until the specified background job (or all of them, with no argument) finishes.`, where:`Running several independent steps in parallel, then waiting for all of them before continuing.` },
    backgroundJob: { syntax:`&lt;command&gt; &amp;`, cmd:`./long-task.sh &\necho "Started with PID $!"`, output:`<span class="ok">Started with PID 4821</span>`, does:`Runs a command in the background, immediately handing control back to the rest of the script.`, where:`Kicking off something slow (a build, a long migration) without blocking the rest of the script.` },
    jobsCmd: { syntax:`jobs`, cmd:`jobs`, output:`[1]+  Running   ./long-task.sh &`, does:`Lists the background jobs currently running in this shell session.`, where:`Checking what's still running in the background before deciding whether to wait or kill something.` },
    getopts: { syntax:`getopts "&lt;flags&gt;" &lt;var&gt;`, cmd:`while getopts "e:v" opt; do\n  case $opt in\n    e) env="$OPTARG";;\n    v) verbose=true;;\n  esac\ndone`, output:`<span class="dim">$ ./deploy.sh -e production -v</span>\n<span class="ok">env=production, verbose=true</span>`, does:`Parses real command-line flags like -e production -v, instead of relying on positional $1, $2 only.`, where:`Any script meant to be called with proper flags rather than "just remember the argument order."` },
    shift: { syntax:`shift &lt;n&gt;`, cmd:`echo "First: $1"\nshift\necho "Now first: $1"`, output:`<span class="dim">$ ./script.sh alpha beta gamma</span>\nFirst: alpha\n<span class="ok">Now first: beta</span>`, does:`Discards $1 and shifts every remaining argument down by one position.`, where:`Processing a variable-length list of arguments one at a time in a loop.` },
    readPrompt: { syntax:`read -p "&lt;prompt&gt;" &lt;var&gt;`, cmd:`read -p "Deploy to production? (y/n) " answer`, output:`Deploy to production? (y/n) <span class="hi">y</span>  <span class="dim">(you typed this)</span>`, does:`Shows a prompt and waits for input on the same line, storing it in the variable.`, where:`Confirmation prompts — combining the prompt and the read into a single line instead of two.` },
    readSilent: { syntax:`read -s &lt;var&gt;`, cmd:`read -s -p "Password: " pw`, output:`Password: <span class="dim">(input is hidden while typing)</span>`, does:`Reads input without echoing it to the screen as it's typed.`, where:`Prompting for a password or token inside a script, without it appearing on screen or in a terminal recording.` },
    printfCmd: { syntax:`printf "&lt;format&gt;" &lt;args&gt;`, cmd:`printf "Deploy: %-10s Status: %s\\n" "myapp" "success"`, output:`<span class="ok">Deploy: myapp      Status: success</span>`, does:`Formats and prints output with precise control over spacing, padding, and types — unlike plain echo.`, where:`Producing aligned, predictable output for logs or reports, where echo's formatting isn't reliable enough.` },
    xargsCmd: { syntax:`&lt;command&gt; | xargs &lt;command2&gt;`, cmd:`find . -name "*.log" | xargs rm -f`, output:`<span class="dim">(every matched .log file is deleted)</span>`, does:`Takes lines of input and feeds them as arguments to another command.`, where:`Bridging commands that only output lines (like find) with commands that need arguments (like rm).` },
    teeCmd: { syntax:`&lt;command&gt; | tee &lt;file&gt;`, cmd:`./deploy.sh | tee deploy.log`, output:`Deploying v2.0...\nDeploy finished\n<span class="dim"># output is shown AND saved to deploy.log</span>`, does:`Writes command output to a file while also still printing it to the screen.`, where:`Watching a script run live while still keeping a saved log of exactly what happened.` },
    seqCmd: { syntax:`seq &lt;start&gt; &lt;end&gt;`, cmd:`for i in $(seq 1 3); do echo "Attempt $i"; done`, output:`Attempt 1\nAttempt 2\n<span class="ok">Attempt 3</span>`, does:`Generates a sequence of numbers — a common way to drive a fixed-count retry loop.`, where:`Retry loops with a specific number of attempts, without manually incrementing a counter.` },
    basenameDirname: { syntax:`basename &lt;path&gt;   /   dirname &lt;path&gt;`, cmd:`path="/opt/releases/myapp/v2.tar.gz"\necho "File: $(basename "$path")"\necho "Dir: $(dirname "$path")"`, output:`File: <span class="ok">v2.tar.gz</span>\nDir: /opt/releases/myapp`, does:`basename extracts just the filename from a path; dirname extracts just the directory.`, where:`Scripts that need to work with a path's filename and folder separately — logging, renaming, moving files.` },
    exportCmd: { syntax:`export &lt;VAR&gt;=&lt;value&gt;`, cmd:`export API_URL="https://api.example.com"\n./child-script.sh`, output:`<span class="ok">(child-script.sh can now read $API_URL too)</span>`, does:`Makes a variable available to any child process the script launches, not just the current shell.`, where:`Passing config down into a script that calls other scripts or programs.` },
    localVar: { syntax:`local &lt;var&gt;=&lt;value&gt;`, cmd:`deploy() {\n  local env="$1"\n  echo "Deploying to $env"\n}`, output:`<span class="ok">(env only exists inside the deploy function, not outside it)</span>`, does:`Scopes a variable to just the current function, instead of leaking into the whole script.`, where:`Writing functions that don't accidentally overwrite a variable with the same name elsewhere in the script.` },
    declareCmd: { syntax:`declare -&lt;flag&gt; &lt;var&gt;`, cmd:`declare -r MAX_RETRIES=3\nMAX_RETRIES=5`, output:`<span class="err">bash: MAX_RETRIES: readonly variable</span>`, does:`Explicitly declares a variable with a type or attribute — like -r for read-only, -i for integer.`, where:`Locking down a constant (like a max retry count) so it can't be accidentally overwritten later in the script.` },
    sourceCmd: { syntax:`source &lt;file&gt;   /   . &lt;file&gt;`, cmd:`source ./config.env\necho "$DB_HOST"`, output:`<span class="ok">db.internal.example.com</span>`, does:`Runs another script's commands in the current shell, so its variables and functions become available here too.`, where:`Loading shared config or helper functions from a separate file into your main script.` },
    heredoc: { syntax:`&lt;command&gt; &lt;&lt;EOF ... EOF`, cmd:`cat <<EOF > config.yml\nenv: production\nreplicas: 3\nEOF`, output:`<span class="ok">(config.yml written with both lines)</span>`, does:`Feeds a multi-line block of text directly into a command, without needing separate echo lines.`, where:`Generating a config file or multi-line message from inside a script cleanly.` },
    evalCmd: { syntax:`eval "&lt;string&gt;"`, cmd:`cmd="echo Hello"\neval "$cmd"`, output:`<span class="ok">Hello</span>`, does:`Builds a command as a string, then actually executes that string as a real command.`, where:`Rare and risky — mostly seen when a command needs to be assembled dynamically; never eval untrusted input.` },
    execCmd: { syntax:`exec &lt;command&gt;`, cmd:`exec node server.js`, output:`<span class="dim">(node server.js replaces this script's process entirely — no script code runs after this line)</span>`, does:`Replaces the current script's process with the new command, instead of starting a child process.`, where:`Docker entrypoint scripts commonly end with exec so signals (like SIGTERM) reach the app directly.` },
    setX: { syntax:`set -x`, cmd:`set -x\ncount=$((1+2))\necho $count`, output:`<span class="dim">+ count=3</span>\n<span class="dim">+ echo 3</span>\n<span class="ok">3</span>`, does:`Turns on debug tracing — prints every command the script actually runs, right before it runs it.`, where:`Debugging a script that isn't behaving as expected, by watching exactly what it executes line by line.` },
    specialVars: { syntax:`$$  $!  $?  $0  $#`, cmd:`echo "PID: $$, last bg PID: $!, last exit: $?, script: $0, args: $#"`, output:`<span class="ok">PID: 4821, last bg PID: 4822, last exit: 0, script: ./deploy.sh, args: 2</span>`, does:`Built-in variables: $$ = this script's PID, $! = last background job's PID, $? = last exit code, $0 = script name, $# = argument count.`, where:`Referenced constantly in error handling, logging, and background-job scripts — worth memorizing.` },
    dateCmd: { syntax:`date +&lt;format&gt;`, cmd:`echo "Deployed at $(date +'%Y-%m-%d %H:%M:%S')"`, output:`<span class="ok">Deployed at 2026-08-10 14:02:11</span>`, does:`Prints the current date/time, formatted however the +format string specifies.`, where:`Timestamping log lines and deploy messages inside a script.` },
    sleepCmd: { syntax:`sleep &lt;seconds&gt;`, cmd:`echo "Waiting for service to warm up..."\nsleep 5\necho "Continuing"`, output:`Waiting for service to warm up...\n<span class="dim">(pauses for 5 seconds)</span>\n<span class="ok">Continuing</span>`, does:`Pauses script execution for a given number of seconds.`, where:`Simple pauses between retries, or giving a just-started service a moment before checking it.` }
  };
  function runShCmd(key, btn) {
    const d = SH_CMDS[key];
    if (!d) return;
    const lines = d.cmd.split('\n');
    document.getElementById('shCmd').textContent = lines[0];
    let extra = '';
    if (lines.length > 1) {
      extra = lines.slice(1).map(l => '<span class="ld-prompt">$</span> ' + l).join('\n') + '\n';
    }
    document.getElementById('shOutput').innerHTML = extra + d.output;
    document.getElementById('shSyntax').innerHTML = d.syntax || lines[0];
    document.getElementById('shDoes').innerHTML = d.does;
    document.getElementById('shWhere').innerHTML = d.where;
    document.querySelectorAll('#tab-shellscript .ld-pill').forEach(p => p.classList.remove('active'));
    if (btn) btn.classList.add('active');
  }

  /* ============ SHELL SCRIPTING — mini script runner ============ */
  const SHELL_LESSONS = {
    shebang: { filename:`hello.sh`, syntax:`#!/bin/bash  →  chmod +x &lt;script&gt;.sh  →  ./&lt;script&gt;.sh`,
      breakdown:[
        {term:`#!/bin/bash`, desc:`The "shebang" — tells the OS which program should interpret this file. Must be the very first line.`},
        {term:`#`, desc:`Starts a comment. Everything after a # on a line is ignored by the shell.`},
        {term:`echo "text"`, desc:`Prints text to the screen.`},
        {term:`$(command)`, desc:`Runs a command and drops its result straight into the surrounding text.`}
      ],
      code:`<span class="c">#!/bin/bash</span>\n<span class="c"># This is a comment — the shell ignores it</span>\n\n<span class="fn">echo</span> <span class="s">"Hello, DevOps!"</span>\n<span class="fn">echo</span> <span class="s">"Today is $(date +%A)"</span>`,
      output:`Hello, DevOps!\nToday is Sunday`,
      does:`The <code>#!/bin/bash</code> line (the "shebang") tells the OS which interpreter should run this file — it must be the very first line. <code>echo</code> prints text. <code>$(date +%A)</code> runs a command and drops its output right into the string.`,
      where:`Every automation script in this entire cheat sheet — CI/CD steps, Docker entrypoints, cron jobs — starts life as exactly this: a plain text file with a shebang on line one.` },
    varsArgs: { filename:`greet.sh`, syntax:`name="value"  (no spaces around =)   →   $1 $2 ... $@ $#`,
      breakdown:[
        {term:`name="value"`, desc:`Creates a variable. No spaces around the = or bash throws an error.`},
        {term:`$1 $2`, desc:`The 1st and 2nd arguments typed after the script's name when you ran it.`},
        {term:`\${2:-staging}`, desc:`Use $2, but if it was left empty, fall back to "staging" instead.`},
        {term:`$#`, desc:`The total number of arguments that were given.`}
      ],
      code:`<span class="c">#!/bin/bash</span>\nname=<span class="s">"$1"</span>\nenv_name=<span class="s">"\${2:-staging}"</span>\n\n<span class="fn">echo</span> <span class="s">"Deploying for: $name"</span>\n<span class="fn">echo</span> <span class="s">"Environment: $env_name"</span>\n<span class="fn">echo</span> <span class="s">"Total arguments given: $#"</span>`,
      output:`<span class="ld-prompt">$</span> ./greet.sh alice production\nDeploying for: alice\nEnvironment: production\nTotal arguments given: 2`,
      does:`<code>$1</code>, <code>$2</code>... are the arguments passed in when you run the script. <code>\${2:-staging}</code> means "use $2, but if it's empty, default to staging." <code>$#</code> counts how many arguments were given.`,
      where:`This is how every real deploy script works: <code>./deploy.sh myapp production</code> instead of hardcoding the app name and environment inside the script.` },
    readInput: { filename:`confirm.sh`, syntax:`read &lt;variable&gt;`,
      breakdown:[
        {term:`read answer`, desc:`Pauses the script and waits for the user to type something, then stores it in the variable "answer".`},
        {term:`if [ ... ]; then ... else ... fi`, desc:`Runs one block of code or another, depending on whether a test is true or false.`},
        {term:`"$answer" = "yes"`, desc:`A string comparison inside a test — always keep variables in quotes like this.`}
      ],
      code:`<span class="c">#!/bin/bash</span>\n<span class="fn">echo</span> <span class="s">"Type 'yes' to continue the deploy:"</span>\n<span class="k">read</span> answer\n\n<span class="k">if</span> [ <span class="s">"$answer"</span> = <span class="s">"yes"</span> ]; <span class="k">then</span>\n  <span class="fn">echo</span> <span class="s">"Continuing..."</span>\n<span class="k">else</span>\n  <span class="fn">echo</span> <span class="s">"Aborted."</span>\n<span class="k">fi</span>`,
      output:`Type 'yes' to continue the deploy:\n<span class="hi">yes</span>  <span class="dim">(you typed this)</span>\nContinuing...`,
      does:`<code>read</code> pauses the script and waits for the user to type something, then stores it in the variable named after it.`,
      where:`Confirmation prompts before a risky manual action — though real CI/CD (see the GitHub Actions tab) has no human to type anything, which is exactly why pipelines use flags like <code>-y</code> instead.` },
    conditionals: { filename:`check-disk.sh`, syntax:`if [ &lt;test&gt; ]; then ... elif [ &lt;test&gt; ]; then ... else ... fi`,
      breakdown:[
        {term:`if [ test ]; then`, desc:`Starts a conditional block — the code after "then" only runs if the test is true.`},
        {term:`elif [ test ]; then`, desc:`An extra condition, only checked if everything above it was false.`},
        {term:`else`, desc:`Runs only if none of the conditions above matched.`},
        {term:`fi`, desc:`Closes the if block ("if" spelled backwards) — every if needs one.`},
        {term:`-ge / -lt`, desc:`Numeric comparisons: greater-than-or-equal, less-than — see the full reference table below.`}
      ],
      code:`<span class="c">#!/bin/bash</span>\nusage=<span class="num">92</span>\n\n<span class="k">if</span> [ <span class="s">"$usage"</span> -ge <span class="num">90</span> ]; <span class="k">then</span>\n  <span class="fn">echo</span> <span class="s">"CRITICAL: disk at \${usage}%"</span>\n<span class="k">elif</span> [ <span class="s">"$usage"</span> -ge <span class="num">75</span> ]; <span class="k">then</span>\n  <span class="fn">echo</span> <span class="s">"WARNING: disk at \${usage}%"</span>\n<span class="k">else</span>\n  <span class="fn">echo</span> <span class="s">"OK: disk at \${usage}%"</span>\n<span class="k">fi</span>`,
      output:`<span class="err">CRITICAL: disk at 92%</span>`,
      does:`Runs different code depending on a true/false test.<br><br><strong>Numeric:</strong> -eq -ne -gt -ge -lt -le &nbsp; <strong>String:</strong> = != -z (empty) -n (not empty) &nbsp; <strong>File:</strong> -f (file exists) -d (dir exists) -e (exists)`,
      where:`This is the actual logic behind Step 1 of Example 4 — deciding whether a health dashboard should read green, yellow, or red.` },
    loops: { filename:`restart-services.sh`, syntax:`for &lt;var&gt; in &lt;list&gt;; do ... done   /   while [ &lt;test&gt; ]; do ... done`,
      breakdown:[
        {term:`for x in list; do ... done`, desc:`Repeats the block once for every item in the list, with x set to the current item each time.`},
        {term:`"\${services[@]}"`, desc:`Expands to every item in the array, so the for loop can go through each one.`},
        {term:`while [ test ]; do ... done`, desc:`Repeats the block for as long as the test stays true.`},
        {term:`$((count+1))`, desc:`Arithmetic expansion — does the math and drops in the result.`}
      ],
      code:`<span class="c">#!/bin/bash</span>\nservices=(<span class="s">"nginx"</span> <span class="s">"app"</span> <span class="s">"worker"</span>)\n\n<span class="k">for</span> svc <span class="k">in</span> <span class="s">"\${services[@]}"</span>; <span class="k">do</span>\n  <span class="fn">echo</span> <span class="s">"Restarting $svc..."</span>\n<span class="k">done</span>\n\ncount=<span class="num">0</span>\n<span class="k">while</span> [ $count -lt <span class="num">3</span> ]; <span class="k">do</span>\n  <span class="fn">echo</span> <span class="s">"Health check attempt $((count+1))"</span>\n  count=$((count+<span class="num">1</span>))\n<span class="k">done</span>`,
      output:`Restarting nginx...\nRestarting app...\nRestarting worker...\nHealth check attempt 1\nHealth check attempt 2\nHealth check attempt 3`,
      does:`<code>for</code> loops over a fixed list, one item at a time. <code>while</code> keeps looping as long as its test stays true — <code>count</code> is manually incremented so it eventually stops.`,
      where:`Retry loops — "keep checking health until it passes or give up after N tries" — are one of the most common patterns in real deploy scripts.` },
    functions: { filename:`lib.sh`, syntax:`function_name() { ... }   →   function_name arg1 arg2`,
      breakdown:[
        {term:`name() { ... }`, desc:`Defines a reusable block of commands under a name, without running it yet.`},
        {term:`deploy "hello-app"`, desc:`Calling the function by name runs its code — "hello-app" becomes that function's own $1.`},
        {term:`$(date +%H:%M:%S)`, desc:`Command substitution again — formats the current time as HH:MM:SS.`}
      ],
      code:`<span class="c">#!/bin/bash</span>\n<span class="fn">log</span>() {\n  <span class="fn">echo</span> <span class="s">"[$(date +%H:%M:%S)] $1"</span>\n}\n\n<span class="fn">deploy</span>() {\n  log <span class="s">"Starting deploy for $1"</span>\n  log <span class="s">"Deploy finished"</span>\n}\n\ndeploy <span class="s">"hello-app"</span>`,
      output:`[14:02:11] Starting deploy for hello-app\n[14:02:11] Deploy finished`,
      does:`A function bundles reusable code under a name. Inside it, <code>$1</code> refers to whatever was passed to <em>that function</em>, not the whole script.`,
      where:`Real deploy scripts are built from small functions like this — <code>log()</code>, <code>check_health()</code>, <code>rollback()</code> — called in sequence, exactly like Example 4's steps.` },
    exitCodes: { filename:`validate.sh`, syntax:`exit &lt;code&gt;   (0 = success, 1–255 = failure)`,
      breakdown:[
        {term:`[ ! -f "file" ]`, desc:`A test that's true when the file does NOT exist — the ! means "not".`},
        {term:`exit N`, desc:`Immediately stops the script right there and sets the exit code to N.`},
        {term:`$?`, desc:`Holds the exit code of whatever command last ran — 0 means it succeeded.`}
      ],
      code:`<span class="c">#!/bin/bash</span>\n<span class="k">if</span> [ ! -f <span class="s">"config.yml"</span> ]; <span class="k">then</span>\n  <span class="fn">echo</span> <span class="s">"ERROR: config.yml missing"</span>\n  <span class="k">exit</span> <span class="num">1</span>\n<span class="k">fi</span>\n\n<span class="fn">echo</span> <span class="s">"Config found, continuing"</span>\n<span class="k">exit</span> <span class="num">0</span>`,
      output:`<span class="err">ERROR: config.yml missing</span>\n<span class="ld-prompt">$</span> echo $?\n<span class="num">1</span>`,
      does:`<code>exit N</code> immediately stops the script and sets <code>$?</code> to N. <code>0</code> always means success; any non-zero number means "something failed" — the specific number can mean whatever you define.`,
      where:`Exactly what a CI/CD step checks to decide if your job passed — see <code>$?</code>, <code>&amp;&amp;</code>, and <code>||</code> back in the Linux for DevOps tab.` },
    strings: { filename:`strings.sh`, syntax:`\${#var} length   \${var:0:5} substring   \${var/old/new} replace`,
      breakdown:[
        {term:`\${#app}`, desc:`The length of the string stored in "app".`},
        {term:`\${app:0:5}`, desc:`A substring: start at character 0, take the next 5 characters.`},
        {term:`\${app/production/staging}`, desc:`Replace the first match of "production" with "staging" inside the string.`}
      ],
      code:`<span class="c">#!/bin/bash</span>\napp=<span class="s">"hello-app-production"</span>\n\n<span class="fn">echo</span> <span class="s">"Length: \${#app}"</span>\n<span class="fn">echo</span> <span class="s">"First 5 chars: \${app:0:5}"</span>\n<span class="fn">echo</span> <span class="s">"Replaced: \${app/production/staging}"</span>`,
      output:`Length: 21\nFirst 5 chars: hello\nReplaced: hello-app-staging`,
      does:`Bash can manipulate strings without any external tool — length, slicing, and find-and-replace are all built in.`,
      where:`Turning a branch name or commit SHA into a valid Docker tag, or swapping an environment name inside a config string, entirely in bash.` },
    arithmetic: { filename:`math.sh`, syntax:`$(( expression ))`,
      breakdown:[
        {term:`$(( expression ))`, desc:`Arithmetic expansion — evaluates math using +, -, *, / and drops in the result.`}
      ],
      code:`<span class="c">#!/bin/bash</span>\nreplicas=<span class="num">3</span>\nnew_replicas=$((replicas * <span class="num">2</span>))\n\n<span class="fn">echo</span> <span class="s">"Scaling from $replicas to $new_replicas replicas"</span>`,
      output:`Scaling from 3 to 6 replicas`,
      does:`<code>$(( ))</code> does math directly in bash — no need for an external tool like <code>bc</code> for simple integer arithmetic.`,
      where:`Calculating scale-up amounts, retry counts, or timeouts inside a script without shelling out to another program.` },
    arrays: { filename:`environments.sh`, syntax:`arr=(a b c)   \${arr[0]}   \${arr[@]}   \${#arr[@]}`,
      breakdown:[
        {term:`arr=(a b c)`, desc:`Declares an array holding three items, in order.`},
        {term:`\${arr[0]}`, desc:`Gets one item by its index — 0 is always the first item.`},
        {term:`\${arr[@]}`, desc:`Expands to every item in the array.`},
        {term:`\${#arr[@]}`, desc:`Counts how many items are in the array.`}
      ],
      code:`<span class="c">#!/bin/bash</span>\nenvironments=(<span class="s">"dev"</span> <span class="s">"staging"</span> <span class="s">"production"</span>)\n\n<span class="fn">echo</span> <span class="s">"First environment: \${environments[0]}"</span>\n<span class="fn">echo</span> <span class="s">"All environments: \${environments[@]}"</span>\n<span class="fn">echo</span> <span class="s">"Total: \${#environments[@]}"</span>`,
      output:`First environment: dev\nAll environments: dev staging production\nTotal: 3`,
      does:`Arrays hold multiple values in one variable. <code>\${arr[0]}</code> gets one item, <code>\${arr[@]}</code> gets all of them, <code>\${#arr[@]}</code> counts them.`,
      where:`Looping through a list of servers, environments, or microservices to run the same command against each one — see Lesson 5's <code>for</code> loop.` },
    cmdSub: { filename:`report.sh`, syntax:`$(command)   (modern — old style uses backticks)`,
      breakdown:[
        {term:`$(command)`, desc:`Modern command substitution — runs the command, captures its output as text.`},
        {term:`\`command\``, desc:`The old-style equivalent of $(command) — same result, but harder to read and nest.`}
      ],
      code:`<span class="c">#!/bin/bash</span>\nnow=$(date +<span class="s">"%Y-%m-%d %H:%M"</span>)\nbranch=$(git rev-parse --abbrev-ref HEAD)\n\n<span class="fn">echo</span> <span class="s">"Deploy report generated: $now"</span>\n<span class="fn">echo</span> <span class="s">"Deploying from branch: $branch"</span>`,
      output:`Deploy report generated: 2026-08-09 14:02\nDeploying from branch: main`,
      does:`<code>$(command)</code> runs a command and substitutes its output right into the string, as if you'd typed the result yourself.`,
      where:`How a script grabs the current git commit, the current date, or a server's hostname to use later — without you typing it in by hand.` },
    errorHandling: { filename:`safe-deploy.sh`, syntax:`set -euo pipefail   (put this on line 2 of every real script)`,
      breakdown:[
        {term:`set -e`, desc:`Stops the whole script immediately the instant any command fails.`},
        {term:`set -u`, desc:`Turns using an undefined variable into an error, instead of silently treating it as empty.`},
        {term:`set -o pipefail`, desc:`Makes a pipeline fail if ANY command inside it fails — normally only the last command's exit code counts.`},
        {term:`trap 'cmd' ERR`, desc:`Runs "cmd" automatically the moment any error happens, before the script exits.`}
      ],
      code:`<span class="c">#!/bin/bash</span>\n<span class="k">set</span> -euo pipefail\n\n<span class="k">trap</span> <span class="s">'echo "Something failed on line $LINENO"'</span> ERR\n\n<span class="fn">echo</span> <span class="s">"Starting deploy..."</span>\n./run-tests.sh\ndocker build -t myapp .\n<span class="fn">echo</span> <span class="s">"Deploy complete"</span>`,
      output:`Starting deploy...\n24 passing\n[+] Building 1.8s (9/9) FINISHED\nDeploy complete`,
      does:`<code>-e</code> stops the script the instant any command fails. <code>-u</code> treats an undefined variable as an error. <code>-o pipefail</code> catches failures inside a pipe (normally only the last command's exit code counts). <code>trap</code> runs a command automatically the moment something errors.`,
      where:`Every script in this cheat sheet's real-world use should start with this line — it's the biggest difference between a script that fails loud and safe, versus one that silently keeps going after something already broke.` },
    healthCheck: { filename:`health-check.sh`, syntax:`— a complete script: variable + command substitution + conditional + exit code —`,
      breakdown:[
        {term:`curl -s -o /dev/null -w "%{http_code}"`, desc:`Fetches a URL silently (-s), throws away the response body (-o /dev/null), and prints only the HTTP status code (-w).`},
        {term:`(everything else)`, desc:`A variable, a conditional, and exit codes — already covered in Lessons 2, 4, and 7 above, just working together now.`}
      ],
      code:`<span class="c">#!/bin/bash</span>\n<span class="k">set</span> -euo pipefail\n\nURL=<span class="s">"https://hello-app.example.com/health"</span>\n\nstatus=$(curl -s -o /dev/null -w <span class="s">"%{http_code}"</span> <span class="s">"$URL"</span>)\n\n<span class="k">if</span> [ <span class="s">"$status"</span> = <span class="s">"200"</span> ]; <span class="k">then</span>\n  <span class="fn">echo</span> <span class="s">"OK: $URL is healthy"</span>\n  <span class="k">exit</span> <span class="num">0</span>\n<span class="k">else</span>\n  <span class="fn">echo</span> <span class="s">"FAIL: $URL returned $status"</span>\n  <span class="k">exit</span> <span class="num">1</span>\n<span class="k">fi</span>`,
      output:`<span class="ok">OK: https://hello-app.example.com/health is healthy</span>`,
      does:`Combines everything so far: a variable, command substitution (curl's output captured into <code>status</code>), a conditional, and an exit code — a real, complete script.`,
      where:`This exact script is what a <code>crontab -e</code> entry or a Kubernetes liveness probe runs every few seconds — the automated version of Example 4's Step 6.` },
    backupScript: { filename:`backup.sh`, syntax:`— combines date, string building, tar, and find -mtime —`,
      breakdown:[
        {term:`date +%Y-%m-%d`, desc:`Formats today's date as text, e.g. 2026-08-09.`},
        {term:`mkdir -p "$DIR"`, desc:`Creates a folder — the -p means "don't error if it already exists."`},
        {term:`tar -czf "$FILE" /app/data`, desc:`Bundles and compresses a folder into one .tar.gz archive file.`},
        {term:`find "$DIR" -type f -mtime +7 -delete`, desc:`Finds files older than 7 days inside that folder and deletes them.`}
      ],
      code:`<span class="c">#!/bin/bash</span>\n<span class="k">set</span> -euo pipefail\n\nDATE=$(date +%Y-%m-%d)\nBACKUP_DIR=<span class="s">"/backups"</span>\nFILE=<span class="s">"$BACKUP_DIR/db-$DATE.tar.gz"</span>\n\nmkdir -p <span class="s">"$BACKUP_DIR"</span>\ntar -czf <span class="s">"$FILE"</span> /app/data\n\n<span class="fn">echo</span> <span class="s">"Backup saved: $FILE"</span>\n\n<span class="c"># delete backups older than 7 days</span>\nfind <span class="s">"$BACKUP_DIR"</span> -type f -mtime +<span class="num">7</span> -delete\n<span class="fn">echo</span> <span class="s">"Old backups cleaned up"</span>`,
      output:`Backup saved: /backups/db-2026-08-09.tar.gz\nOld backups cleaned up`,
      does:`Combines command substitution (today's date), string building (the filename), <code>tar</code>, and <code>find -mtime</code> — both from the Linux for DevOps tab — into one real, useful script.`,
      where:`Exactly the kind of script a <code>crontab -e</code> entry runs every night at 2 AM — see the Logs &amp; Scheduling section of the Linux for DevOps tab.` },
    deployScript: { filename:`deploy.sh`, syntax:`— every lesson above, combined into one real ./deploy.sh —`,
      breakdown:[
        {term:`git pull origin main`, desc:`Pulls the latest committed code before deploying it.`},
        {term:`cmd1 || { cmd2; exit 1; }`, desc:`A fallback group: if cmd1 fails, run cmd2, then exit — all in one line.`},
        {term:`docker build / push, kubectl set image / rollout status`, desc:`Already taught in the Linux for DevOps and GitHub Actions tabs — here they're just being called from inside a script.`}
      ],
      code:`<span class="c">#!/bin/bash</span>\n<span class="k">set</span> -euo pipefail\n\nAPP=<span class="s">"$1"</span>\nENV=<span class="s">"\${2:-staging}"</span>\n\n<span class="fn">log</span>() { <span class="fn">echo</span> <span class="s">"[$(date +%H:%M:%S)] $1"</span>; }\n\nlog <span class="s">"Deploying $APP to $ENV"</span>\n\ngit pull origin main\n./run-tests.sh || { log <span class="s">"Tests failed — aborting"</span>; <span class="k">exit</span> <span class="num">1</span>; }\n\ndocker build -t <span class="s">"$APP:latest"</span> .\ndocker push <span class="s">"$APP:latest"</span>\n\nkubectl set image deployment/<span class="s">"$APP"</span> <span class="s">"$APP=$APP:latest"</span>\nkubectl rollout status deployment/<span class="s">"$APP"</span>\n\nlog <span class="s">"Deploy complete"</span>`,
      output:`[14:02:11] Deploying hello-app to production\nAlready up to date.\n24 passing\n[+] Building 1.8s (9/9) FINISHED\n<span class="ok">deployment.apps/hello-app image updated</span>\nWaiting for deployment "hello-app" rollout to finish...\n<span class="ok">deployment "hello-app" successfully rolled out</span>\n[14:02:44] Deploy complete`,
      does:`Every concept from this whole tab, used together: arguments, a function, <code>set -e</code>, <code>||</code> for graceful failure, command substitution, and calling out to <code>git</code>, <code>docker</code>, and <code>kubectl</code>.`,
      where:`This is, genuinely, what a hand-written <code>./deploy.sh</code> looks like — the manual version of the exact pipeline built in the GitHub Actions tab and Example 3.` }
  };
  function loadShellLesson(key, btn) {
    const d = SHELL_LESSONS[key];
    if (!d) return;
    document.getElementById('slFilename').textContent = d.filename;
    document.getElementById('slSyntax').innerHTML = d.syntax;
    document.getElementById('slCode').innerHTML = d.code;
    document.getElementById('slDoes').innerHTML = d.does;
    document.getElementById('slWhere').innerHTML = d.where;
    document.getElementById('slOutput').innerHTML = '<span class="dim">↳ click "▶ Run script" above to see what this actually prints</span>';
    document.querySelectorAll('.sl-pill').forEach(p => p.classList.remove('active'));
    if (btn) btn.classList.add('active');
    document.getElementById('slOutput').dataset.key = key;

    const list = document.getElementById('slBreakdownList');
    if (d.breakdown && d.breakdown.length) {
      list.innerHTML = d.breakdown.map(item =>
        `<div class="sl-breakdown-item"><span class="sl-breakdown-term">${item.term}</span><span class="sl-breakdown-desc">${item.desc}</span></div>`
      ).join('');
    } else {
      list.innerHTML = '<span class="dim">No new pieces here — this one just recombines what earlier lessons already taught.</span>';
    }
  }
  function runShellScript() {
    const key = document.getElementById('slOutput').dataset.key;
    const d = SHELL_LESSONS[key];
    if (!d) { document.getElementById('slOutput').innerHTML = '<span class="warn">↳ pick a lesson below first</span>'; return; }
    document.getElementById('slOutput').innerHTML = d.output;
  }

  const SHELLSCRIPT_QUIZ_JOKES = [
    `A programmer's variable naming philosophy: x, y, temp, temp2, ohGodWhy.`,
    `There are two hard problems in shell scripting: naming things, and knowing when quotes actually matter.`,
    `My shell script has trust issues — it checks the exit code of literally everything.`,
    `set -euo pipefail is the bash equivalent of a smoke detector nobody installs until after the fire.`,
    `Why did the shell script refuse to run? It said it needed to "find itself" first — turns out it was just missing chmod +x.`
  ];

  const SHELLSCRIPT_QUIZ_QUESTIONS = [
    { q:`What must be the very first line of a shell script for it to run correctly?`, options:[`Just a comment explaining what the script does`,`The shebang, e.g. #!/bin/bash`,`A line printing "start" to the screen`,`An empty blank line before the real code begins`], correct:1, why:`The shebang tells the OS which interpreter (bash, python, etc.) should execute the rest of the file.` },
    { q:`Before a script can be run with "./myscript.sh", what usually needs to happen first?`, options:[`Nothing at all — scripts run immediately without any setup`,`chmod +x myscript.sh to make it executable`,`It must be renamed with a .exe file extension`,`It must be compiled into a binary first`], correct:1, why:`Without execute permission, the OS refuses to run the file directly — chmod +x grants it.` },
    { q:`In "name=\"value\"", why does it matter that there are no spaces around the =?`, options:[`It's purely a style preference with no functional impact`,`Bash will misinterpret it as trying to run a command, not assign a variable`,`Spaces make the script noticeably slower to execute`,`It only actually matters when assigning numeric values`], correct:1, why:`bash parses "name = value" (with spaces) as trying to run a command called "name" — a very common beginner error.` },
    { q:`Inside a script, what does $1 refer to?`, options:[`The process ID number the script is currently running under`,`The first command-line argument passed to the script`,`A reference to the very first line of code in the file`,`The exit code returned by the most recent command`], correct:1, why:`Running "./deploy.sh myapp" makes $1 equal "myapp" inside the script.` },
    { q:`What does "\${2:-staging}" mean?`, options:[`Multiplies the value of $2 by the word staging`,`Use $2, but default to "staging" if it's empty`,`Permanently deletes the $2 variable from memory`,`Compares $2 against the literal string staging`], correct:1, why:`The :- syntax provides a fallback value when the variable is unset or empty.` },
    { q:`What does "$#" represent in a script?`, options:[`The exit code the script will return once it finishes`,`The total number of arguments given`,`The process ID number assigned to the running script`,`A special marker used to start an inline comment`], correct:1, why:`$# is the count of arguments passed in — useful for checking "did the user give me enough info to run?"` },
    { q:`What does the "read" command do?`, options:[`Prints a file's entire contents straight to the screen`,`Pauses the script and stores whatever the user types into a variable`,`Loads every environment variable currently set on the system`,`Parses and lists the command-line flags passed to the script`], correct:1, why:`read blocks execution until the user types something and presses enter, then stores it.` },
    { q:`In an if statement, what does "fi" do?`, options:[`Nothing — it's simply a leftover typo bash happens to ignore`,`Closes the if block`,`Starts the definition of a brand new function`,`Repeats everything inside the block one more time`], correct:1, why:`fi is "if" spelled backwards — bash's way of marking the end of a conditional block.` },
    { q:`What's the difference between "if" and "elif"?`, options:[`They're completely identical and can be used interchangeably`,`elif is only checked if the earlier conditions were false`,`An if block can only ever appear once in an entire script`,`Using elif immediately ends the script at that point`], correct:1, why:`elif lets you check an additional condition, but only if none of the ones above it matched.` },
    { q:`In a numeric test, what does "-ge" mean?`, options:[`Strictly greater than, with no equal case allowed`,`Greater than or equal to`,`Not equal to the value being compared`,`Less than or equal to the value being compared`], correct:1, why:`-ge is "greater than or equal" for numbers — different from = or == which compare strings.` },
    { q:`What's the difference between a "for" loop and a "while" loop?`, options:[`They behave identically and can always be swapped freely`,`for iterates over a fixed list, while repeats as long as a test stays true`,`A for loop always executes noticeably faster than a while loop`,`A while loop is fundamentally unable to reference any variables`], correct:1, why:`for is for "go through each of these known items," while is for "keep going until a condition changes."` },
    { q:`In "for svc in \"\${services[@]}\"; do ... done", what does "\${services[@]}" do?`, options:[`Retrieves only the very first item stored in the array`,`Expands to every item in the array`,`Permanently deletes the entire array and its contents`,`Returns just a count of how many items are in the array`], correct:1, why:`@ means "all elements" — this lets the for loop go through every item one at a time.` },
    { q:`What does "$((count+1))" do?`, options:[`Concatenates the word count with the number 1 as text`,`Arithmetic — adds 1 to the value of count`,`Turns that entire line into a comment bash ignores`,`Compares the current value of count against the number 1`], correct:1, why:`$(( )) is arithmetic expansion — it evaluates the math inside and returns the result.` },
    { q:`How do you define a function in bash?`, options:[`function_name() { ... }`,`def function_name():`,`func function_name`,`class function_name`], correct:0, why:`name() { commands } is bash's function syntax — no "def" keyword required.` },
    { q:`Inside a function, what does $1 refer to?`, options:[`Always refers to the whole script's first argument, no matter what`,`Whatever was passed to that specific function call`,`The literal name of the function itself, as text`,`Nothing at all — functions in bash can't accept arguments`], correct:1, why:`Each function has its own $1, $2, etc., scoped to how IT was called — separate from the script's own arguments.` },
    { q:`What does "exit 1" do inside a script?`, options:[`Pauses script execution for exactly 1 second, then continues`,`Immediately stops the script and sets its exit code to 1`,`Restarts the entire script from the very beginning again`,`Jumps execution back to line 1 of the script`], correct:1, why:`exit N stops execution right there; 0 conventionally means success, any other number means some kind of failure.` },
    { q:`What does "$?" hold, right after a command runs?`, options:[`Whatever text output the previous command printed`,`The exit code of the last command`,`Today's date, formatted using the system's locale settings`,`The total number of arguments the script was given`], correct:1, why:`0 means success; anything else means failure — this is what && and || actually check behind the scenes.` },
    { q:`What does "\${#app}" return, if app="hello"?`, options:[`The literal text "hello" printed back out`,`5`,`Just the single first letter of the string`,`A syntax error, since this isn't valid bash`], correct:1, why:`\${#var} gives the LENGTH of the string — "hello" has 5 characters.` },
    { q:`What does "\${app:0:5}" do?`, options:[`Permanently deletes the first 5 characters from the variable`,`Returns a substring starting at index 0, 5 characters long`,`Repeats the entire contents of app five times over`,`Overwrites the variable app with the literal number 5`], correct:1, why:`This is bash's substring syntax: \${var:start:length}.` },
    { q:`What does "\${app/old/new}" do?`, options:[`Renames the variable itself from app to something else`,`Replaces the first match of "old" with "new" inside the string`,`Attempts to mathematically divide app by the text "old"`,`Deletes every instance of the word "old", leaving nothing`], correct:1, why:`This is bash's find-and-replace syntax for strings — no external tool needed.` },
    { q:`How do you do basic integer math in bash without an external tool?`, options:[`math(1+2)`,`$((1+2))`,`calc 1+2`,`=1+2`], correct:1, why:`$(( )) is arithmetic expansion, built directly into bash.` },
    { q:`How do you declare an array in bash?`, options:[`arr = [a, b, c]`,`arr=(a b c)`,`array(a, b, c)`,`let arr = a,b,c`], correct:1, why:`Parentheses with space-separated items, no commas — "arr=(a b c)".` },
    { q:`What does "\${arr[@]}" return?`, options:[`Only the very first element stored in the array`,`Every element in the array`,`Just a count of how many elements the array contains`,`An empty string, since this syntax isn't valid`], correct:1, why:`@ expands to all items — same idea as \${services[@]} used in the loops lesson.` },
    { q:`What does "\${#arr[@]}" return?`, options:[`Just the single first element stored in the array`,`Every element joined together into one long string`,`The number of elements in the array`,`Nothing at all — this is actually invalid bash syntax`], correct:2, why:`Adding # before an array with [@] gives you the count of items, not their content.` },
    { q:`What's the difference between "$(command)" and backtick "command" syntax?`, options:[`They produce completely different results in every case`,`Same result — $(command) is the modern, easier-to-nest version`,`Backtick syntax executes noticeably faster in practice`,`The $(command) syntax simply doesn't work in bash at all`], correct:1, why:`Both are command substitution; $() is preferred because it's easier to read and nest inside other substitutions.` },
    { q:`What does "now=$(date +%Y-%m-%d)" do?`, options:[`Immediately prints today's date straight to the screen`,`Runs the date command and stores its output in the variable "now"`,`Deletes the variable now from the current shell session`,`Sets the variable now to the literal, unevaluated text "date"`], correct:1, why:`Command substitution runs date and captures its output as text, assigning it to "now".` },
    { q:`What does "set -e" do at the top of a script?`, options:[`Does nothing at all unless combined with other flags`,`Makes the script exit immediately the moment any command fails`,`Only turns on extra logging, with no other behavior change`,`Creates a new environment variable literally named e`], correct:1, why:`Without set -e, a script can keep running commands even after an earlier one has already failed silently.` },
    { q:`What does "set -u" catch that "set -e" doesn't?`, options:[`Errors caused specifically by failed network connections`,`Using a variable that was never defined`,`Errors caused by invalid or malformed bash syntax`,`Errors caused by insufficient file or folder permissions`], correct:1, why:`set -u turns a typo like a misspelled variable name into a hard error instead of silently treating it as empty text.` },
    { q:`What problem does "set -o pipefail" solve?`, options:[`Makes every pipe in the script execute measurably faster`,`Without it, a failing command in the middle of a pipe can go unnoticed — only the LAST command's exit code counts`,`Disables the use of pipes anywhere in the script entirely`,`Only changes how file and folder permissions are handled`], correct:1, why:`"cmd1 | cmd2" normally reports cmd2's exit code even if cmd1 secretly failed — pipefail fixes that blind spot.` },
    { q:`What does "trap 'echo failed' ERR" do?`, options:[`Runs "echo failed" a single time, immediately, right then`,`Automatically runs that command any time an error occurs later in the script`,`Deletes and suppresses every error message the script produces`,`Pauses script execution forever, with no way to continue`], correct:1, why:`trap registers a command to run automatically the moment a matching event (like ERR) happens, anywhere later in the script.` },
    { q:`According to the "how to think about writing scripts" framework, what should you do BEFORE writing any code?`, options:[`Add set -euo pipefail to the very top of the file first`,`Run the actual commands by hand until they work`,`Write out every comment before adding any real logic`,`Spend time carefully picking good variable names first`], correct:1, why:`A script should record steps you've already proven work by hand — not be where you invent the logic for the first time.` },
    { q:`When should you add "set -euo pipefail" to a script you're actively writing?`, options:[`Before writing a single line of the actual logic`,`After the logic is already correct and tested`,`Never — it's entirely optional and rarely worth adding`,`Only after deploying to production, never during development`], correct:1, why:`While you're still figuring out the logic, you want to see failures clearly to understand them — add safety once it's already working.` },
    { q:`What should turn into a variable or argument, according to the "find what changes" step?`, options:[`Every single word that appears anywhere in the script`,`Anything that would be different the next time you run the script`,`Only numeric values — text should always stay hardcoded`,`Nothing at all — hardcoding every value is actually safer`], correct:1, why:`Values likely to differ between runs belong in variables/arguments — that's what makes a script reusable instead of a one-time hack.` },
    { q:`If you're repeating the same block of logic in two different places in a script, what should you do?`, options:[`Copy and paste it again — it's simpler than refactoring`,`Pull it into a function and call it in both places`,`Just delete one of the two copies and hope for the best`,`Leave it duplicated — repeated logic isn't actually a problem`], correct:1, why:`Functions avoid duplicated logic — fix a bug once, in one place, instead of hunting down every copy.` },
    { q:`Why does the "test each piece alone" step in the thinking framework matter?`, options:[`It doesn't really matter — testing the whole script at once works just as well`,`A script built from pieces you've already verified is far easier to debug than one tested for the first time as a whole`,`Bash technically refuses to run scripts that skip this step`,`Testing pieces individually makes the final script run faster`], correct:1, why:`Isolating pieces (e.g. testing a loop with echo instead of the real command) catches bugs before they're tangled up with everything else.` },
    { q:`What is "curl -s -o /dev/null -w \"%{http_code}\" <url>" used for?`, options:[`Downloading the full contents of a URL and saving it to disk`,`Silently checking a URL and printing only its HTTP status code`,`Sending a request that deletes the resource at that URL`,`Opening that URL directly inside a web browser window`], correct:1, why:`-s is silent, -o /dev/null discards the response body, -w prints just the status code — a lightweight health check.` },
    { q:`In the health-check script, why does it "exit 0" on success and "exit 1" on failure?`, options:[`Those specific numbers are completely arbitrary and meaningless`,`So anything calling this script (like cron or Kubernetes) can tell whether it passed or failed`,`Purely to make the script execute a little bit faster`,`Because bash syntax technically requires every script to call exit`], correct:1, why:`0/non-zero is the universal pass/fail signal other tools check via $? — this is what makes a health-check script actually useful to automation.` },
    { q:`What does "mkdir -p" do differently from plain "mkdir"?`, options:[`Nothing — mkdir and mkdir -p behave in exactly the same way`,`Doesn't error if the directory already exists, and creates parent folders as needed`,`Creates the directory but marks it as permanently read-only`,`Deletes the target directory first before recreating it`], correct:1, why:`Plain mkdir fails if the folder already exists; -p makes it safe to run repeatedly — an idempotent-friendly choice.` },
    { q:`What does "tar -czf backup.tar.gz /app/data" do?`, options:[`Permanently deletes the entire /app/data folder`,`Bundles and compresses /app/data into one archive file`,`Copies /app/data elsewhere without compressing it at all`,`Extracts the contents of an already-existing archive`], correct:1, why:`-c create, -z gzip-compress, -f the output filename — this packages a whole folder into one portable file.` },
    { q:`In the backup script, what does "find $DIR -type f -mtime +7 -delete" accomplish?`, options:[`Finds and deletes every file that's newer than 7 days old`,`Finds and deletes files older than 7 days`,`Only lists matching files, without deleting any of them`,`Creates a backup copy of files older than 7 days`], correct:1, why:`+7 means "more than 7 days old" — automatic cleanup of old backups so disk doesn't fill up over time.` },
    { q:`In the deploy script, what does "./run-tests.sh || { log \"Tests failed\"; exit 1; }" do?`, options:[`Always runs both the tests and the log+exit block, no matter what`,`Runs the log+exit block ONLY if run-tests.sh fails`,`Runs the entire test suite a second time for safety`,`Silently ignores any test failures and continues on anyway`], correct:1, why:`|| only triggers the fallback block if the command before it failed — a graceful "stop here if this step didn't succeed."` },
    { q:`Why does the deploy script call git, docker, and kubectl instead of reimplementing their behavior?`, options:[`It's actually a mistake — scripts should never call other programs`,`Shell scripts are meant to orchestrate other tools, not replace them`,`Those particular commands don't actually function inside scripts`,`Calling external tools like this makes the script run slower`], correct:1, why:`A shell script's real power is gluing existing tools together in the right order, with the right checks — not rebuilding what already exists.` },
    { q:`What's the safest way to add a line to a file only if it isn't already there?`, options:[`Always append with >>, with no checking needed beforehand`,`grep -q "line" file || echo "line" >> file`,`Delete the file first, then write it fresh from scratch`,`Overwrite the file completely with cat file > file`], correct:1, why:`This checks whether the line already exists before appending — avoiding duplicate entries if the script runs more than once.` },
    { q:`What does "idempotent" mean for a script?`, options:[`Means the script automatically deletes itself after one run`,`Running it multiple times produces the same end result as running it once`,`Means the script gets measurably faster with each execution`,`Means the script can only ever be run with root access`], correct:1, why:`A script that blindly appends or creates without checking state can produce duplicate work if run more than once — idempotent scripts check first.` },
    { q:`What's wrong with writing "rm -rf $DIR" without quoting $DIR?`, options:[`Nothing — unquoted variables are always perfectly safe to use`,`If $DIR is empty or contains spaces, it can behave completely unexpectedly`,`It simply makes the command run a little more slowly`,`The command will refuse to run at all without quotes`], correct:1, why:`An empty, unquoted $DIR in "rm -rf $DIR" can expand into something dangerous — quoting "$DIR" is a basic safety habit.` },
    { q:`Which comes first when writing a script: making it work, or making it safe (set -euo pipefail)?`, options:[`Safety measures should always come first, before any logic`,`Working logic first, then layer safety on top once it's correct`,`Both must be written simultaneously, in the same pass`,`Safety isn't necessary at all if the script's logic is simple`], correct:1, why:`This mirrors the thinking framework directly — see the logic work first, understand failures clearly, THEN lock it down.` },
    { q:`In "log() { echo \"[$(date +%H:%M:%S)] $1\"; }", what does calling "log \"Starting\"" actually print?`, options:[`Just the plain word "Starting", with nothing else added`,`A timestamp followed by "Starting", e.g. [14:02:11] Starting`,`A syntax error, since log isn't a real built-in bash command`,`Nothing prints at all — functions aren't allowed to use echo`], correct:1, why:`The function combines command substitution (the timestamp) with its own $1 (the message passed in) into one formatted line.` },
    { q:`A script works fine typed manually but fails when run from cron. What's most likely the issue?`, options:[`Cron itself is broken and needs to be reinstalled`,`Cron runs with a stripped-down environment (often missing PATH) that the script assumes exists`,`Shell scripts are fundamentally unable to run from cron at all`,`The script would need to be completely rewritten in Python`], correct:1, why:`Interactive shells load extra environment setup that cron does not — using absolute paths or sourcing the profile fixes it.` },
    { q:`What's the recommended first step before writing a script that checks disk usage and cleans up old files?`, options:[`Sit down and write the full, complete script immediately`,`Manually run df -h, du -sh, and find by hand until you know the exact commands that work`,`Add set -euo pipefail to the file before writing any logic`,`Ask a teammate to write the entire script on your behalf`], correct:1, why:`Following the thinking framework — prove the commands work by hand first, then turn them into a script.` },
    { q:`By the time you reach the deploy script capstone, which concepts does it actually combine?`, options:[`Only basic variables and the echo command, nothing more`,`Arguments, functions, set -e, || fallback handling, and command substitution together`,`None of it — the whole thing uses completely new, unseen syntax`,`Only for and while loops, and nothing else`], correct:1, why:`The deploy script is deliberately built from nothing but ideas already taught in earlier lessons — proof that by Lesson 15 you already know everything needed.` }
  ];
